// Auto-generated for ccaa conference grouping.
// Source: ccaa-current-teams.json
// Regenerate: python3 scripts/generate-college-conferences.py --league ccaa
// Generated: 2026-08-12

import {
  createCollegeConferenceGrouper,
  type CollegeConferenceGroup,
  type CollegeConferenceMeta,
} from "./college-conference-core";

export type CcaaConferenceMeta = CollegeConferenceMeta;
export type CcaaConferenceGroup<T> = CollegeConferenceGroup<T>;

const CONFERENCES: readonly CollegeConferenceMeta[] = [
  {
    slug: "alberta",
    name: "Alberta",
    teamSlugs: [
    "S.Alberta Institute of Tech",
    "S.Alberta Institute of Technology",
    "Southern Alberta Inst.of Tech",
    "Southern Alberta Institute of Technology",
    "s-alberta-institute-of-tech",
    "s-alberta-institute-of-technology",
    "s.alberta institute of tech",
    "s.alberta institute of technology",
    "saiot",
    "sait",
    "salberta-institute-of-tech",
    "salberta-institute-of-technology",
    "siot",
    "southern alberta inst.of tech",
    "southern alberta institute of technology",
    "southern-alberta-inst-of-tech",
    "southern-alberta-institute-of-technology",
    "southern-alberta-instof-tech",
  ],
    teamNames: [
    "S.Alberta Institute of Tech",
    "S.Alberta Institute of Technology",
    "Southern Alberta Inst.of Tech",
    "Southern Alberta Institute of Technology",
    "s-alberta-institute-of-tech",
    "s-alberta-institute-of-technology",
    "s.alberta institute of tech",
    "s.alberta institute of technology",
    "saiot",
    "sait",
    "salberta-institute-of-tech",
    "salberta-institute-of-technology",
    "siot",
    "southern alberta inst.of tech",
    "southern alberta institute of technology",
    "southern-alberta-inst-of-tech",
    "southern-alberta-institute-of-technology",
    "southern-alberta-instof-tech",
  ],
    canonicalSchools: [
    "S.Alberta Institute of Tech",
    "S.Alberta Institute of Technology",
    "Southern Alberta Inst.of Tech",
    "Southern Alberta Institute of Technology",
  ],
  },  {
    slug: "british-columbia",
    name: "British Columbia",
    teamSlugs: [
    "Northern British Columbia",
    "Richmond, BC / Vancouver College",
    "University of Northern British Columbia",
    "northern-british-columbia",
    "rb-vc",
    "rb/vc",
    "richmond, bc / vancouver college",
    "richmond-bc-vancouver-college",
    "university of northern british columbia",
    "university-of-northern-british-columbia",
    "uonbc",
  ],
    teamNames: [
    "Northern British Columbia",
    "Richmond, BC / Vancouver College",
    "University of Northern British Columbia",
    "northern-british-columbia",
    "rb-vc",
    "rb/vc",
    "richmond, bc / vancouver college",
    "richmond-bc-vancouver-college",
    "university of northern british columbia",
    "university-of-northern-british-columbia",
    "uonbc",
  ],
    canonicalSchools: [
    "Richmond, BC / Vancouver College",
    "University of Northern British Columbia",
  ],
  },  {
    slug: "nova-scotia",
    name: "Nova Scotia",
    teamSlugs: [
    "Nova Scotia Agriculture College",
    "nova scotia agriculture college",
    "nova-scotia-agriculture-college",
    "nsac",
  ],
    teamNames: [
    "Nova Scotia Agriculture College",
    "nova scotia agriculture college",
    "nova-scotia-agriculture-college",
    "nsac",
  ],
    canonicalSchools: [
    "Nova Scotia Agriculture College",
  ],
  },  {
    slug: "other",
    name: "Other",
    teamSlugs: [
    "Ahuntsic",
    "Alb-Augustana",
    "Algoma University",
    "Algonquin",
    "Ambrose",
    "Andrews University",
    "Appalachian Bible College",
    "Arlington Baptist University",
    "Association Free Lutheran Bible College",
    "Baptist Bible College, MO",
    "Baptist Florida",
    "Baptist University of Florida",
    "Barclay College",
    "Bethesda University",
    "Blue Lights College",
    "Bob Jones University",
    "Boyce College",
    "Briercrest",
    "Bristol University",
    "CEGEP de Ste.Foy",
    "California Miramar University",
    "Calvary Chapel Bible College",
    "Calvary University",
    "Cambrian College",
    "Camosun",
    "Campbellsville University at Harrodsburg",
    "Canadian Mennonite University",
    "Canadore",
    "Capilano",
    "Carolina Christian College",
    "Carolina University",
    "Carver Bible College",
    "Cbc",
    "Centennial",
    "Central Christian College of the Bible",
    "Ch.-St-Lambert",
    "Champion Christian College",
    "Champlain College division 2",
    "Christian Heritage College",
    "Clearwater Christian College",
    "Clinton College",
    "Colege Montmorency",
    "College Champlain-SaintLambert",
    "College Champlain-St.Lambert",
    "College of Biblical Studies",
    "College of Sequoias",
    "College of the Ozarks",
    "Coll\u00e8ge Edouard-Montpetit",
    "Columbia International University",
    "Concordia",
    "Conestoga",
    "Crandall",
    "Crossroads College",
    "Crowley's Ridge College",
    "Dalhousie",
    "Dalhousie Agricultural Campus",
    "Dallas Christian College",
    "Dartmouth College",
    "Dawson",
    "Dayspring Bible College",
    "Douglas",
    "Durham",
    "Ecclesia College",
    "Edouard-Montp.",
    "El Camino College Compton Center",
    "Emmaus Bible College",
    "Faith Baptist Bible College",
    "Fanshawe",
    "Fleming",
    "Four Winds University",
    "Free Lutheran Bible College",
    "Fullerton College",
    "Gavilan College",
    "George Brown",
    "Georgian",
    "Grace Bible College",
    "Grace Christian University",
    "Grace University",
    "Grande Prairie",
    "Grande Prairie Regional College",
    "Grant McEwan College",
    "Great Lakes Chr istian College",
    "Great Lakes Christian College",
    "Hillsdale Baptist",
    "Hillsdale FBBC",
    "Hillsdale Freewill Baptist Bible College",
    "Holland",
    "Holland Hurricanes",
    "Holy Patriot University",
    "Humber",
    "Jean-De-Breb.",
    "John Abbott",
    "Johnson University",
    "Johnson University, FL",
    "Johnson University, TN",
    "Johnson, TN",
    "Justice College",
    "Justice University",
    "Kansas Christian College",
    "Kentucky Christian University",
    "Keyano",
    "King'S Univ.",
    "Kuyper College",
    "Kwantlen Polytechnic University",
    "La Cite",
    "Lakeland",
    "Lambton",
    "Langara",
    "Lethbridge",
    "Life Pacific College",
    "Lincoln University",
    "Long Beach CC",
    "Los Angeles College of Divinity",
    "Loyalist",
    "MCC Toronto Basket",
    "MacEwan",
    "Manhattan Chr istian College",
    "Manhattan Christian College",
    "Maryland Bible College",
    "Medicine Hat",
    "Miami Dade",
    "Miami Hamilton",
    "Miami University Hamilton",
    "Miami University Middletown",
    "Mid Continent College",
    "Mid-Atlantic Christian University",
    "Mohawk",
    "Montmorency",
    "Moody Bible Institute",
    "Morthland College",
    "Mount Allison",
    "Msvu",
    "Multnomah University",
    "Nait",
    "Nebraska Christian College",
    "Nelson University",
    "New College of Florida",
    "New Hope Christian College",
    "New Hope College",
    "Niagara",
    "Nobel University",
    "North American University",
    "Northwest Indian College",
    "Nwp",
    "Oak Hills Christian College",
    "Oakland City University",
    "Ohio Christian University",
    "Ohio University Chillicothe",
    "Okanagan",
    "Olds",
    "Outaouais",
    "Ozark Christian College",
    "Paine College",
    "Paul Quinn College",
    "Pensacola Christian College",
    "Piedmont International University",
    "Pittsburgh-Titusville",
    "Portland Bible College",
    "Providence University College",
    "Puget Sound Christian College",
    "Quest University",
    "Randall University",
    "Red Deer",
    "Red River College",
    "Redeemer",
    "Regent University",
    "Rhema Bible College",
    "Ridley College",
    "SAGU American Indian College",
    "SE Baptist",
    "Saddleback JC",
    "Saint Katherine",
    "Saint Katherine College",
    "Saint Louis Christian College",
    "SaintClair",
    "SaintLawrence",
    "SaintMary's University College",
    "SaintThomas",
    "Sainte-Foy",
    "Sait",
    "San Jose City College Jaguars",
    "Sault College",
    "Seminary",
    "Seneca",
    "Sherbrooke",
    "Sheridan",
    "Simmons College of Kentucky",
    "Sisseton Wahpeton College",
    "Southeastern Baptist College",
    "Spurgeon College",
    "St. Louis Christian College",
    "St.Clair",
    "St.Lawrence",
    "St.Mary's University College",
    "St.Thomas",
    "Stmu",
    "Team Ahuntsic",
    "Tennessee Temple University",
    "The King'S",
    "The Word of Life Bible Institute",
    "Thetford",
    "Toccoa Falls College",
    "Toronto at Mississauga",
    "Trinity Baptist College",
    "Trinity Bible College",
    "Trinity College, FL",
    "U of T Mississauga",
    "Unbsj",
    "Union Adventist University",
    "Union College",
    "University of Los Angeles College of Divinity",
    "University of Pittsburgh-Titusville",
    "University of Puget Sound Christian College",
    "University of Saint Katherine",
    "University of Toronto at Mississauga",
    "UofA-Augustana",
    "Valley Forge Christian College",
    "Vanier",
    "Viu",
    "Volunteer State Community College",
    "Warner Pacific College",
    "Welch College",
    "West Coast Baptist College",
    "West Los Angeles College",
    "West Valley JC",
    "Westcliff University",
    "Yellowstone Chr.",
    "Yellowstone Christian College",
    "abc",
    "aflbc",
    "ahunts",
    "ahuntsic",
    "alb-au",
    "alb-augustana",
    "alg",
    "algoma university",
    "algoma-university",
    "algonquin",
    "ambros",
    "ambrose",
    "andrews university",
    "andrews-university",
    "appalachian bible college",
    "appalachian-bible-college",
    "arlington baptist university",
    "arlington-baptist-university",
    "association free lutheran bible college",
    "association-free-lutheran-bible-college",
    "au",
    "baptist bible college, mo",
    "baptist university of florida",
    "baptist-bible-college-mo",
    "baptist-florida",
    "baptist-university-of-florida",
    "barclay college",
    "barclay-college",
    "bbcm",
    "bc",
    "bethesda university",
    "bethesda-university",
    "bju",
    "blc",
    "blue lights college",
    "blue-lights-college",
    "bob jones university",
    "bob-jones-university",
    "boyce college",
    "boyce-college",
    "brierc",
    "briercrest",
    "bristol university",
    "bristol-university",
    "bu",
    "buof",
    "california miramar university",
    "california-miramar-university",
    "calvary chapel bible college",
    "calvary university",
    "calvary-chapel-bible-college",
    "calvary-university",
    "cambrian college",
    "cambrian-college",
    "camosu",
    "camosun",
    "campbellsville university at harrodsburg",
    "campbellsville-university-at-harrodsburg",
    "canadian mennonite university",
    "canadian-mennonite-university",
    "canado",
    "canadore",
    "cap",
    "capilano",
    "carolina christian college",
    "carolina university",
    "carolina-christian-college",
    "carolina-university",
    "carver bible college",
    "carver-bible-college",
    "cbc",
    "cc",
    "ccbc",
    "ccc",
    "cccotb",
    "ccd2",
    "cds",
    "ce",
    "cegep de ste.foy",
    "cegep-de-ste-foy",
    "cegep-de-stefoy",
    "cen",
    "centennial",
    "central christian college of the bible",
    "central-christian-college-of-the-bible",
    "ch-st",
    "ch-st-lambert",
    "ch.-st",
    "ch.-st-lambert",
    "champion christian college",
    "champion-christian-college",
    "champlain college division 2",
    "champlain-college-division-2",
    "chc",
    "christian heritage college",
    "christian-heritage-college",
    "ciu",
    "clearwater christian college",
    "clearwater-christian-college",
    "clinton college",
    "clinton-college",
    "cm",
    "cmu",
    "cobs",
    "colege montmorency",
    "colege-montmorency",
    "coll-ge-edouard-montpetit",
    "college champlain-st.lambert",
    "college of biblical studies",
    "college of sequoias",
    "college of the ozarks",
    "college-champlain-saintlambert",
    "college-champlain-st-lambert",
    "college-champlain-stlambert",
    "college-of-biblical-studies",
    "college-of-sequoias",
    "college-of-the-ozarks",
    "coll\u00e8ge edouard-montpetit",
    "columbia international university",
    "columbia-international-university",
    "concor",
    "concordia",
    "conest",
    "conestoga",
    "cos",
    "coto",
    "cranda",
    "crandall",
    "crc",
    "crossroads college",
    "crossroads-college",
    "crowley's ridge college",
    "crowley-s-ridge-college",
    "crowleys-ridge-college",
    "cu",
    "cuah",
    "dac",
    "dalhou",
    "dalhousie",
    "dalhousie agricultural campus",
    "dalhousie-agricultural-campus",
    "dallas christian college",
    "dallas-christian-college",
    "dartmouth college",
    "dartmouth-college",
    "daw",
    "dawson",
    "dayspring bible college",
    "dayspring-bible-college",
    "dbc",
    "dc",
    "dcc",
    "dougla",
    "douglas",
    "durham",
    "ebc",
    "ec",
    "ecccc",
    "ecclesia college",
    "ecclesia-college",
    "edouar",
    "edouard-montp",
    "edouard-montp.",
    "el camino college compton center",
    "el-camino-college-compton-center",
    "emmaus bible college",
    "emmaus-bible-college",
    "faith baptist bible college",
    "faith-baptist-bible-college",
    "fan",
    "fanshawe",
    "fbbc",
    "fc",
    "flbc",
    "flemin",
    "fleming",
    "four winds university",
    "four-winds-university",
    "free lutheran bible college",
    "free-lutheran-bible-college",
    "fullerton college",
    "fullerton-college",
    "fwu",
    "gavilan college",
    "gavilan-college",
    "gb",
    "gbc",
    "gc",
    "gcu",
    "george brown",
    "george-brown",
    "georgi",
    "georgian",
    "glcc",
    "glcic",
    "gmc",
    "gp",
    "gprc",
    "grace bible college",
    "grace christian university",
    "grace university",
    "grace-bible-college",
    "grace-christian-university",
    "grace-university",
    "grande prairie",
    "grande prairie regional college",
    "grande-prairie",
    "grande-prairie-regional-college",
    "grant mcewan college",
    "grant-mcewan-college",
    "great lakes chr istian college",
    "great lakes christian college",
    "great-lakes-chr-istian-college",
    "great-lakes-christian-college",
    "gu",
    "hb",
    "hf",
    "hfbbc",
    "hh",
    "hillsdale baptist",
    "hillsdale fbbc",
    "hillsdale freewill baptist bible college",
    "hillsdale-baptist",
    "hillsdale-fbbc",
    "hillsdale-freewill-baptist-bible-college",
    "hol",
    "holland",
    "holland hurricanes",
    "holland-hurricanes",
    "holy patriot university",
    "holy-patriot-university",
    "hpu",
    "hum",
    "humber",
    "ja",
    "jc",
    "jean-d",
    "jean-de-breb",
    "jean-de-breb.",
    "john abbott",
    "john-abbott",
    "johnson university",
    "johnson university, fl",
    "johnson university, tn",
    "johnson, tn",
    "johnson-tn",
    "johnson-university",
    "johnson-university-fl",
    "johnson-university-tn",
    "jt",
    "ju",
    "juf",
    "justice college",
    "justice university",
    "justice-college",
    "justice-university",
    "jut",
    "kansas christian college",
    "kansas-christian-college",
    "kc",
    "kcc",
    "kcu",
    "kentucky christian university",
    "kentucky-christian-university",
    "keyano",
    "king's univ.",
    "king-s-univ",
    "kings-univ",
    "kpu",
    "kuyper college",
    "kuyper-college",
    "kwantlen polytechnic university",
    "kwantlen-polytechnic-university",
    "la cite",
    "la-cite",
    "lak",
    "lakeland",
    "lambto",
    "lambton",
    "langar",
    "langara",
    "lbc",
    "lc",
    "lethbr",
    "lethbridge",
    "life pacific college",
    "life-pacific-college",
    "lincoln university",
    "lincoln-university",
    "long beach cc",
    "long-beach-cc",
    "los-angeles-college-of-divinity",
    "loyali",
    "loyalist",
    "lpc",
    "lu",
    "ma",
    "macewa",
    "macewan",
    "manhattan chr istian college",
    "manhattan christian college",
    "manhattan-chr-istian-college",
    "manhattan-christian-college",
    "maryland bible college",
    "maryland-bible-college",
    "mbc",
    "mbi",
    "mc",
    "mcc",
    "mcc toronto basket",
    "mcc-toronto-basket",
    "mcic",
    "mcu",
    "md",
    "medicine hat",
    "medicine-hat",
    "mh",
    "miami dade",
    "miami hamilton",
    "miami university hamilton",
    "miami university middletown",
    "miami-dade",
    "miami-hamilton",
    "miami-university-hamilton",
    "miami-university-middletown",
    "mid continent college",
    "mid-atlantic christian university",
    "mid-atlantic-christian-university",
    "mid-continent-college",
    "moh",
    "mohawk",
    "mon",
    "montmorency",
    "moody bible institute",
    "moody-bible-institute",
    "morthland college",
    "morthland-college",
    "mount allison",
    "mount-allison",
    "msvu",
    "mtb",
    "mu",
    "muh",
    "multnomah university",
    "multnomah-university",
    "mum",
    "nait",
    "nau",
    "ncc",
    "ncof",
    "nebraska christian college",
    "nebraska-christian-college",
    "nelson university",
    "nelson-university",
    "new college of florida",
    "new hope christian college",
    "new hope college",
    "new-college-of-florida",
    "new-hope-christian-college",
    "new-hope-college",
    "nhc",
    "nhcc",
    "niagar",
    "niagara",
    "nic",
    "nobel university",
    "nobel-university",
    "north american university",
    "north-american-university",
    "northwest indian college",
    "northwest-indian-college",
    "nu",
    "nwp",
    "oak hills christian college",
    "oak-hills-christian-college",
    "oakland city university",
    "oakland-city-university",
    "occ",
    "ocu",
    "ohcc",
    "ohio christian university",
    "ohio university chillicothe",
    "ohio-christian-university",
    "ohio-university-chillicothe",
    "okanag",
    "okanagan",
    "olds",
    "ouc",
    "outaou",
    "outaouais",
    "ozark christian college",
    "ozark-christian-college",
    "paine college",
    "paine-college",
    "paul quinn college",
    "paul-quinn-college",
    "pbc",
    "pc",
    "pcc",
    "pensacola christian college",
    "pensacola-christian-college",
    "piedmont international university",
    "piedmont-international-university",
    "pittsburgh-titusville",
    "piu",
    "portland bible college",
    "portland-bible-college",
    "pqc",
    "providence university college",
    "providence-university-college",
    "puc",
    "puget-sound-christian-college",
    "qu",
    "quest university",
    "quest-university",
    "randall university",
    "randall-university",
    "rbc",
    "rc",
    "rd",
    "red deer",
    "red river college",
    "red-deer",
    "red-river-college",
    "redeem",
    "redeemer",
    "regent university",
    "regent-university",
    "rhema bible college",
    "rhema-bible-college",
    "ridley college",
    "ridley-college",
    "rrc",
    "ru",
    "saddleback jc",
    "saddleback-jc",
    "sagu american indian college",
    "sagu-american-indian-college",
    "saic",
    "saint katherine college",
    "saint-katherine",
    "saint-katherine-college",
    "saint-louis-christian-college",
    "saintclair",
    "sainte",
    "sainte-foy",
    "saintlawrence",
    "saintmarys-university-college",
    "saintthomas",
    "sait",
    "san jose city college jaguars",
    "san-jose-city-college-jaguars",
    "sault college",
    "sault-college",
    "sb",
    "sbc",
    "sc",
    "scok",
    "se baptist",
    "se-baptist",
    "semina",
    "seminary",
    "sen",
    "seneca",
    "sherbr",
    "sherbrooke",
    "sherid",
    "sheridan",
    "simmons college of kentucky",
    "simmons-college-of-kentucky",
    "sisseton wahpeton college",
    "sisseton-wahpeton-college",
    "sj",
    "sjccj",
    "skc",
    "slcc",
    "southeastern baptist college",
    "southeastern-baptist-college",
    "spurgeon college",
    "spurgeon-college",
    "st",
    "st-clair",
    "st-lawrence",
    "st-louis-christian-college",
    "st-mary-s-university-college",
    "st-thomas",
    "st.",
    "st. louis christian college",
    "st.clair",
    "st.law",
    "st.lawrence",
    "st.mary's university college",
    "st.tho",
    "st.thomas",
    "stclair",
    "stlaw",
    "stlawrence",
    "stmarys-university-college",
    "stmu",
    "sttho",
    "stthomas",
    "suc",
    "swc",
    "ta",
    "tbc",
    "tcf",
    "team ahuntsic",
    "team-ahuntsic",
    "tennessee temple university",
    "tennessee-temple-university",
    "tfc",
    "the king's",
    "the word of life bible institute",
    "the-king-s",
    "the-kings",
    "the-word-of-life-bible-institute",
    "thetfo",
    "thetford",
    "tk",
    "toccoa falls college",
    "toccoa-falls-college",
    "toronto-at-mississauga",
    "trinity baptist college",
    "trinity bible college",
    "trinity college, fl",
    "trinity-baptist-college",
    "trinity-bible-college",
    "trinity-college-fl",
    "ttu",
    "twolbi",
    "u of t mississauga",
    "u-of-t-mississauga",
    "uau",
    "uc",
    "unbsj",
    "union adventist university",
    "union college",
    "union-adventist-university",
    "union-college",
    "university of los angeles college of divinity",
    "university of pittsburgh-titusville",
    "university of puget sound christian college",
    "university of saint katherine",
    "university of toronto at mississauga",
    "university-of-los-angeles-college-of-divinity",
    "university-of-pittsburgh-titusville",
    "university-of-puget-sound-christian-college",
    "university-of-saint-katherine",
    "university-of-toronto-at-mississauga",
    "uofa-a",
    "uofa-augustana",
    "uokc",
    "uolaco",
    "uop",
    "uopscc",
    "uosk",
    "uotam",
    "uotm",
    "valley forge christian college",
    "valley-forge-christian-college",
    "vanier",
    "vfcc",
    "viu",
    "volunteer state community college",
    "volunteer-state-community-college",
    "vscc",
    "warner pacific college",
    "warner-pacific-college",
    "wc",
    "wcbc",
    "welch college",
    "welch-college",
    "west coast baptist college",
    "west los angeles college",
    "west valley jc",
    "west-coast-baptist-college",
    "west-los-angeles-college",
    "west-valley-jc",
    "westcliff university",
    "westcliff-university",
    "wlac",
    "wpc",
    "wu",
    "wvj",
    "yc",
    "ycc",
    "yellowstone chr.",
    "yellowstone christian college",
    "yellowstone-chr",
    "yellowstone-christian-college",
  ],
    teamNames: [
    "Ahuntsic",
    "Alb-Augustana",
    "Algoma University",
    "Algonquin",
    "Ambrose",
    "Andrews University",
    "Appalachian Bible College",
    "Arlington Baptist University",
    "Association Free Lutheran Bible College",
    "Baptist Bible College, MO",
    "Baptist Florida",
    "Baptist University of Florida",
    "Barclay College",
    "Bethesda University",
    "Blue Lights College",
    "Bob Jones University",
    "Boyce College",
    "Briercrest",
    "Bristol University",
    "CEGEP de Ste.Foy",
    "California Miramar University",
    "Calvary Chapel Bible College",
    "Calvary University",
    "Cambrian College",
    "Camosun",
    "Campbellsville University at Harrodsburg",
    "Canadian Mennonite University",
    "Canadore",
    "Capilano",
    "Carolina Christian College",
    "Carolina University",
    "Carver Bible College",
    "Cbc",
    "Centennial",
    "Central Christian College of the Bible",
    "Ch.-St-Lambert",
    "Champion Christian College",
    "Champlain College division 2",
    "Christian Heritage College",
    "Clearwater Christian College",
    "Clinton College",
    "Colege Montmorency",
    "College Champlain-SaintLambert",
    "College Champlain-St.Lambert",
    "College of Biblical Studies",
    "College of Sequoias",
    "College of the Ozarks",
    "Coll\u00e8ge Edouard-Montpetit",
    "Columbia International University",
    "Concordia",
    "Conestoga",
    "Crandall",
    "Crossroads College",
    "Crowley's Ridge College",
    "Dalhousie",
    "Dalhousie Agricultural Campus",
    "Dallas Christian College",
    "Dartmouth College",
    "Dawson",
    "Dayspring Bible College",
    "Douglas",
    "Durham",
    "Ecclesia College",
    "Edouard-Montp.",
    "El Camino College Compton Center",
    "Emmaus Bible College",
    "Faith Baptist Bible College",
    "Fanshawe",
    "Fleming",
    "Four Winds University",
    "Free Lutheran Bible College",
    "Fullerton College",
    "Gavilan College",
    "George Brown",
    "Georgian",
    "Grace Bible College",
    "Grace Christian University",
    "Grace University",
    "Grande Prairie",
    "Grande Prairie Regional College",
    "Grant McEwan College",
    "Great Lakes Chr istian College",
    "Great Lakes Christian College",
    "Hillsdale Baptist",
    "Hillsdale FBBC",
    "Hillsdale Freewill Baptist Bible College",
    "Holland",
    "Holland Hurricanes",
    "Holy Patriot University",
    "Humber",
    "Jean-De-Breb.",
    "John Abbott",
    "Johnson University",
    "Johnson University, FL",
    "Johnson University, TN",
    "Johnson, TN",
    "Justice College",
    "Justice University",
    "Kansas Christian College",
    "Kentucky Christian University",
    "Keyano",
    "King'S Univ.",
    "Kuyper College",
    "Kwantlen Polytechnic University",
    "La Cite",
    "Lakeland",
    "Lambton",
    "Langara",
    "Lethbridge",
    "Life Pacific College",
    "Lincoln University",
    "Long Beach CC",
    "Los Angeles College of Divinity",
    "Loyalist",
    "MCC Toronto Basket",
    "MacEwan",
    "Manhattan Chr istian College",
    "Manhattan Christian College",
    "Maryland Bible College",
    "Medicine Hat",
    "Miami Dade",
    "Miami Hamilton",
    "Miami University Hamilton",
    "Miami University Middletown",
    "Mid Continent College",
    "Mid-Atlantic Christian University",
    "Mohawk",
    "Montmorency",
    "Moody Bible Institute",
    "Morthland College",
    "Mount Allison",
    "Msvu",
    "Multnomah University",
    "Nait",
    "Nebraska Christian College",
    "Nelson University",
    "New College of Florida",
    "New Hope Christian College",
    "New Hope College",
    "Niagara",
    "Nobel University",
    "North American University",
    "Northwest Indian College",
    "Nwp",
    "Oak Hills Christian College",
    "Oakland City University",
    "Ohio Christian University",
    "Ohio University Chillicothe",
    "Okanagan",
    "Olds",
    "Outaouais",
    "Ozark Christian College",
    "Paine College",
    "Paul Quinn College",
    "Pensacola Christian College",
    "Piedmont International University",
    "Pittsburgh-Titusville",
    "Portland Bible College",
    "Providence University College",
    "Puget Sound Christian College",
    "Quest University",
    "Randall University",
    "Red Deer",
    "Red River College",
    "Redeemer",
    "Regent University",
    "Rhema Bible College",
    "Ridley College",
    "SAGU American Indian College",
    "SE Baptist",
    "Saddleback JC",
    "Saint Katherine",
    "Saint Katherine College",
    "Saint Louis Christian College",
    "SaintClair",
    "SaintLawrence",
    "SaintMary's University College",
    "SaintThomas",
    "Sainte-Foy",
    "Sait",
    "San Jose City College Jaguars",
    "Sault College",
    "Seminary",
    "Seneca",
    "Sherbrooke",
    "Sheridan",
    "Simmons College of Kentucky",
    "Sisseton Wahpeton College",
    "Southeastern Baptist College",
    "Spurgeon College",
    "St. Louis Christian College",
    "St.Clair",
    "St.Lawrence",
    "St.Mary's University College",
    "St.Thomas",
    "Stmu",
    "Team Ahuntsic",
    "Tennessee Temple University",
    "The King'S",
    "The Word of Life Bible Institute",
    "Thetford",
    "Toccoa Falls College",
    "Toronto at Mississauga",
    "Trinity Baptist College",
    "Trinity Bible College",
    "Trinity College, FL",
    "U of T Mississauga",
    "Unbsj",
    "Union Adventist University",
    "Union College",
    "University of Los Angeles College of Divinity",
    "University of Pittsburgh-Titusville",
    "University of Puget Sound Christian College",
    "University of Saint Katherine",
    "University of Toronto at Mississauga",
    "UofA-Augustana",
    "Valley Forge Christian College",
    "Vanier",
    "Viu",
    "Volunteer State Community College",
    "Warner Pacific College",
    "Welch College",
    "West Coast Baptist College",
    "West Los Angeles College",
    "West Valley JC",
    "Westcliff University",
    "Yellowstone Chr.",
    "Yellowstone Christian College",
    "abc",
    "aflbc",
    "ahunts",
    "ahuntsic",
    "alb-au",
    "alb-augustana",
    "alg",
    "algoma university",
    "algoma-university",
    "algonquin",
    "ambros",
    "ambrose",
    "andrews university",
    "andrews-university",
    "appalachian bible college",
    "appalachian-bible-college",
    "arlington baptist university",
    "arlington-baptist-university",
    "association free lutheran bible college",
    "association-free-lutheran-bible-college",
    "au",
    "baptist bible college, mo",
    "baptist university of florida",
    "baptist-bible-college-mo",
    "baptist-florida",
    "baptist-university-of-florida",
    "barclay college",
    "barclay-college",
    "bbcm",
    "bc",
    "bethesda university",
    "bethesda-university",
    "bju",
    "blc",
    "blue lights college",
    "blue-lights-college",
    "bob jones university",
    "bob-jones-university",
    "boyce college",
    "boyce-college",
    "brierc",
    "briercrest",
    "bristol university",
    "bristol-university",
    "bu",
    "buof",
    "california miramar university",
    "california-miramar-university",
    "calvary chapel bible college",
    "calvary university",
    "calvary-chapel-bible-college",
    "calvary-university",
    "cambrian college",
    "cambrian-college",
    "camosu",
    "camosun",
    "campbellsville university at harrodsburg",
    "campbellsville-university-at-harrodsburg",
    "canadian mennonite university",
    "canadian-mennonite-university",
    "canado",
    "canadore",
    "cap",
    "capilano",
    "carolina christian college",
    "carolina university",
    "carolina-christian-college",
    "carolina-university",
    "carver bible college",
    "carver-bible-college",
    "cbc",
    "cc",
    "ccbc",
    "ccc",
    "cccotb",
    "ccd2",
    "cds",
    "ce",
    "cegep de ste.foy",
    "cegep-de-ste-foy",
    "cegep-de-stefoy",
    "cen",
    "centennial",
    "central christian college of the bible",
    "central-christian-college-of-the-bible",
    "ch-st",
    "ch-st-lambert",
    "ch.-st",
    "ch.-st-lambert",
    "champion christian college",
    "champion-christian-college",
    "champlain college division 2",
    "champlain-college-division-2",
    "chc",
    "christian heritage college",
    "christian-heritage-college",
    "ciu",
    "clearwater christian college",
    "clearwater-christian-college",
    "clinton college",
    "clinton-college",
    "cm",
    "cmu",
    "cobs",
    "colege montmorency",
    "colege-montmorency",
    "coll-ge-edouard-montpetit",
    "college champlain-st.lambert",
    "college of biblical studies",
    "college of sequoias",
    "college of the ozarks",
    "college-champlain-saintlambert",
    "college-champlain-st-lambert",
    "college-champlain-stlambert",
    "college-of-biblical-studies",
    "college-of-sequoias",
    "college-of-the-ozarks",
    "coll\u00e8ge edouard-montpetit",
    "columbia international university",
    "columbia-international-university",
    "concor",
    "concordia",
    "conest",
    "conestoga",
    "cos",
    "coto",
    "cranda",
    "crandall",
    "crc",
    "crossroads college",
    "crossroads-college",
    "crowley's ridge college",
    "crowley-s-ridge-college",
    "crowleys-ridge-college",
    "cu",
    "cuah",
    "dac",
    "dalhou",
    "dalhousie",
    "dalhousie agricultural campus",
    "dalhousie-agricultural-campus",
    "dallas christian college",
    "dallas-christian-college",
    "dartmouth college",
    "dartmouth-college",
    "daw",
    "dawson",
    "dayspring bible college",
    "dayspring-bible-college",
    "dbc",
    "dc",
    "dcc",
    "dougla",
    "douglas",
    "durham",
    "ebc",
    "ec",
    "ecccc",
    "ecclesia college",
    "ecclesia-college",
    "edouar",
    "edouard-montp",
    "edouard-montp.",
    "el camino college compton center",
    "el-camino-college-compton-center",
    "emmaus bible college",
    "emmaus-bible-college",
    "faith baptist bible college",
    "faith-baptist-bible-college",
    "fan",
    "fanshawe",
    "fbbc",
    "fc",
    "flbc",
    "flemin",
    "fleming",
    "four winds university",
    "four-winds-university",
    "free lutheran bible college",
    "free-lutheran-bible-college",
    "fullerton college",
    "fullerton-college",
    "fwu",
    "gavilan college",
    "gavilan-college",
    "gb",
    "gbc",
    "gc",
    "gcu",
    "george brown",
    "george-brown",
    "georgi",
    "georgian",
    "glcc",
    "glcic",
    "gmc",
    "gp",
    "gprc",
    "grace bible college",
    "grace christian university",
    "grace university",
    "grace-bible-college",
    "grace-christian-university",
    "grace-university",
    "grande prairie",
    "grande prairie regional college",
    "grande-prairie",
    "grande-prairie-regional-college",
    "grant mcewan college",
    "grant-mcewan-college",
    "great lakes chr istian college",
    "great lakes christian college",
    "great-lakes-chr-istian-college",
    "great-lakes-christian-college",
    "gu",
    "hb",
    "hf",
    "hfbbc",
    "hh",
    "hillsdale baptist",
    "hillsdale fbbc",
    "hillsdale freewill baptist bible college",
    "hillsdale-baptist",
    "hillsdale-fbbc",
    "hillsdale-freewill-baptist-bible-college",
    "hol",
    "holland",
    "holland hurricanes",
    "holland-hurricanes",
    "holy patriot university",
    "holy-patriot-university",
    "hpu",
    "hum",
    "humber",
    "ja",
    "jc",
    "jean-d",
    "jean-de-breb",
    "jean-de-breb.",
    "john abbott",
    "john-abbott",
    "johnson university",
    "johnson university, fl",
    "johnson university, tn",
    "johnson, tn",
    "johnson-tn",
    "johnson-university",
    "johnson-university-fl",
    "johnson-university-tn",
    "jt",
    "ju",
    "juf",
    "justice college",
    "justice university",
    "justice-college",
    "justice-university",
    "jut",
    "kansas christian college",
    "kansas-christian-college",
    "kc",
    "kcc",
    "kcu",
    "kentucky christian university",
    "kentucky-christian-university",
    "keyano",
    "king's univ.",
    "king-s-univ",
    "kings-univ",
    "kpu",
    "kuyper college",
    "kuyper-college",
    "kwantlen polytechnic university",
    "kwantlen-polytechnic-university",
    "la cite",
    "la-cite",
    "lak",
    "lakeland",
    "lambto",
    "lambton",
    "langar",
    "langara",
    "lbc",
    "lc",
    "lethbr",
    "lethbridge",
    "life pacific college",
    "life-pacific-college",
    "lincoln university",
    "lincoln-university",
    "long beach cc",
    "long-beach-cc",
    "los-angeles-college-of-divinity",
    "loyali",
    "loyalist",
    "lpc",
    "lu",
    "ma",
    "macewa",
    "macewan",
    "manhattan chr istian college",
    "manhattan christian college",
    "manhattan-chr-istian-college",
    "manhattan-christian-college",
    "maryland bible college",
    "maryland-bible-college",
    "mbc",
    "mbi",
    "mc",
    "mcc",
    "mcc toronto basket",
    "mcc-toronto-basket",
    "mcic",
    "mcu",
    "md",
    "medicine hat",
    "medicine-hat",
    "mh",
    "miami dade",
    "miami hamilton",
    "miami university hamilton",
    "miami university middletown",
    "miami-dade",
    "miami-hamilton",
    "miami-university-hamilton",
    "miami-university-middletown",
    "mid continent college",
    "mid-atlantic christian university",
    "mid-atlantic-christian-university",
    "mid-continent-college",
    "moh",
    "mohawk",
    "mon",
    "montmorency",
    "moody bible institute",
    "moody-bible-institute",
    "morthland college",
    "morthland-college",
    "mount allison",
    "mount-allison",
    "msvu",
    "mtb",
    "mu",
    "muh",
    "multnomah university",
    "multnomah-university",
    "mum",
    "nait",
    "nau",
    "ncc",
    "ncof",
    "nebraska christian college",
    "nebraska-christian-college",
    "nelson university",
    "nelson-university",
    "new college of florida",
    "new hope christian college",
    "new hope college",
    "new-college-of-florida",
    "new-hope-christian-college",
    "new-hope-college",
    "nhc",
    "nhcc",
    "niagar",
    "niagara",
    "nic",
    "nobel university",
    "nobel-university",
    "north american university",
    "north-american-university",
    "northwest indian college",
    "northwest-indian-college",
    "nu",
    "nwp",
    "oak hills christian college",
    "oak-hills-christian-college",
    "oakland city university",
    "oakland-city-university",
    "occ",
    "ocu",
    "ohcc",
    "ohio christian university",
    "ohio university chillicothe",
    "ohio-christian-university",
    "ohio-university-chillicothe",
    "okanag",
    "okanagan",
    "olds",
    "ouc",
    "outaou",
    "outaouais",
    "ozark christian college",
    "ozark-christian-college",
    "paine college",
    "paine-college",
    "paul quinn college",
    "paul-quinn-college",
    "pbc",
    "pc",
    "pcc",
    "pensacola christian college",
    "pensacola-christian-college",
    "piedmont international university",
    "piedmont-international-university",
    "pittsburgh-titusville",
    "piu",
    "portland bible college",
    "portland-bible-college",
    "pqc",
    "providence university college",
    "providence-university-college",
    "puc",
    "puget-sound-christian-college",
    "qu",
    "quest university",
    "quest-university",
    "randall university",
    "randall-university",
    "rbc",
    "rc",
    "rd",
    "red deer",
    "red river college",
    "red-deer",
    "red-river-college",
    "redeem",
    "redeemer",
    "regent university",
    "regent-university",
    "rhema bible college",
    "rhema-bible-college",
    "ridley college",
    "ridley-college",
    "rrc",
    "ru",
    "saddleback jc",
    "saddleback-jc",
    "sagu american indian college",
    "sagu-american-indian-college",
    "saic",
    "saint katherine college",
    "saint-katherine",
    "saint-katherine-college",
    "saint-louis-christian-college",
    "saintclair",
    "sainte",
    "sainte-foy",
    "saintlawrence",
    "saintmarys-university-college",
    "saintthomas",
    "sait",
    "san jose city college jaguars",
    "san-jose-city-college-jaguars",
    "sault college",
    "sault-college",
    "sb",
    "sbc",
    "sc",
    "scok",
    "se baptist",
    "se-baptist",
    "semina",
    "seminary",
    "sen",
    "seneca",
    "sherbr",
    "sherbrooke",
    "sherid",
    "sheridan",
    "simmons college of kentucky",
    "simmons-college-of-kentucky",
    "sisseton wahpeton college",
    "sisseton-wahpeton-college",
    "sj",
    "sjccj",
    "skc",
    "slcc",
    "southeastern baptist college",
    "southeastern-baptist-college",
    "spurgeon college",
    "spurgeon-college",
    "st",
    "st-clair",
    "st-lawrence",
    "st-louis-christian-college",
    "st-mary-s-university-college",
    "st-thomas",
    "st.",
    "st. louis christian college",
    "st.clair",
    "st.law",
    "st.lawrence",
    "st.mary's university college",
    "st.tho",
    "st.thomas",
    "stclair",
    "stlaw",
    "stlawrence",
    "stmarys-university-college",
    "stmu",
    "sttho",
    "stthomas",
    "suc",
    "swc",
    "ta",
    "tbc",
    "tcf",
    "team ahuntsic",
    "team-ahuntsic",
    "tennessee temple university",
    "tennessee-temple-university",
    "tfc",
    "the king's",
    "the word of life bible institute",
    "the-king-s",
    "the-kings",
    "the-word-of-life-bible-institute",
    "thetfo",
    "thetford",
    "tk",
    "toccoa falls college",
    "toccoa-falls-college",
    "toronto-at-mississauga",
    "trinity baptist college",
    "trinity bible college",
    "trinity college, fl",
    "trinity-baptist-college",
    "trinity-bible-college",
    "trinity-college-fl",
    "ttu",
    "twolbi",
    "u of t mississauga",
    "u-of-t-mississauga",
    "uau",
    "uc",
    "unbsj",
    "union adventist university",
    "union college",
    "union-adventist-university",
    "union-college",
    "university of los angeles college of divinity",
    "university of pittsburgh-titusville",
    "university of puget sound christian college",
    "university of saint katherine",
    "university of toronto at mississauga",
    "university-of-los-angeles-college-of-divinity",
    "university-of-pittsburgh-titusville",
    "university-of-puget-sound-christian-college",
    "university-of-saint-katherine",
    "university-of-toronto-at-mississauga",
    "uofa-a",
    "uofa-augustana",
    "uokc",
    "uolaco",
    "uop",
    "uopscc",
    "uosk",
    "uotam",
    "uotm",
    "valley forge christian college",
    "valley-forge-christian-college",
    "vanier",
    "vfcc",
    "viu",
    "volunteer state community college",
    "volunteer-state-community-college",
    "vscc",
    "warner pacific college",
    "warner-pacific-college",
    "wc",
    "wcbc",
    "welch college",
    "welch-college",
    "west coast baptist college",
    "west los angeles college",
    "west valley jc",
    "west-coast-baptist-college",
    "west-los-angeles-college",
    "west-valley-jc",
    "westcliff university",
    "westcliff-university",
    "wlac",
    "wpc",
    "wu",
    "wvj",
    "yc",
    "ycc",
    "yellowstone chr.",
    "yellowstone christian college",
    "yellowstone-chr",
    "yellowstone-christian-college",
  ],
    canonicalSchools: [
    "Ahuntsic",
    "Alb-Augustana",
    "Algoma University",
    "Algonquin",
    "Ambrose",
    "Andrews University",
    "Appalachian Bible College",
    "Arlington Baptist University",
    "Association Free Lutheran Bible College",
    "Baptist Bible College, MO",
    "Baptist University of Florida",
    "Barclay College",
    "Bethesda University",
    "Blue Lights College",
    "Bob Jones University",
    "Boyce College",
    "Briercrest",
    "Bristol University",
    "CEGEP de Ste.Foy",
    "California Miramar University",
    "Calvary Chapel Bible College",
    "Calvary University",
    "Cambrian College",
    "Camosun",
    "Campbellsville University at Harrodsburg",
    "Canadian Mennonite University",
    "Canadore",
    "Capilano",
    "Carolina Christian College",
    "Carolina University",
    "Carver Bible College",
    "Cbc",
    "Centennial",
    "Central Christian College of the Bible",
    "Ch.-St-Lambert",
    "Champion Christian College",
    "Champlain College division 2",
    "Christian Heritage College",
    "Clearwater Christian College",
    "Clinton College",
    "Colege Montmorency",
    "College Champlain-St.Lambert",
    "College of Biblical Studies",
    "College of Sequoias",
    "College of the Ozarks",
    "Coll\u00e8ge Edouard-Montpetit",
    "Columbia International University",
    "Concordia",
    "Conestoga",
    "Crandall",
    "Crossroads College",
    "Crowley's Ridge College",
    "Dalhousie",
    "Dalhousie Agricultural Campus",
    "Dallas Christian College",
    "Dartmouth College",
    "Dawson",
    "Dayspring Bible College",
    "Douglas",
    "Durham",
    "Ecclesia College",
    "Edouard-Montp.",
    "El Camino College Compton Center",
    "Emmaus Bible College",
    "Faith Baptist Bible College",
    "Fanshawe",
    "Fleming",
    "Four Winds University",
    "Free Lutheran Bible College",
    "Fullerton College",
    "Gavilan College",
    "George Brown",
    "Georgian",
    "Grace Bible College",
    "Grace Christian University",
    "Grace University",
    "Grande Prairie",
    "Grande Prairie Regional College",
    "Grant McEwan College",
    "Great Lakes Chr istian College",
    "Great Lakes Christian College",
    "Hillsdale Baptist",
    "Hillsdale FBBC",
    "Hillsdale Freewill Baptist Bible College",
    "Holland",
    "Holland Hurricanes",
    "Holy Patriot University",
    "Humber",
    "Jean-De-Breb.",
    "John Abbott",
    "Johnson University",
    "Johnson University, FL",
    "Johnson University, TN",
    "Johnson, TN",
    "Justice College",
    "Justice University",
    "Kansas Christian College",
    "Kentucky Christian University",
    "Keyano",
    "King'S Univ.",
    "Kuyper College",
    "Kwantlen Polytechnic University",
    "La Cite",
    "Lakeland",
    "Lambton",
    "Langara",
    "Lethbridge",
    "Life Pacific College",
    "Lincoln University",
    "Long Beach CC",
    "Loyalist",
    "MCC Toronto Basket",
    "MacEwan",
    "Manhattan Chr istian College",
    "Manhattan Christian College",
    "Maryland Bible College",
    "Medicine Hat",
    "Miami Dade",
    "Miami Hamilton",
    "Miami University Hamilton",
    "Miami University Middletown",
    "Mid Continent College",
    "Mid-Atlantic Christian University",
    "Mohawk",
    "Montmorency",
    "Moody Bible Institute",
    "Morthland College",
    "Mount Allison",
    "Msvu",
    "Multnomah University",
    "Nait",
    "Nebraska Christian College",
    "Nelson University",
    "New College of Florida",
    "New Hope Christian College",
    "New Hope College",
    "Niagara",
    "Nobel University",
    "North American University",
    "Northwest Indian College",
    "Nwp",
    "Oak Hills Christian College",
    "Oakland City University",
    "Ohio Christian University",
    "Ohio University Chillicothe",
    "Okanagan",
    "Olds",
    "Outaouais",
    "Ozark Christian College",
    "Paine College",
    "Paul Quinn College",
    "Pensacola Christian College",
    "Piedmont International University",
    "Portland Bible College",
    "Providence University College",
    "Quest University",
    "Randall University",
    "Red Deer",
    "Red River College",
    "Redeemer",
    "Regent University",
    "Rhema Bible College",
    "Ridley College",
    "SAGU American Indian College",
    "SE Baptist",
    "Saddleback JC",
    "Saint Katherine College",
    "Sainte-Foy",
    "Sait",
    "San Jose City College Jaguars",
    "Sault College",
    "Seminary",
    "Seneca",
    "Sherbrooke",
    "Sheridan",
    "Simmons College of Kentucky",
    "Sisseton Wahpeton College",
    "Southeastern Baptist College",
    "Spurgeon College",
    "St. Louis Christian College",
    "St.Clair",
    "St.Lawrence",
    "St.Mary's University College",
    "St.Thomas",
    "Stmu",
    "Team Ahuntsic",
    "Tennessee Temple University",
    "The King'S",
    "The Word of Life Bible Institute",
    "Thetford",
    "Toccoa Falls College",
    "Trinity Baptist College",
    "Trinity Bible College",
    "Trinity College, FL",
    "U of T Mississauga",
    "Unbsj",
    "Union Adventist University",
    "Union College",
    "University of Los Angeles College of Divinity",
    "University of Pittsburgh-Titusville",
    "University of Puget Sound Christian College",
    "University of Saint Katherine",
    "University of Toronto at Mississauga",
    "UofA-Augustana",
    "Valley Forge Christian College",
    "Vanier",
    "Viu",
    "Volunteer State Community College",
    "Warner Pacific College",
    "Welch College",
    "West Coast Baptist College",
    "West Los Angeles College",
    "West Valley JC",
    "Westcliff University",
    "Yellowstone Chr.",
    "Yellowstone Christian College",
  ],
  },
] as const;

const CANONICAL_SCHOOL_TO_CONFERENCE: Record<string, string> = {
  "ahuntsic": "other",
  "alb-augustana": "other",
  "algoma-university": "other",
  "algonquin": "other",
  "ambrose": "other",
  "andrews-university": "other",
  "appalachian-bible-college": "other",
  "arlington-baptist-university": "other",
  "association-free-lutheran-bible-college": "other",
  "baptist-bible-college-mo": "other",
  "baptist-university-of-florida": "other",
  "barclay-college": "other",
  "bethesda-university": "other",
  "blue-lights-college": "other",
  "bob-jones-university": "other",
  "boyce-college": "other",
  "briercrest": "other",
  "bristol-university": "other",
  "california-miramar-university": "other",
  "calvary-chapel-bible-college": "other",
  "calvary-university": "other",
  "cambrian-college": "other",
  "camosun": "other",
  "campbellsville-university-at-harrodsburg": "other",
  "canadian-mennonite-university": "other",
  "canadore": "other",
  "capilano": "other",
  "carolina-christian-college": "other",
  "carolina-university": "other",
  "carver-bible-college": "other",
  "cbc": "other",
  "cegep-de-stefoy": "other",
  "centennial": "other",
  "central-christian-college-of-the-bible": "other",
  "ch-st-lambert": "other",
  "champion-christian-college": "other",
  "champlain-college-division-2": "other",
  "christian-heritage-college": "other",
  "clearwater-christian-college": "other",
  "clinton-college": "other",
  "colege-montmorency": "other",
  "coll-ge-edouard-montpetit": "other",
  "college-champlain-stlambert": "other",
  "college-of-biblical-studies": "other",
  "college-of-sequoias": "other",
  "college-of-the-ozarks": "other",
  "columbia-international-university": "other",
  "concordia": "other",
  "conestoga": "other",
  "crandall": "other",
  "crossroads-college": "other",
  "crowleys-ridge-college": "other",
  "dalhousie": "other",
  "dalhousie-agricultural-campus": "other",
  "dallas-christian-college": "other",
  "dartmouth-college": "other",
  "dawson": "other",
  "dayspring-bible-college": "other",
  "douglas": "other",
  "durham": "other",
  "ecclesia-college": "other",
  "edouard-montp": "other",
  "el-camino-college-compton-center": "other",
  "emmaus-bible-college": "other",
  "faith-baptist-bible-college": "other",
  "fanshawe": "other",
  "fleming": "other",
  "four-winds-university": "other",
  "free-lutheran-bible-college": "other",
  "fullerton-college": "other",
  "gavilan-college": "other",
  "george-brown": "other",
  "georgian": "other",
  "grace-bible-college": "other",
  "grace-christian-university": "other",
  "grace-university": "other",
  "grande-prairie": "other",
  "grande-prairie-regional-college": "other",
  "grant-mcewan-college": "other",
  "great-lakes-chr-istian-college": "other",
  "great-lakes-christian-college": "other",
  "hillsdale-baptist": "other",
  "hillsdale-fbbc": "other",
  "hillsdale-freewill-baptist-bible-college": "other",
  "holland": "other",
  "holland-hurricanes": "other",
  "holy-patriot-university": "other",
  "humber": "other",
  "jean-de-breb": "other",
  "john-abbott": "other",
  "johnson-tn": "other",
  "johnson-university": "other",
  "johnson-university-fl": "other",
  "johnson-university-tn": "other",
  "justice-college": "other",
  "justice-university": "other",
  "kansas-christian-college": "other",
  "kentucky-christian-university": "other",
  "keyano": "other",
  "kings-univ": "other",
  "kuyper-college": "other",
  "kwantlen-polytechnic-university": "other",
  "la-cite": "other",
  "lakeland": "other",
  "lambton": "other",
  "langara": "other",
  "lethbridge": "other",
  "life-pacific-college": "other",
  "lincoln-university": "other",
  "long-beach-cc": "other",
  "loyalist": "other",
  "macewan": "other",
  "manhattan-chr-istian-college": "other",
  "manhattan-christian-college": "other",
  "maryland-bible-college": "other",
  "mcc-toronto-basket": "other",
  "medicine-hat": "other",
  "miami-dade": "other",
  "miami-hamilton": "other",
  "miami-university-hamilton": "other",
  "miami-university-middletown": "other",
  "mid-atlantic-christian-university": "other",
  "mid-continent-college": "other",
  "mohawk": "other",
  "montmorency": "other",
  "moody-bible-institute": "other",
  "morthland-college": "other",
  "mount-allison": "other",
  "msvu": "other",
  "multnomah-university": "other",
  "nait": "other",
  "nebraska-christian-college": "other",
  "nelson-university": "other",
  "new-college-of-florida": "other",
  "new-hope-christian-college": "other",
  "new-hope-college": "other",
  "niagara": "other",
  "nobel-university": "other",
  "north-american-university": "other",
  "northwest-indian-college": "other",
  "nova-scotia-agriculture-college": "nova-scotia",
  "nwp": "other",
  "oak-hills-christian-college": "other",
  "oakland-city-university": "other",
  "ohio-christian-university": "other",
  "ohio-university-chillicothe": "other",
  "okanagan": "other",
  "olds": "other",
  "outaouais": "other",
  "ozark-christian-college": "other",
  "paine-college": "other",
  "paul-quinn-college": "other",
  "pensacola-christian-college": "other",
  "piedmont-international-university": "other",
  "portland-bible-college": "other",
  "providence-university-college": "other",
  "quest-university": "other",
  "randall-university": "other",
  "red-deer": "other",
  "red-river-college": "other",
  "redeemer": "other",
  "regent-university": "other",
  "rhema-bible-college": "other",
  "richmond-bc-vancouver-college": "british-columbia",
  "ridley-college": "other",
  "saddleback-jc": "other",
  "sagu-american-indian-college": "other",
  "saint-katherine-college": "other",
  "sainte-foy": "other",
  "sait": "other",
  "salberta-institute-of-tech": "alberta",
  "salberta-institute-of-technology": "alberta",
  "san-jose-city-college-jaguars": "other",
  "sault-college": "other",
  "se-baptist": "other",
  "seminary": "other",
  "seneca": "other",
  "sherbrooke": "other",
  "sheridan": "other",
  "simmons-college-of-kentucky": "other",
  "sisseton-wahpeton-college": "other",
  "southeastern-baptist-college": "other",
  "southern-alberta-institute-of-technology": "alberta",
  "southern-alberta-instof-tech": "alberta",
  "spurgeon-college": "other",
  "st-louis-christian-college": "other",
  "stclair": "other",
  "stlawrence": "other",
  "stmarys-university-college": "other",
  "stmu": "other",
  "stthomas": "other",
  "team-ahuntsic": "other",
  "tennessee-temple-university": "other",
  "the-kings": "other",
  "the-word-of-life-bible-institute": "other",
  "thetford": "other",
  "toccoa-falls-college": "other",
  "trinity-baptist-college": "other",
  "trinity-bible-college": "other",
  "trinity-college-fl": "other",
  "u-of-t-mississauga": "other",
  "unbsj": "other",
  "union-adventist-university": "other",
  "union-college": "other",
  "university-of-los-angeles-college-of-divinity": "other",
  "university-of-northern-british-columbia": "british-columbia",
  "university-of-pittsburgh-titusville": "other",
  "university-of-puget-sound-christian-college": "other",
  "university-of-saint-katherine": "other",
  "university-of-toronto-at-mississauga": "other",
  "uofa-augustana": "other",
  "valley-forge-christian-college": "other",
  "vanier": "other",
  "viu": "other",
  "volunteer-state-community-college": "other",
  "warner-pacific-college": "other",
  "welch-college": "other",
  "west-coast-baptist-college": "other",
  "west-los-angeles-college": "other",
  "west-valley-jc": "other",
  "westcliff-university": "other",
  "yellowstone-chr": "other",
  "yellowstone-christian-college": "other"
};

const DB_ALIAS_TO_CANONICAL_SCHOOL: Record<string, string> = {
  "abc": "appalachian-bible-college",
  "aflbc": "association-free-lutheran-bible-college",
  "ahunts": "ahuntsic",
  "ahuntsic": "ahuntsic",
  "alb-au": "alb-augustana",
  "alb-augustana": "alb-augustana",
  "alg": "algonquin",
  "algoma university": "algoma-university",
  "algoma-university": "algoma-university",
  "algonquin": "algonquin",
  "ambros": "ambrose",
  "ambrose": "ambrose",
  "andrews university": "andrews-university",
  "andrews-university": "andrews-university",
  "appalachian bible college": "appalachian-bible-college",
  "appalachian-bible-college": "appalachian-bible-college",
  "arlington baptist university": "arlington-baptist-university",
  "arlington-baptist-university": "arlington-baptist-university",
  "association free lutheran bible college": "association-free-lutheran-bible-college",
  "association-free-lutheran-bible-college": "association-free-lutheran-bible-college",
  "au": "andrews-university",
  "baptist bible college, mo": "baptist-bible-college-mo",
  "baptist university of florida": "baptist-university-of-florida",
  "baptist-bible-college-mo": "baptist-bible-college-mo",
  "baptist-university-of-florida": "baptist-university-of-florida",
  "barclay college": "barclay-college",
  "barclay-college": "barclay-college",
  "bbcm": "baptist-bible-college-mo",
  "bc": "boyce-college",
  "bethesda university": "bethesda-university",
  "bethesda-university": "bethesda-university",
  "bju": "bob-jones-university",
  "blc": "blue-lights-college",
  "blue lights college": "blue-lights-college",
  "blue-lights-college": "blue-lights-college",
  "bob jones university": "bob-jones-university",
  "bob-jones-university": "bob-jones-university",
  "boyce college": "boyce-college",
  "boyce-college": "boyce-college",
  "brierc": "briercrest",
  "briercrest": "briercrest",
  "bristol university": "bristol-university",
  "bristol-university": "bristol-university",
  "bu": "bristol-university",
  "buof": "baptist-university-of-florida",
  "california miramar university": "california-miramar-university",
  "california-miramar-university": "california-miramar-university",
  "calvary chapel bible college": "calvary-chapel-bible-college",
  "calvary university": "calvary-university",
  "calvary-chapel-bible-college": "calvary-chapel-bible-college",
  "calvary-university": "calvary-university",
  "cambrian college": "cambrian-college",
  "cambrian-college": "cambrian-college",
  "camosu": "camosun",
  "camosun": "camosun",
  "campbellsville university at harrodsburg": "campbellsville-university-at-harrodsburg",
  "campbellsville-university-at-harrodsburg": "campbellsville-university-at-harrodsburg",
  "canadian mennonite university": "canadian-mennonite-university",
  "canadian-mennonite-university": "canadian-mennonite-university",
  "canado": "canadore",
  "canadore": "canadore",
  "cap": "capilano",
  "capilano": "capilano",
  "carolina christian college": "carolina-christian-college",
  "carolina university": "carolina-university",
  "carolina-christian-college": "carolina-christian-college",
  "carolina-university": "carolina-university",
  "carver bible college": "carver-bible-college",
  "carver-bible-college": "carver-bible-college",
  "cbc": "cbc",
  "cc": "crossroads-college",
  "ccbc": "calvary-chapel-bible-college",
  "ccc": "clearwater-christian-college",
  "cccotb": "central-christian-college-of-the-bible",
  "ccd2": "champlain-college-division-2",
  "cds": "cegep-de-stefoy",
  "ce": "coll-ge-edouard-montpetit",
  "cegep de ste.foy": "cegep-de-stefoy",
  "cegep-de-ste-foy": "cegep-de-stefoy",
  "cegep-de-stefoy": "cegep-de-stefoy",
  "cen": "centennial",
  "centennial": "centennial",
  "central christian college of the bible": "central-christian-college-of-the-bible",
  "central-christian-college-of-the-bible": "central-christian-college-of-the-bible",
  "ch-st-lambert": "ch-st-lambert",
  "ch.-st": "ch-st-lambert",
  "ch.-st-lambert": "ch-st-lambert",
  "champion christian college": "champion-christian-college",
  "champion-christian-college": "champion-christian-college",
  "champlain college division 2": "champlain-college-division-2",
  "champlain-college-division-2": "champlain-college-division-2",
  "chc": "christian-heritage-college",
  "christian heritage college": "christian-heritage-college",
  "christian-heritage-college": "christian-heritage-college",
  "ciu": "columbia-international-university",
  "clearwater christian college": "clearwater-christian-college",
  "clearwater-christian-college": "clearwater-christian-college",
  "clinton college": "clinton-college",
  "clinton-college": "clinton-college",
  "cm": "colege-montmorency",
  "cmu": "canadian-mennonite-university",
  "cobs": "college-of-biblical-studies",
  "colege montmorency": "colege-montmorency",
  "colege-montmorency": "colege-montmorency",
  "coll-ge-edouard-montpetit": "coll-ge-edouard-montpetit",
  "college champlain-st.lambert": "college-champlain-stlambert",
  "college of biblical studies": "college-of-biblical-studies",
  "college of sequoias": "college-of-sequoias",
  "college of the ozarks": "college-of-the-ozarks",
  "college-champlain-st-lambert": "college-champlain-stlambert",
  "college-champlain-stlambert": "college-champlain-stlambert",
  "college-of-biblical-studies": "college-of-biblical-studies",
  "college-of-sequoias": "college-of-sequoias",
  "college-of-the-ozarks": "college-of-the-ozarks",
  "coll\u00e8ge edouard-montpetit": "coll-ge-edouard-montpetit",
  "columbia international university": "columbia-international-university",
  "columbia-international-university": "columbia-international-university",
  "concor": "concordia",
  "concordia": "concordia",
  "conest": "conestoga",
  "conestoga": "conestoga",
  "cos": "college-of-sequoias",
  "coto": "college-of-the-ozarks",
  "cranda": "crandall",
  "crandall": "crandall",
  "crc": "crowleys-ridge-college",
  "crossroads college": "crossroads-college",
  "crossroads-college": "crossroads-college",
  "crowley's ridge college": "crowleys-ridge-college",
  "crowley-s-ridge-college": "crowleys-ridge-college",
  "crowleys-ridge-college": "crowleys-ridge-college",
  "cu": "carolina-university",
  "cuah": "campbellsville-university-at-harrodsburg",
  "dac": "dalhousie-agricultural-campus",
  "dalhou": "dalhousie",
  "dalhousie": "dalhousie",
  "dalhousie agricultural campus": "dalhousie-agricultural-campus",
  "dalhousie-agricultural-campus": "dalhousie-agricultural-campus",
  "dallas christian college": "dallas-christian-college",
  "dallas-christian-college": "dallas-christian-college",
  "dartmouth college": "dartmouth-college",
  "dartmouth-college": "dartmouth-college",
  "daw": "dawson",
  "dawson": "dawson",
  "dayspring bible college": "dayspring-bible-college",
  "dayspring-bible-college": "dayspring-bible-college",
  "dbc": "dayspring-bible-college",
  "dc": "dartmouth-college",
  "dcc": "dallas-christian-college",
  "dougla": "douglas",
  "douglas": "douglas",
  "durham": "durham",
  "ebc": "emmaus-bible-college",
  "ec": "ecclesia-college",
  "ecccc": "el-camino-college-compton-center",
  "ecclesia college": "ecclesia-college",
  "ecclesia-college": "ecclesia-college",
  "edouar": "edouard-montp",
  "edouard-montp": "edouard-montp",
  "edouard-montp.": "edouard-montp",
  "el camino college compton center": "el-camino-college-compton-center",
  "el-camino-college-compton-center": "el-camino-college-compton-center",
  "emmaus bible college": "emmaus-bible-college",
  "emmaus-bible-college": "emmaus-bible-college",
  "faith baptist bible college": "faith-baptist-bible-college",
  "faith-baptist-bible-college": "faith-baptist-bible-college",
  "fan": "fanshawe",
  "fanshawe": "fanshawe",
  "fbbc": "faith-baptist-bible-college",
  "fc": "fullerton-college",
  "flbc": "association-free-lutheran-bible-college",
  "flemin": "fleming",
  "fleming": "fleming",
  "four winds university": "four-winds-university",
  "four-winds-university": "four-winds-university",
  "free lutheran bible college": "association-free-lutheran-bible-college",
  "free-lutheran-bible-college": "association-free-lutheran-bible-college",
  "fullerton college": "fullerton-college",
  "fullerton-college": "fullerton-college",
  "fwu": "four-winds-university",
  "gavilan college": "gavilan-college",
  "gavilan-college": "gavilan-college",
  "gb": "george-brown",
  "gbc": "grace-bible-college",
  "gc": "gavilan-college",
  "gcu": "grace-christian-university",
  "george brown": "george-brown",
  "george-brown": "george-brown",
  "georgi": "georgian",
  "georgian": "georgian",
  "glcc": "great-lakes-christian-college",
  "glcic": "great-lakes-chr-istian-college",
  "gmc": "grant-mcewan-college",
  "gp": "grande-prairie",
  "gprc": "grande-prairie-regional-college",
  "grace bible college": "grace-bible-college",
  "grace christian university": "grace-christian-university",
  "grace university": "grace-christian-university",
  "grace-bible-college": "grace-bible-college",
  "grace-christian-university": "grace-christian-university",
  "grace-university": "grace-christian-university",
  "grande prairie": "grande-prairie",
  "grande prairie regional college": "grande-prairie-regional-college",
  "grande-prairie": "grande-prairie",
  "grande-prairie-regional-college": "grande-prairie-regional-college",
  "grant mcewan college": "grant-mcewan-college",
  "grant-mcewan-college": "grant-mcewan-college",
  "great lakes chr istian college": "great-lakes-chr-istian-college",
  "great lakes christian college": "great-lakes-christian-college",
  "great-lakes-chr-istian-college": "great-lakes-chr-istian-college",
  "great-lakes-christian-college": "great-lakes-christian-college",
  "gu": "grace-christian-university",
  "hb": "hillsdale-baptist",
  "hf": "hillsdale-fbbc",
  "hfbbc": "hillsdale-freewill-baptist-bible-college",
  "hh": "holland-hurricanes",
  "hillsdale baptist": "hillsdale-baptist",
  "hillsdale fbbc": "hillsdale-fbbc",
  "hillsdale freewill baptist bible college": "hillsdale-freewill-baptist-bible-college",
  "hillsdale-baptist": "hillsdale-baptist",
  "hillsdale-fbbc": "hillsdale-fbbc",
  "hillsdale-freewill-baptist-bible-college": "hillsdale-freewill-baptist-bible-college",
  "hol": "holland",
  "holland": "holland",
  "holland hurricanes": "holland-hurricanes",
  "holland-hurricanes": "holland-hurricanes",
  "holy patriot university": "holy-patriot-university",
  "holy-patriot-university": "holy-patriot-university",
  "hpu": "holy-patriot-university",
  "hum": "humber",
  "humber": "humber",
  "ja": "john-abbott",
  "jc": "justice-college",
  "jean-d": "jean-de-breb",
  "jean-de-breb": "jean-de-breb",
  "jean-de-breb.": "jean-de-breb",
  "john abbott": "john-abbott",
  "john-abbott": "john-abbott",
  "johnson university": "johnson-university",
  "johnson university, fl": "johnson-university-fl",
  "johnson university, tn": "johnson-university-tn",
  "johnson, tn": "johnson-tn",
  "johnson-tn": "johnson-tn",
  "johnson-university": "johnson-university",
  "johnson-university-fl": "johnson-university-fl",
  "johnson-university-tn": "johnson-university-tn",
  "jt": "johnson-tn",
  "ju": "justice-university",
  "juf": "johnson-university-fl",
  "justice college": "justice-college",
  "justice university": "justice-university",
  "justice-college": "justice-college",
  "justice-university": "justice-university",
  "jut": "johnson-university-tn",
  "kansas christian college": "kansas-christian-college",
  "kansas-christian-college": "kansas-christian-college",
  "kc": "kuyper-college",
  "kcc": "kansas-christian-college",
  "kcu": "kentucky-christian-university",
  "kentucky christian university": "kentucky-christian-university",
  "kentucky-christian-university": "kentucky-christian-university",
  "keyano": "keyano",
  "king's univ.": "kings-univ",
  "king-s-univ": "kings-univ",
  "kings-univ": "kings-univ",
  "kpu": "kwantlen-polytechnic-university",
  "kuyper college": "kuyper-college",
  "kuyper-college": "kuyper-college",
  "kwantlen polytechnic university": "kwantlen-polytechnic-university",
  "kwantlen-polytechnic-university": "kwantlen-polytechnic-university",
  "la cite": "la-cite",
  "la-cite": "la-cite",
  "lak": "lakeland",
  "lakeland": "lakeland",
  "lambto": "lambton",
  "lambton": "lambton",
  "langar": "langara",
  "langara": "langara",
  "lbc": "long-beach-cc",
  "lc": "la-cite",
  "lethbr": "lethbridge",
  "lethbridge": "lethbridge",
  "life pacific college": "life-pacific-college",
  "life-pacific-college": "life-pacific-college",
  "lincoln university": "lincoln-university",
  "lincoln-university": "lincoln-university",
  "long beach cc": "long-beach-cc",
  "long-beach-cc": "long-beach-cc",
  "loyali": "loyalist",
  "loyalist": "loyalist",
  "lpc": "life-pacific-college",
  "lu": "lincoln-university",
  "ma": "mount-allison",
  "macewa": "macewan",
  "macewan": "macewan",
  "manhattan chr istian college": "manhattan-chr-istian-college",
  "manhattan christian college": "manhattan-christian-college",
  "manhattan-chr-istian-college": "manhattan-chr-istian-college",
  "manhattan-christian-college": "manhattan-christian-college",
  "maryland bible college": "maryland-bible-college",
  "maryland-bible-college": "maryland-bible-college",
  "mbc": "maryland-bible-college",
  "mbi": "moody-bible-institute",
  "mc": "morthland-college",
  "mcc": "mid-continent-college",
  "mcc toronto basket": "mcc-toronto-basket",
  "mcc-toronto-basket": "mcc-toronto-basket",
  "mcic": "manhattan-chr-istian-college",
  "mcu": "mid-atlantic-christian-university",
  "md": "miami-dade",
  "medicine hat": "medicine-hat",
  "medicine-hat": "medicine-hat",
  "mh": "miami-hamilton",
  "miami dade": "miami-dade",
  "miami hamilton": "miami-hamilton",
  "miami university hamilton": "miami-university-hamilton",
  "miami university middletown": "miami-university-middletown",
  "miami-dade": "miami-dade",
  "miami-hamilton": "miami-hamilton",
  "miami-university-hamilton": "miami-university-hamilton",
  "miami-university-middletown": "miami-university-middletown",
  "mid continent college": "mid-continent-college",
  "mid-atlantic christian university": "mid-atlantic-christian-university",
  "mid-atlantic-christian-university": "mid-atlantic-christian-university",
  "mid-continent-college": "mid-continent-college",
  "moh": "mohawk",
  "mohawk": "mohawk",
  "mon": "colege-montmorency",
  "montmorency": "colege-montmorency",
  "moody bible institute": "moody-bible-institute",
  "moody-bible-institute": "moody-bible-institute",
  "morthland college": "morthland-college",
  "morthland-college": "morthland-college",
  "mount allison": "mount-allison",
  "mount-allison": "mount-allison",
  "msvu": "msvu",
  "mtb": "mcc-toronto-basket",
  "mu": "multnomah-university",
  "muh": "miami-university-hamilton",
  "multnomah university": "multnomah-university",
  "multnomah-university": "multnomah-university",
  "mum": "miami-university-middletown",
  "nait": "nait",
  "nau": "north-american-university",
  "ncc": "nebraska-christian-college",
  "ncof": "new-college-of-florida",
  "nebraska christian college": "nebraska-christian-college",
  "nebraska-christian-college": "nebraska-christian-college",
  "nelson university": "nelson-university",
  "nelson-university": "nelson-university",
  "new college of florida": "new-college-of-florida",
  "new hope christian college": "new-hope-christian-college",
  "new hope college": "new-hope-christian-college",
  "new-college-of-florida": "new-college-of-florida",
  "new-hope-christian-college": "new-hope-christian-college",
  "new-hope-college": "new-hope-christian-college",
  "nhc": "new-hope-christian-college",
  "nhcc": "new-hope-christian-college",
  "niagar": "niagara",
  "niagara": "niagara",
  "nic": "northwest-indian-college",
  "nobel university": "nobel-university",
  "nobel-university": "nobel-university",
  "north american university": "north-american-university",
  "north-american-university": "north-american-university",
  "northwest indian college": "northwest-indian-college",
  "northwest-indian-college": "northwest-indian-college",
  "nova scotia agriculture college": "nova-scotia-agriculture-college",
  "nova-scotia-agriculture-college": "nova-scotia-agriculture-college",
  "nsac": "nova-scotia-agriculture-college",
  "nu": "nobel-university",
  "nwp": "nwp",
  "oak hills christian college": "oak-hills-christian-college",
  "oak-hills-christian-college": "oak-hills-christian-college",
  "oakland city university": "oakland-city-university",
  "oakland-city-university": "oakland-city-university",
  "occ": "ozark-christian-college",
  "ocu": "ohio-christian-university",
  "ohcc": "oak-hills-christian-college",
  "ohio christian university": "ohio-christian-university",
  "ohio university chillicothe": "ohio-university-chillicothe",
  "ohio-christian-university": "ohio-christian-university",
  "ohio-university-chillicothe": "ohio-university-chillicothe",
  "okanag": "okanagan",
  "okanagan": "okanagan",
  "olds": "olds",
  "ouc": "ohio-university-chillicothe",
  "outaou": "outaouais",
  "outaouais": "outaouais",
  "ozark christian college": "ozark-christian-college",
  "ozark-christian-college": "ozark-christian-college",
  "paine college": "paine-college",
  "paine-college": "paine-college",
  "paul quinn college": "paul-quinn-college",
  "paul-quinn-college": "paul-quinn-college",
  "pbc": "portland-bible-college",
  "pc": "paine-college",
  "pcc": "pensacola-christian-college",
  "pensacola christian college": "pensacola-christian-college",
  "pensacola-christian-college": "pensacola-christian-college",
  "piedmont international university": "piedmont-international-university",
  "piedmont-international-university": "piedmont-international-university",
  "piu": "piedmont-international-university",
  "portland bible college": "portland-bible-college",
  "portland-bible-college": "portland-bible-college",
  "pqc": "paul-quinn-college",
  "providence university college": "providence-university-college",
  "providence-university-college": "providence-university-college",
  "puc": "providence-university-college",
  "qu": "quest-university",
  "quest university": "quest-university",
  "quest-university": "quest-university",
  "randall university": "randall-university",
  "randall-university": "randall-university",
  "rb/vc": "richmond-bc-vancouver-college",
  "rbc": "rhema-bible-college",
  "rc": "ridley-college",
  "rd": "red-deer",
  "red deer": "red-deer",
  "red river college": "red-river-college",
  "red-deer": "red-deer",
  "red-river-college": "red-river-college",
  "redeem": "redeemer",
  "redeemer": "redeemer",
  "regent university": "regent-university",
  "regent-university": "regent-university",
  "rhema bible college": "rhema-bible-college",
  "rhema-bible-college": "rhema-bible-college",
  "richmond, bc / vancouver college": "richmond-bc-vancouver-college",
  "richmond-bc-vancouver-college": "richmond-bc-vancouver-college",
  "ridley college": "ridley-college",
  "ridley-college": "ridley-college",
  "rrc": "red-river-college",
  "ru": "regent-university",
  "s-alberta-institute-of-tech": "salberta-institute-of-tech",
  "s-alberta-institute-of-technology": "salberta-institute-of-technology",
  "s.alberta institute of tech": "salberta-institute-of-tech",
  "s.alberta institute of technology": "salberta-institute-of-technology",
  "saddleback jc": "saddleback-jc",
  "saddleback-jc": "saddleback-jc",
  "sagu american indian college": "sagu-american-indian-college",
  "sagu-american-indian-college": "sagu-american-indian-college",
  "saic": "sagu-american-indian-college",
  "saint katherine college": "saint-katherine-college",
  "saint-katherine-college": "saint-katherine-college",
  "sainte": "sainte-foy",
  "sainte-foy": "sainte-foy",
  "saiot": "southern-alberta-institute-of-technology",
  "sait": "southern-alberta-instof-tech",
  "salberta-institute-of-tech": "salberta-institute-of-tech",
  "salberta-institute-of-technology": "salberta-institute-of-technology",
  "san jose city college jaguars": "san-jose-city-college-jaguars",
  "san-jose-city-college-jaguars": "san-jose-city-college-jaguars",
  "sault college": "sault-college",
  "sault-college": "sault-college",
  "sb": "se-baptist",
  "sbc": "southeastern-baptist-college",
  "sc": "spurgeon-college",
  "scok": "simmons-college-of-kentucky",
  "se baptist": "se-baptist",
  "se-baptist": "se-baptist",
  "semina": "seminary",
  "seminary": "seminary",
  "sen": "seneca",
  "seneca": "seneca",
  "sherbr": "sherbrooke",
  "sherbrooke": "sherbrooke",
  "sherid": "sheridan",
  "sheridan": "sheridan",
  "simmons college of kentucky": "simmons-college-of-kentucky",
  "simmons-college-of-kentucky": "simmons-college-of-kentucky",
  "siot": "salberta-institute-of-technology",
  "sisseton wahpeton college": "sisseton-wahpeton-college",
  "sisseton-wahpeton-college": "sisseton-wahpeton-college",
  "sj": "saddleback-jc",
  "sjccj": "san-jose-city-college-jaguars",
  "skc": "saint-katherine-college",
  "slcc": "st-louis-christian-college",
  "southeastern baptist college": "southeastern-baptist-college",
  "southeastern-baptist-college": "southeastern-baptist-college",
  "southern alberta inst.of tech": "southern-alberta-instof-tech",
  "southern alberta institute of technology": "southern-alberta-institute-of-technology",
  "southern-alberta-inst-of-tech": "southern-alberta-instof-tech",
  "southern-alberta-institute-of-technology": "southern-alberta-institute-of-technology",
  "southern-alberta-instof-tech": "southern-alberta-instof-tech",
  "spurgeon college": "spurgeon-college",
  "spurgeon-college": "spurgeon-college",
  "st-clair": "stclair",
  "st-lawrence": "stlawrence",
  "st-louis-christian-college": "st-louis-christian-college",
  "st-mary-s-university-college": "stmarys-university-college",
  "st-thomas": "stthomas",
  "st.": "stclair",
  "st. louis christian college": "st-louis-christian-college",
  "st.clair": "stclair",
  "st.law": "stlawrence",
  "st.lawrence": "stlawrence",
  "st.mary's university college": "stmarys-university-college",
  "st.tho": "stthomas",
  "st.thomas": "stthomas",
  "stclair": "stclair",
  "stlawrence": "stlawrence",
  "stmarys-university-college": "stmarys-university-college",
  "stmu": "stmu",
  "stthomas": "stthomas",
  "suc": "stmarys-university-college",
  "swc": "sisseton-wahpeton-college",
  "ta": "team-ahuntsic",
  "tbc": "trinity-bible-college",
  "tcf": "trinity-college-fl",
  "team ahuntsic": "team-ahuntsic",
  "team-ahuntsic": "team-ahuntsic",
  "tennessee temple university": "tennessee-temple-university",
  "tennessee-temple-university": "tennessee-temple-university",
  "tfc": "toccoa-falls-college",
  "the king's": "the-kings",
  "the word of life bible institute": "the-word-of-life-bible-institute",
  "the-king-s": "the-kings",
  "the-kings": "the-kings",
  "the-word-of-life-bible-institute": "the-word-of-life-bible-institute",
  "thetfo": "thetford",
  "thetford": "thetford",
  "tk": "the-kings",
  "toccoa falls college": "toccoa-falls-college",
  "toccoa-falls-college": "toccoa-falls-college",
  "trinity baptist college": "trinity-baptist-college",
  "trinity bible college": "trinity-bible-college",
  "trinity college, fl": "trinity-college-fl",
  "trinity-baptist-college": "trinity-baptist-college",
  "trinity-bible-college": "trinity-bible-college",
  "trinity-college-fl": "trinity-college-fl",
  "ttu": "tennessee-temple-university",
  "twolbi": "the-word-of-life-bible-institute",
  "u of t mississauga": "university-of-toronto-at-mississauga",
  "u-of-t-mississauga": "university-of-toronto-at-mississauga",
  "uau": "union-adventist-university",
  "uc": "union-college",
  "unbsj": "unbsj",
  "union adventist university": "union-adventist-university",
  "union college": "union-college",
  "union-adventist-university": "union-adventist-university",
  "union-college": "union-college",
  "university of los angeles college of divinity": "university-of-los-angeles-college-of-divinity",
  "university of northern british columbia": "university-of-northern-british-columbia",
  "university of pittsburgh-titusville": "university-of-pittsburgh-titusville",
  "university of puget sound christian college": "university-of-puget-sound-christian-college",
  "university of saint katherine": "university-of-saint-katherine",
  "university of toronto at mississauga": "university-of-toronto-at-mississauga",
  "university-of-los-angeles-college-of-divinity": "university-of-los-angeles-college-of-divinity",
  "university-of-northern-british-columbia": "university-of-northern-british-columbia",
  "university-of-pittsburgh-titusville": "university-of-pittsburgh-titusville",
  "university-of-puget-sound-christian-college": "university-of-puget-sound-christian-college",
  "university-of-saint-katherine": "university-of-saint-katherine",
  "university-of-toronto-at-mississauga": "university-of-toronto-at-mississauga",
  "uofa-a": "uofa-augustana",
  "uofa-augustana": "uofa-augustana",
  "uokc": "kings-univ",
  "uolaco": "university-of-los-angeles-college-of-divinity",
  "uonbc": "university-of-northern-british-columbia",
  "uop": "university-of-pittsburgh-titusville",
  "uopscc": "university-of-puget-sound-christian-college",
  "uosk": "university-of-saint-katherine",
  "uotam": "university-of-toronto-at-mississauga",
  "uotm": "university-of-toronto-at-mississauga",
  "valley forge christian college": "valley-forge-christian-college",
  "valley-forge-christian-college": "valley-forge-christian-college",
  "vanier": "vanier",
  "vfcc": "valley-forge-christian-college",
  "viu": "viu",
  "volunteer state community college": "volunteer-state-community-college",
  "volunteer-state-community-college": "volunteer-state-community-college",
  "vscc": "volunteer-state-community-college",
  "warner pacific college": "warner-pacific-college",
  "warner-pacific-college": "warner-pacific-college",
  "wc": "welch-college",
  "wcbc": "west-coast-baptist-college",
  "welch college": "welch-college",
  "welch-college": "welch-college",
  "west coast baptist college": "west-coast-baptist-college",
  "west los angeles college": "west-los-angeles-college",
  "west valley jc": "west-valley-jc",
  "west-coast-baptist-college": "west-coast-baptist-college",
  "west-los-angeles-college": "west-los-angeles-college",
  "west-valley-jc": "west-valley-jc",
  "westcliff university": "westcliff-university",
  "westcliff-university": "westcliff-university",
  "wlac": "west-los-angeles-college",
  "wpc": "warner-pacific-college",
  "wu": "westcliff-university",
  "wvj": "west-valley-jc",
  "yc": "yellowstone-chr",
  "ycc": "yellowstone-christian-college",
  "yellowstone chr.": "yellowstone-chr",
  "yellowstone christian college": "yellowstone-christian-college",
  "yellowstone-chr": "yellowstone-chr",
  "yellowstone-christian-college": "yellowstone-christian-college"
};

const CURRENT_TEAM_SLUGS = new Set<string>([
  "ahuntsic",
  "alb-augustana",
  "algonquin",
  "ambrose",
  "appalachian-bible-college",
  "arlington-baptist-university",
  "baptist-university-of-florida",
  "barclay-college",
  "bethesda-university",
  "bob-jones-university",
  "boyce-college",
  "briercrest",
  "california-miramar-university",
  "calvary-chapel-bible-college",
  "camosun",
  "campbellsville-university-at-harrodsburg",
  "canadian-mennonite-university",
  "canadore",
  "capilano",
  "carolina-christian-college",
  "carolina-university",
  "cbc",
  "centennial",
  "central-christian-college-of-the-bible",
  "ch-st-lambert",
  "champion-christian-college",
  "colege-montmorency",
  "college-champlain-st-lambert",
  "college-of-biblical-studies",
  "concordia",
  "conestoga",
  "crandall",
  "dallas-christian-college",
  "dawson",
  "dayspring-bible-college",
  "douglas",
  "durham",
  "ecclesia-college",
  "edouard-montp",
  "emmaus-bible-college",
  "faith-baptist-bible-college",
  "fanshawe",
  "fleming",
  "four-winds-university",
  "fullerton-college",
  "george-brown",
  "georgian",
  "grace-christian-university",
  "great-lakes-chr-istian-college",
  "great-lakes-christian-college",
  "holland",
  "humber",
  "jean-de-breb",
  "john-abbott",
  "justice-college",
  "justice-university",
  "kansas-christian-college",
  "keyano",
  "king-s-univ",
  "kuyper-college",
  "la-cite",
  "lakeland",
  "lambton",
  "langara",
  "lethbridge",
  "lincoln-university",
  "long-beach-cc",
  "loyalist",
  "manhattan-chr-istian-college",
  "manhattan-christian-college",
  "mcc-toronto-basket",
  "medicine-hat",
  "miami-dade",
  "miami-university-middletown",
  "mohawk",
  "montmorency",
  "moody-bible-institute",
  "mount-allison",
  "msvu",
  "nelson-university",
  "niagara",
  "nobel-university",
  "northwest-indian-college",
  "nwp",
  "oak-hills-christian-college",
  "okanagan",
  "olds",
  "outaouais",
  "ozark-christian-college",
  "paine-college",
  "pensacola-christian-college",
  "portland-bible-college",
  "providence-university-college",
  "randall-university",
  "red-deer",
  "redeemer",
  "regent-university",
  "sainte-foy",
  "sait",
  "seneca",
  "sherbrooke",
  "sheridan",
  "simmons-college-of-kentucky",
  "southeastern-baptist-college",
  "spurgeon-college",
  "st-clair",
  "st-lawrence",
  "st-thomas",
  "stmu",
  "the-king-s",
  "thetford",
  "toccoa-falls-college",
  "trinity-baptist-college",
  "trinity-bible-college",
  "trinity-college-fl",
  "unbsj",
  "union-adventist-university",
  "union-college",
  "vanier",
  "viu",
  "welch-college",
  "west-coast-baptist-college",
  "westcliff-university"
]);

const grouper = createCollegeConferenceGrouper({
  conferences: CONFERENCES,
  canonicalSchoolToConference: CANONICAL_SCHOOL_TO_CONFERENCE,
  dbAliasToCanonicalSchool: DB_ALIAS_TO_CANONICAL_SCHOOL,
  currentTeamSlugs: CURRENT_TEAM_SLUGS,
  requireCurrentTeam: false,
});

export const CCAA_CONFERENCES = CONFERENCES;
export const OTHER_CCAA_CONFERENCE_SLUG = grouper.OTHER_SLUG;
export const conferenceForCcaaTeam = grouper.conferenceForTeam;
export const getCcaaConference = grouper.getConference;
export const groupCcaaTeamsByConference = grouper.groupTeamsByConference;
