/**
 * Official CCAA men's basketball conference grouping.
 * Only the 65 current schools across PACWEST, ACAC, OCAA, RSEQ, ACAA, and MCAC
 * are shown. Leftover usbasket rows stay in the database but are hidden.
 */
import {
  createCollegeConferenceGrouper,
  type CollegeConferenceGroup,
  type CollegeConferenceMeta,
} from "./college-conference-core";

export type CcaaConferenceMeta = CollegeConferenceMeta;
export type CcaaConferenceGroup<T> = CollegeConferenceGroup<T>;

const CONFERENCES: readonly CollegeConferenceMeta[] = [
  {
    slug: "pacwest",
    name: "PACWEST",
    teamSlugs: [
      "camosun",
      "capilano",
      "cbc",
      "douglas",
      "langara",
      "okanagan",
      "viu",
    ],
    teamNames: [
      "Camosun College Chargers",
      "Capilano University Blues",
      "Columbia Bible College Bearcats",
      "Douglas College Royals",
      "Langara College Falcons",
      "Okanagan College Coyotes",
      "Vancouver Island University Mariners",
    ],
    canonicalSchools: [
      "camosun",
      "capilano",
      "cbc",
      "douglas",
      "langara",
      "okanagan",
      "viu",
    ],
  },
  {
    slug: "acac",
    name: "ACAC",
    teamSlugs: [
      "ambrose",
      "uofa-augustana",
      "alb-augustana",
      "briercrest",
      "concordia",
      "keyano",
      "the-king-s",
      "the-kings",
      "lakeland",
      "lethbridge",
      "medicine-hat",
      "nait",
      "nwp",
      "olds",
      "red-deer",
      "sait",
      "stmu",
    ],
    teamNames: [
      "Ambrose University Lions",
      "University of Alberta Augustana Vikings",
      "Briercrest College Clippers",
      "Concordia University of Edmonton Thunder",
      "Keyano College Huskies",
      "The King's University Eagles",
      "Lakeland College Rustlers",
      "Lethbridge Polytechnic Kodiaks",
      "Medicine Hat College Rattlers",
      "Northern Alberta Institute of Technology Ooks",
      "Northwestern Polytechnic Wolves",
      "Olds College Broncos",
      "Red Deer Polytechnic Kings",
      "Southern Alberta Institute of Technology Trojans",
      "St. Mary's University Lightning",
    ],
    canonicalSchools: [
      "ambrose",
      "uofa-augustana",
      "briercrest",
      "concordia",
      "keyano",
      "the-king-s",
      "lakeland",
      "lethbridge",
      "medicine-hat",
      "nait",
      "nwp",
      "olds",
      "red-deer",
      "sait",
      "stmu",
    ],
  },
  {
    slug: "ocaa",
    name: "OCAA",
    teamSlugs: [
      "algonquin",
      "canadore",
      "centennial",
      "conestoga",
      "durham",
      "fanshawe",
      "fleming",
      "george-brown",
      "georgian",
      "humber",
      "la-cite",
      "lambton",
      "loyalist",
      "mohawk",
      "niagara",
      "redeemer",
      "seneca",
      "sheridan",
      "st-clair",
      "st-lawrence",
    ],
    teamNames: [
      "Algonquin College Wolves",
      "Canadore College Panthers",
      "Centennial College Colts",
      "Conestoga College Condors",
      "Durham College Lords",
      "Fanshawe College Falcons",
      "Fleming College Phoenix",
      "George Brown College Huskies",
      "Georgian College Grizzlies",
      "Humber College Hawks",
      "Collège La Cité Coyotes",
      "Lambton College Lions",
      "Loyalist College Lancers",
      "Mohawk College Mountaineers",
      "Niagara College Knights",
      "Redeemer University Royals",
      "Seneca Polytechnic Sting",
      "Sheridan College Bruins",
      "St. Clair College Saints",
      "St. Lawrence College Surge",
    ],
    canonicalSchools: [
      "algonquin",
      "canadore",
      "centennial",
      "conestoga",
      "durham",
      "fanshawe",
      "fleming",
      "george-brown",
      "georgian",
      "humber",
      "la-cite",
      "lambton",
      "loyalist",
      "mohawk",
      "niagara",
      "redeemer",
      "seneca",
      "sheridan",
      "st-clair",
      "st-lawrence",
    ],
  },
  {
    slug: "rseq",
    name: "RSEQ",
    teamSlugs: [
      "ahuntsic",
      "ch-st-lambert",
      "dawson",
      "edouard-montp",
      "jean-de-breb",
      "john-abbott",
      "montmorency",
      "outaouais",
      "sainte-foy",
      "sherbrooke",
      "thetford",
      "vanier",
    ],
    teamNames: [
      "Collège Ahuntsic Aigles",
      "Champlain College Saint-Lambert Cavaliers",
      "Dawson College Blues",
      "Cégep Édouard-Montpetit Lynx",
      "Collège Jean-de-Brébeuf Dynamiques",
      "John Abbott College Islanders",
      "Collège Montmorency Nomades",
      "Cégep de l'Outaouais Griffons",
      "Cégep de Sainte-Foy Dynamiques",
      "Cégep de Sherbrooke Volontaires",
      "Cégep de Thetford Filons",
      "Vanier College Cheetahs",
    ],
    canonicalSchools: [
      "ahuntsic",
      "ch-st-lambert",
      "dawson",
      "edouard-montp",
      "jean-de-breb",
      "john-abbott",
      "montmorency",
      "outaouais",
      "sainte-foy",
      "sherbrooke",
      "thetford",
      "vanier",
    ],
  },
  {
    slug: "acaa",
    name: "ACAA",
    teamSlugs: [
      "crandall",
      "holland",
      "mount-allison",
      "msvu",
      "st-thomas",
      "university-of-kings-college",
      "unbsj",
    ],
    teamNames: [
      "Crandall University Chargers",
      "Holland College Hurricanes",
      "Mount Allison University Mounties",
      "Mount Saint Vincent University Mystics",
      "St. Thomas University Tommies",
      "University of King's College Blue Devils",
      "University of New Brunswick Saint John Seawolves",
    ],
    canonicalSchools: [
      "crandall",
      "holland",
      "mount-allison",
      "msvu",
      "st-thomas",
      "university-of-kings-college",
      "unbsj",
    ],
  },
  {
    slug: "mcac",
    name: "MCAC",
    teamSlugs: [
      "canadian-mennonite-university",
      "providence-university-college",
      "red-river-college",
      "saint-boniface",
    ],
    teamNames: [
      "Canadian Mennonite University Blazers",
      "Providence University College Pilots",
      "Red River College Polytechnic Rebels",
      "Université de Saint-Boniface Les Rouges",
    ],
    canonicalSchools: [
      "canadian-mennonite-university",
      "providence-university-college",
      "red-river-college",
      "saint-boniface",
    ],
  },
] as const;

const CANONICAL_SCHOOL_TO_CONFERENCE: Record<string, string> = {
  camosun: "pacwest",
  capilano: "pacwest",
  cbc: "pacwest",
  douglas: "pacwest",
  langara: "pacwest",
  okanagan: "pacwest",
  viu: "pacwest",
  ambrose: "acac",
  "uofa-augustana": "acac",
  "alb-augustana": "acac",
  briercrest: "acac",
  concordia: "acac",
  keyano: "acac",
  "the-king-s": "acac",
  lakeland: "acac",
  lethbridge: "acac",
  "medicine-hat": "acac",
  nait: "acac",
  nwp: "acac",
  olds: "acac",
  "red-deer": "acac",
  sait: "acac",
  stmu: "acac",
  algonquin: "ocaa",
  canadore: "ocaa",
  centennial: "ocaa",
  conestoga: "ocaa",
  durham: "ocaa",
  fanshawe: "ocaa",
  fleming: "ocaa",
  "george-brown": "ocaa",
  georgian: "ocaa",
  humber: "ocaa",
  "la-cite": "ocaa",
  lambton: "ocaa",
  loyalist: "ocaa",
  mohawk: "ocaa",
  niagara: "ocaa",
  redeemer: "ocaa",
  seneca: "ocaa",
  sheridan: "ocaa",
  "st-clair": "ocaa",
  "st-lawrence": "ocaa",
  ahuntsic: "rseq",
  "ch-st-lambert": "rseq",
  dawson: "rseq",
  "edouard-montp": "rseq",
  "jean-de-breb": "rseq",
  "john-abbott": "rseq",
  montmorency: "rseq",
  outaouais: "rseq",
  "sainte-foy": "rseq",
  sherbrooke: "rseq",
  thetford: "rseq",
  vanier: "rseq",
  crandall: "acaa",
  holland: "acaa",
  "mount-allison": "acaa",
  msvu: "acaa",
  "st-thomas": "acaa",
  "university-of-kings-college": "acaa",
  unbsj: "acaa",
  "canadian-mennonite-university": "mcac",
  "providence-university-college": "mcac",
  "red-river-college": "mcac",
  "saint-boniface": "mcac",
};

const DB_ALIAS_TO_CANONICAL_SCHOOL: Record<string, string> = {
  ...Object.fromEntries(Object.keys(CANONICAL_SCHOOL_TO_CONFERENCE).map((slug) => [slug, slug])),
  "ambrose-university": "ambrose",
  "briercrest-college": "briercrest",
  "concordia-university-of-edmonton": "concordia",
  "concordia-edmonton": "concordia",
  "lethbridge-college": "lethbridge",
  "lethbridge-polytechnic": "lethbridge",
  "northern-alberta-institute-of-technology": "nait",
  "southern-alberta-institute-of-technology": "sait",
  "southern-alberta-instof-tech": "sait",
  "s-alberta-institute-of-technology": "sait",
  "grande-prairie": "nwp",
  "grande-prairie-regional-college": "nwp",
  "northwestern-polytechnic": "nwp",
  "red-deer-college": "red-deer",
  "red-deer-polytechnic": "red-deer",
  "the-kings-university": "the-king-s",
  "the-kings": "the-king-s",
  "university-of-alberta-augustana": "uofa-augustana",
  "alb-augustana": "uofa-augustana",
  georgebrown: "george-brown",
  lacite: "la-cite",
  "humber-college": "humber",
  "seneca-college": "seneca",
  stclair: "st-clair",
  stlawrence: "st-lawrence",
  "college-champlain-st-lambert": "ch-st-lambert",
  "ch.-st-lambert": "ch-st-lambert",
  "team-ahuntsic": "ahuntsic",
  "colege-montmorency": "montmorency",
  "cegep-de-ste-foy": "sainte-foy",
  "cegep-de-sherbrooke": "sherbrooke",
  mountallison: "mount-allison",
  mountsaintvincent: "msvu",
  stthomas: "st-thomas",
  "kings-college": "university-of-kings-college",
  ukc: "university-of-kings-college",
  "unb-saint-john": "unbsj",
  cmu: "canadian-mennonite-university",
  puc: "providence-university-college",
  rrc: "red-river-college",
  "rrc-polytech": "red-river-college",
  "st-boniface": "saint-boniface",
  stboniface: "saint-boniface",
};

const CURRENT_TEAM_SLUGS = new Set(
  CONFERENCES.flatMap((conference) => [...(conference.canonicalSchools ?? [])]),
);

const grouper = createCollegeConferenceGrouper({
  conferences: CONFERENCES,
  canonicalSchoolToConference: CANONICAL_SCHOOL_TO_CONFERENCE,
  dbAliasToCanonicalSchool: DB_ALIAS_TO_CANONICAL_SCHOOL,
  currentTeamSlugs: CURRENT_TEAM_SLUGS,
  requireCurrentTeam: true,
});

const CCAA_DISPLAY_BY_SLUG: Record<string, string> = {};
for (const conference of CONFERENCES) {
  for (const [index, slug] of (conference.canonicalSchools ?? []).entries()) {
    const name = conference.teamNames[index];
    if (slug && name) CCAA_DISPLAY_BY_SLUG[slug] = name;
  }
}
for (const [alias, canonical] of Object.entries(DB_ALIAS_TO_CANONICAL_SCHOOL)) {
  const name = CCAA_DISPLAY_BY_SLUG[canonical];
  if (name) CCAA_DISPLAY_BY_SLUG[alias] = name;
}

export function resolveCcaaTeamDisplayName(slug?: string | null, fallback?: string | null): string | null {
  const key = slug?.trim().toLowerCase() ?? "";
  return CCAA_DISPLAY_BY_SLUG[key] ?? fallback?.trim() ?? null;
}

export const CCAA_CONFERENCES = CONFERENCES;
export const OTHER_CCAA_CONFERENCE_SLUG = grouper.OTHER_SLUG;
export const conferenceForCcaaTeam = grouper.conferenceForTeam;
export const getCcaaConference = grouper.getConference;
export function groupCcaaTeamsByConference<T extends { name: string; abbreviation: string; slug: string }>(
  teams: T[],
) {
  return grouper.groupTeamsByConference(teams).filter(
    (group) => group.conference.slug !== OTHER_CCAA_CONFERENCE_SLUG,
  );
}
