const FLAG_CDN = "https://purecatamphetamine.github.io/country-flag-icons/3x2";

const COUNTRY_ISO: Record<string, string> = {
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  us: "US",
  america: "US",
  canada: "CA",
  mexico: "MX",
  "puerto rico": "PR",
  "dominican republic": "DO",
  "the bahamas": "BS",
  bahamas: "BS",
  jamaica: "JM",
  haiti: "HT",
  cuba: "CU",
  "trinidad and tobago": "TT",
  "us virgin islands": "VI",
  "u s virgin islands": "VI",
  "virgin islands": "VI",
  "united states virgin islands": "VI",
  panama: "PA",
  "costa rica": "CR",
  honduras: "HN",
  guatemala: "GT",
  nicaragua: "NI",
  "el salvador": "SV",
  belize: "BZ",
  "antigua and barbuda": "AG",
  barbados: "BB",
  grenada: "GD",
  dominica: "DM",
  "saint lucia": "LC",
  "st lucia": "LC",

  brazil: "BR",
  argentina: "AR",
  venezuela: "VE",
  colombia: "CO",
  chile: "CL",
  uruguay: "UY",
  peru: "PE",
  ecuador: "EC",
  bolivia: "BO",
  paraguay: "PY",
  guyana: "GY",
  suriname: "SR",

  greece: "GR",
  france: "FR",
  spain: "ES",
  germany: "DE",
  italy: "IT",
  serbia: "RS",
  croatia: "HR",
  lithuania: "LT",
  latvia: "LV",
  estonia: "EE",
  slovenia: "SI",
  montenegro: "ME",
  "bosnia and herzegovina": "BA",
  bosnia: "BA",
  "north macedonia": "MK",
  macedonia: "MK",
  albania: "AL",
  kosovo: "XK",
  turkey: "TR",
  turkiye: "TR",
  poland: "PL",
  "czech republic": "CZ",
  czechia: "CZ",
  slovakia: "SK",
  hungary: "HU",
  romania: "RO",
  bulgaria: "BG",
  ukraine: "UA",
  russia: "RU",
  georgia: "GE",
  armenia: "AM",
  azerbaijan: "AZ",
  belarus: "BY",
  moldova: "MD",
  "united kingdom": "GB",
  uk: "GB",
  "great britain": "GB",
  britain: "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  "northern ireland": "GB",
  ireland: "IE",
  netherlands: "NL",
  holland: "NL",
  belgium: "BE",
  sweden: "SE",
  finland: "FI",
  norway: "NO",
  denmark: "DK",
  switzerland: "CH",
  austria: "AT",
  portugal: "PT",
  iceland: "IS",
  luxembourg: "LU",
  monaco: "MC",
  andorra: "AD",
  cyprus: "CY",
  malta: "MT",

  nigeria: "NG",
  cameroon: "CM",
  senegal: "SN",
  "south sudan": "SS",
  sudan: "SD",
  egypt: "EG",
  tunisia: "TN",
  morocco: "MA",
  algeria: "DZ",
  mali: "ML",
  "ivory coast": "CI",
  "cote divoire": "CI",
  "cote d ivoire": "CI",
  angola: "AO",
  ghana: "GH",
  kenya: "KE",
  "south africa": "ZA",
  ethiopia: "ET",
  guinea: "GN",
  "cape verde": "CV",
  "cabo verde": "CV",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  "drc": "CD",
  congo: "CG",
  "republic of the congo": "CG",
  gabon: "GA",
  "burkina faso": "BF",
  togo: "TG",
  benin: "BJ",
  rwanda: "RW",
  uganda: "UG",
  tanzania: "TZ",
  mozambique: "MZ",
  madagascar: "MG",
  "sierra leone": "SL",
  liberia: "LR",
  "central african republic": "CF",
  chad: "TD",
  niger: "NE",
  mauritania: "MR",
  gambia: "GM",
  "the gambia": "GM",
  "equatorial guinea": "GQ",
  namibia: "NA",
  botswana: "BW",
  zimbabwe: "ZW",
  zambia: "ZM",
  malawi: "MW",

  australia: "AU",
  "new zealand": "NZ",
  china: "CN",
  japan: "JP",
  "south korea": "KR",
  korea: "KR",
  "republic of korea": "KR",
  "korea south": "KR",
  taiwan: "TW",
  philippines: "PH",
  india: "IN",
  israel: "IL",
  lebanon: "LB",
  jordan: "JO",
  iran: "IR",
  iraq: "IQ",
  "saudi arabia": "SA",
  "united arab emirates": "AE",
  uae: "AE",
  qatar: "QA",
  kuwait: "KW",
  bahrain: "BH",
  syria: "SY",
  "new caledonia": "NC",
  fiji: "FJ",
  samoa: "WS",
  tonga: "TO",
  guam: "GU",
  indonesia: "ID",
  thailand: "TH",
  vietnam: "VN",
  malaysia: "MY",
  singapore: "SG",
  mongolia: "MN",
  kazakhstan: "KZ",
  uzbekistan: "UZ",
  pakistan: "PK",
  bangladesh: "BD",
  "sri lanka": "LK",
  nepal: "NP",
};

function normalizeCountry(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/['’.]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function countryToIsoCode(country: string | null | undefined): string | null {
  const raw = country?.trim();
  if (!raw) return null;

  const normalized = normalizeCountry(raw);
  if (!normalized) return null;

  const mapped = COUNTRY_ISO[normalized];
  if (mapped) return mapped;

  if (/^[a-z]{2}$/.test(normalized)) {
    return normalized.toUpperCase();
  }

  return null;
}

export function countryFlagUrl(country: string | null | undefined): string | null {
  const iso = countryToIsoCode(country);
  return iso ? `${FLAG_CDN}/${iso}.svg` : null;
}
