// Auto-generated from ESPN men's college basketball conference groups.
// Regenerate with: python3 scripts/generate-ncaa-conferences.py
// Generated: 2026-06-19

export interface NcaaConferenceMeta {
  slug: string;
  name: string;
  teamSlugs: readonly string[];
  teamNames: readonly string[];
  teamAbbrevs: readonly string[];
}

export const NCAA_M_CONFERENCES: readonly NcaaConferenceMeta[] = [
  {
    slug: "america-east-conference",
    name: "America East Conference",
    teamSlugs: [
    "Binghamton",
    "Binghamton Bearcats",
    "Bryant",
    "Bryant Bulldogs",
    "Maine",
    "Maine Black Bears",
    "NJIT",
    "NJIT Highlanders",
    "New Hampshire",
    "New Hampshire Wildcats",
    "UAlbany",
    "UAlbany Great Danes",
    "UMBC",
    "UMBC Retrievers",
    "UMass Lowell",
    "UMass Lowell River Hawks",
    "Vermont",
    "Vermont Catamounts",
    "binghamton",
    "binghamton-bearcats",
    "bryant",
    "bryant-bulldogs",
    "maine",
    "maine-black",
    "maine-black-bears",
    "new-hampshire",
    "new-hampshire-wildcats",
    "njit",
    "njit-highlanders",
    "ualbany",
    "ualbany-great",
    "ualbany-great-danes",
    "umass-lowell",
    "umass-lowell-river",
    "umass-lowell-river-hawks",
    "umbc",
    "umbc-retrievers",
    "vermont",
    "vermont-catamounts",
  ],
    teamNames: [
    "Binghamton",
    "Binghamton Bearcats",
    "Bryant",
    "Bryant Bulldogs",
    "Maine",
    "Maine Black Bears",
    "NJIT",
    "NJIT Highlanders",
    "New Hampshire",
    "New Hampshire Wildcats",
    "UAlbany",
    "UAlbany Great Danes",
    "UMBC",
    "UMBC Retrievers",
    "UMass Lowell",
    "UMass Lowell River Hawks",
    "Vermont",
    "Vermont Catamounts",
    "binghamton",
    "binghamton-bearcats",
    "bryant",
    "bryant-bulldogs",
    "maine",
    "maine-black-bears",
    "new-hampshire",
    "new-hampshire-wildcats",
    "njit",
    "njit-highlanders",
    "ualbany",
    "ualbany-great-danes",
    "umass-lowell",
    "umass-lowell-river-hawks",
    "umbc",
    "umbc-retrievers",
    "vermont",
    "vermont-catamounts",
  ],
    teamAbbrevs: [
    "BING",
    "BRY",
    "ME",
    "NJIT",
    "UALB",
    "UMBC",
    "UML",
    "UNH",
    "UVM",
  ],
  },
  {
    slug: "american-conference",
    name: "American Conference",
    teamSlugs: [
    "Charlotte",
    "Charlotte 49ers",
    "East Carolina",
    "East Carolina Pirates",
    "FAU",
    "Florida Atlantic Owls",
    "Memphis",
    "Memphis Tigers",
    "North Texas",
    "North Texas Mean Green",
    "Rice",
    "Rice Owls",
    "South Florida",
    "South Florida Bulls",
    "Temple",
    "Temple Owls",
    "Tulane",
    "Tulane Green Wave",
    "Tulsa",
    "Tulsa Golden Hurricane",
    "UAB",
    "UAB Blazers",
    "UTSA",
    "UTSA Roadrunners",
    "Wichita St",
    "Wichita State Shockers",
    "charlotte",
    "charlotte-49ers",
    "east-carolina",
    "east-carolina-pirates",
    "fau",
    "florida-atlantic",
    "florida-atlantic-owls",
    "memphis",
    "memphis-tigers",
    "north-texas",
    "north-texas-mean",
    "north-texas-mean-green",
    "rice",
    "rice-owls",
    "south-florida",
    "south-florida-bulls",
    "temple",
    "temple-owls",
    "tulane",
    "tulane-green",
    "tulane-green-wave",
    "tulsa",
    "tulsa-golden",
    "tulsa-golden-hurricane",
    "uab",
    "uab-blazers",
    "utsa",
    "utsa-roadrunners",
    "wichita-st",
    "wichita-state",
    "wichita-state-shockers",
  ],
    teamNames: [
    "Charlotte",
    "Charlotte 49ers",
    "East Carolina",
    "East Carolina Pirates",
    "FAU",
    "Florida Atlantic Owls",
    "Memphis",
    "Memphis Tigers",
    "North Texas",
    "North Texas Mean Green",
    "Rice",
    "Rice Owls",
    "South Florida",
    "South Florida Bulls",
    "Temple",
    "Temple Owls",
    "Tulane",
    "Tulane Green Wave",
    "Tulsa",
    "Tulsa Golden Hurricane",
    "UAB",
    "UAB Blazers",
    "UTSA",
    "UTSA Roadrunners",
    "Wichita St",
    "Wichita State Shockers",
    "charlotte",
    "charlotte-49ers",
    "east-carolina",
    "east-carolina-pirates",
    "fau",
    "florida-atlantic-owls",
    "memphis",
    "memphis-tigers",
    "north-texas",
    "north-texas-mean-green",
    "rice",
    "rice-owls",
    "south-florida",
    "south-florida-bulls",
    "temple",
    "temple-owls",
    "tulane",
    "tulane-green-wave",
    "tulsa",
    "tulsa-golden-hurricane",
    "uab",
    "uab-blazers",
    "utsa",
    "utsa-roadrunners",
    "wichita-st",
    "wichita-state-shockers",
  ],
    teamAbbrevs: [
    "CLT",
    "ECU",
    "FAU",
    "MEM",
    "RICE",
    "TEM",
    "TLSA",
    "TULN",
    "UAB",
    "UNT",
    "USF",
    "UTSA",
    "WICH",
  ],
  },
  {
    slug: "atlantic-10-conference",
    name: "Atlantic 10 Conference",
    teamSlugs: [
    "Davidson",
    "Davidson Wildcats",
    "Dayton",
    "Dayton Flyers",
    "Duquesne",
    "Duquesne Dukes",
    "Fordham",
    "Fordham Rams",
    "G Washington",
    "George Mason",
    "George Mason Patriots",
    "George Washington Revolutionaries",
    "La Salle",
    "La Salle Explorers",
    "Loyola Chicago",
    "Loyola Chicago Ramblers",
    "Rhode Island",
    "Rhode Island Rams",
    "Richmond",
    "Richmond Spiders",
    "Saint Joseph's",
    "Saint Joseph's Hawks",
    "Saint Louis",
    "Saint Louis Billikens",
    "St Bonaventure",
    "St. Bonaventure Bonnies",
    "VCU",
    "VCU Rams",
    "davidson",
    "davidson-wildcats",
    "dayton",
    "dayton-flyers",
    "duquesne",
    "duquesne-dukes",
    "fordham",
    "fordham-rams",
    "g-washington",
    "george-mason",
    "george-mason-patriots",
    "george-washington",
    "george-washington-revolutionaries",
    "la-salle",
    "la-salle-explorers",
    "loyola-chicago",
    "loyola-chicago-ramblers",
    "rhode-island",
    "rhode-island-rams",
    "richmond",
    "richmond-spiders",
    "saint-josephs",
    "saint-josephs-hawks",
    "saint-louis",
    "saint-louis-billikens",
    "st-bonaventure",
    "st-bonaventure-bonnies",
    "vcu",
    "vcu-rams",
  ],
    teamNames: [
    "Davidson",
    "Davidson Wildcats",
    "Dayton",
    "Dayton Flyers",
    "Duquesne",
    "Duquesne Dukes",
    "Fordham",
    "Fordham Rams",
    "G Washington",
    "George Mason",
    "George Mason Patriots",
    "George Washington Revolutionaries",
    "La Salle",
    "La Salle Explorers",
    "Loyola Chicago",
    "Loyola Chicago Ramblers",
    "Rhode Island",
    "Rhode Island Rams",
    "Richmond",
    "Richmond Spiders",
    "Saint Joseph's",
    "Saint Joseph's Hawks",
    "Saint Louis",
    "Saint Louis Billikens",
    "St Bonaventure",
    "St. Bonaventure Bonnies",
    "VCU",
    "VCU Rams",
    "davidson",
    "davidson-wildcats",
    "dayton",
    "dayton-flyers",
    "duquesne",
    "duquesne-dukes",
    "fordham",
    "fordham-rams",
    "g-washington",
    "george-mason",
    "george-mason-patriots",
    "george-washington-revolutionaries",
    "la-salle",
    "la-salle-explorers",
    "loyola-chicago",
    "loyola-chicago-ramblers",
    "rhode-island",
    "rhode-island-rams",
    "richmond",
    "richmond-spiders",
    "saint-josephs",
    "saint-josephs-hawks",
    "saint-louis",
    "saint-louis-billikens",
    "st-bonaventure",
    "st-bonaventure-bonnies",
    "vcu",
    "vcu-rams",
  ],
    teamAbbrevs: [
    "DAV",
    "DAY",
    "DUQ",
    "FOR",
    "GMU",
    "GW",
    "JOES",
    "LAS",
    "LUC",
    "RICH",
    "SBU",
    "SLU",
    "URI",
    "VCU",
  ],
  },
  {
    slug: "atlantic-coast-conference",
    name: "Atlantic Coast Conference",
    teamSlugs: [
    "Boston College",
    "Boston College Eagles",
    "California",
    "California Golden Bears",
    "Clemson",
    "Clemson Tigers",
    "Duke",
    "Duke Blue Devils",
    "Florida St",
    "Florida State Seminoles",
    "Georgia Tech",
    "Georgia Tech Yellow Jackets",
    "Louisville",
    "Louisville Cardinals",
    "Miami",
    "Miami Hurricanes",
    "NC State",
    "NC State Wolfpack",
    "North Carolina",
    "North Carolina Tar Heels",
    "Notre Dame",
    "Notre Dame Fighting Irish",
    "Pitt",
    "Pittsburgh Panthers",
    "SMU",
    "SMU Mustangs",
    "Stanford",
    "Stanford Cardinal",
    "Syracuse",
    "Syracuse Orange",
    "Virginia",
    "Virginia Cavaliers",
    "Virginia Tech",
    "Virginia Tech Hokies",
    "Wake Forest",
    "Wake Forest Demon Deacons",
    "boston-college",
    "boston-college-eagles",
    "california",
    "california-golden",
    "california-golden-bears",
    "clemson",
    "clemson-tigers",
    "duke",
    "duke-blue",
    "duke-blue-devils",
    "florida-st",
    "florida-state",
    "florida-state-seminoles",
    "georgia-tech",
    "georgia-tech-yellow",
    "georgia-tech-yellow-jackets",
    "louisville",
    "louisville-cardinals",
    "miami",
    "miami-hurricanes",
    "nc-state",
    "nc-state-wolfpack",
    "north-carolina",
    "north-carolina-tar",
    "north-carolina-tar-heels",
    "notre-dame",
    "notre-dame-fighting",
    "notre-dame-fighting-irish",
    "pitt",
    "pittsburgh",
    "pittsburgh-panthers",
    "smu",
    "smu-mustangs",
    "stanford",
    "stanford-cardinal",
    "syracuse",
    "syracuse-orange",
    "virginia",
    "virginia-cavaliers",
    "virginia-tech",
    "virginia-tech-hokies",
    "wake-forest",
    "wake-forest-demon",
    "wake-forest-demon-deacons",
  ],
    teamNames: [
    "Boston College",
    "Boston College Eagles",
    "California",
    "California Golden Bears",
    "Clemson",
    "Clemson Tigers",
    "Duke",
    "Duke Blue Devils",
    "Florida St",
    "Florida State Seminoles",
    "Georgia Tech",
    "Georgia Tech Yellow Jackets",
    "Louisville",
    "Louisville Cardinals",
    "Miami",
    "Miami Hurricanes",
    "NC State",
    "NC State Wolfpack",
    "North Carolina",
    "North Carolina Tar Heels",
    "Notre Dame",
    "Notre Dame Fighting Irish",
    "Pitt",
    "Pittsburgh Panthers",
    "SMU",
    "SMU Mustangs",
    "Stanford",
    "Stanford Cardinal",
    "Syracuse",
    "Syracuse Orange",
    "Virginia",
    "Virginia Cavaliers",
    "Virginia Tech",
    "Virginia Tech Hokies",
    "Wake Forest",
    "Wake Forest Demon Deacons",
    "boston-college",
    "boston-college-eagles",
    "california",
    "california-golden-bears",
    "clemson",
    "clemson-tigers",
    "duke",
    "duke-blue-devils",
    "florida-st",
    "florida-state-seminoles",
    "georgia-tech",
    "georgia-tech-yellow-jackets",
    "louisville",
    "louisville-cardinals",
    "miami",
    "miami-hurricanes",
    "nc-state",
    "nc-state-wolfpack",
    "north-carolina",
    "north-carolina-tar-heels",
    "notre-dame",
    "notre-dame-fighting-irish",
    "pitt",
    "pittsburgh-panthers",
    "smu",
    "smu-mustangs",
    "stanford",
    "stanford-cardinal",
    "syracuse",
    "syracuse-orange",
    "virginia",
    "virginia-cavaliers",
    "virginia-tech",
    "virginia-tech-hokies",
    "wake-forest",
    "wake-forest-demon-deacons",
  ],
    teamAbbrevs: [
    "BC",
    "CAL",
    "CLEM",
    "DUKE",
    "FSU",
    "GT",
    "LOU",
    "MIA",
    "NCSU",
    "ND",
    "PITT",
    "SMU",
    "STAN",
    "SYR",
    "UNC",
    "UVA",
    "VT",
    "WAKE",
  ],
  },
  {
    slug: "atlantic-sun-conference",
    name: "Atlantic Sun Conference",
    teamSlugs: [
    "Austin Peay",
    "Austin Peay Governors",
    "Bellarmine",
    "Bellarmine Knights",
    "C Arkansas",
    "Central Arkansas Bears",
    "E Kentucky",
    "Eastern Kentucky Colonels",
    "FGCU",
    "Florida Gulf Coast Eagles",
    "Jacksonville",
    "Jacksonville Dolphins",
    "Lipscomb",
    "Lipscomb Bisons",
    "North Alabama",
    "North Alabama Lions",
    "North Florida",
    "North Florida Ospreys",
    "Queens",
    "Queens University Royals",
    "Stetson",
    "Stetson Hatters",
    "West Georgia",
    "West Georgia Wolves",
    "austin-peay",
    "austin-peay-governors",
    "bellarmine",
    "bellarmine-knights",
    "c-arkansas",
    "central-arkansas",
    "central-arkansas-bears",
    "e-kentucky",
    "eastern-kentucky",
    "eastern-kentucky-colonels",
    "fgcu",
    "florida-gulf-coast",
    "florida-gulf-coast-eagles",
    "jacksonville",
    "jacksonville-dolphins",
    "lipscomb",
    "lipscomb-bisons",
    "north-alabama",
    "north-alabama-lions",
    "north-florida",
    "north-florida-ospreys",
    "queens",
    "queens-university",
    "queens-university-royals",
    "stetson",
    "stetson-hatters",
    "west-georgia",
    "west-georgia-wolves",
  ],
    teamNames: [
    "Austin Peay",
    "Austin Peay Governors",
    "Bellarmine",
    "Bellarmine Knights",
    "C Arkansas",
    "Central Arkansas Bears",
    "E Kentucky",
    "Eastern Kentucky Colonels",
    "FGCU",
    "Florida Gulf Coast Eagles",
    "Jacksonville",
    "Jacksonville Dolphins",
    "Lipscomb",
    "Lipscomb Bisons",
    "North Alabama",
    "North Alabama Lions",
    "North Florida",
    "North Florida Ospreys",
    "Queens",
    "Queens University Royals",
    "Stetson",
    "Stetson Hatters",
    "West Georgia",
    "West Georgia Wolves",
    "austin-peay",
    "austin-peay-governors",
    "bellarmine",
    "bellarmine-knights",
    "c-arkansas",
    "central-arkansas-bears",
    "e-kentucky",
    "eastern-kentucky-colonels",
    "fgcu",
    "florida-gulf-coast-eagles",
    "jacksonville",
    "jacksonville-dolphins",
    "lipscomb",
    "lipscomb-bisons",
    "north-alabama",
    "north-alabama-lions",
    "north-florida",
    "north-florida-ospreys",
    "queens",
    "queens-university-royals",
    "stetson",
    "stetson-hatters",
    "west-georgia",
    "west-georgia-wolves",
  ],
    teamAbbrevs: [
    "APSU",
    "BELL",
    "CARK",
    "EKU",
    "FGCU",
    "JAX",
    "LIP",
    "QUC",
    "STET",
    "UNA",
    "UNF",
    "WGA",
  ],
  },
  {
    slug: "big-12-conference",
    name: "Big 12 Conference",
    teamSlugs: [
    "Arizona",
    "Arizona St",
    "Arizona State Sun Devils",
    "Arizona Wildcats",
    "BYU",
    "BYU Cougars",
    "Baylor",
    "Baylor Bears",
    "Cincinnati",
    "Cincinnati Bearcats",
    "Colorado",
    "Colorado Buffaloes",
    "Houston",
    "Houston Cougars",
    "Iowa State",
    "Iowa State Cyclones",
    "Kansas",
    "Kansas Jayhawks",
    "Kansas St",
    "Kansas State Wildcats",
    "Oklahoma St",
    "Oklahoma State Cowboys",
    "TCU",
    "TCU Horned Frogs",
    "Texas Tech",
    "Texas Tech Red Raiders",
    "UCF",
    "UCF Knights",
    "Utah",
    "Utah Utes",
    "West Virginia",
    "West Virginia Mountaineers",
    "arizona",
    "arizona-st",
    "arizona-state-sun",
    "arizona-state-sun-devils",
    "arizona-wildcats",
    "baylor",
    "baylor-bears",
    "byu",
    "byu-cougars",
    "cincinnati",
    "cincinnati-bearcats",
    "colorado",
    "colorado-buffaloes",
    "houston",
    "houston-cougars",
    "iowa-state",
    "iowa-state-cyclones",
    "kansas",
    "kansas-jayhawks",
    "kansas-st",
    "kansas-state",
    "kansas-state-wildcats",
    "oklahoma-st",
    "oklahoma-state",
    "oklahoma-state-cowboys",
    "tcu",
    "tcu-horned",
    "tcu-horned-frogs",
    "texas-tech",
    "texas-tech-red",
    "texas-tech-red-raiders",
    "ucf",
    "ucf-knights",
    "utah",
    "utah-utes",
    "west-virginia",
    "west-virginia-mountaineers",
  ],
    teamNames: [
    "Arizona",
    "Arizona St",
    "Arizona State Sun Devils",
    "Arizona Wildcats",
    "BYU",
    "BYU Cougars",
    "Baylor",
    "Baylor Bears",
    "Cincinnati",
    "Cincinnati Bearcats",
    "Colorado",
    "Colorado Buffaloes",
    "Houston",
    "Houston Cougars",
    "Iowa State",
    "Iowa State Cyclones",
    "Kansas",
    "Kansas Jayhawks",
    "Kansas St",
    "Kansas State Wildcats",
    "Oklahoma St",
    "Oklahoma State Cowboys",
    "TCU",
    "TCU Horned Frogs",
    "Texas Tech",
    "Texas Tech Red Raiders",
    "UCF",
    "UCF Knights",
    "Utah",
    "Utah Utes",
    "West Virginia",
    "West Virginia Mountaineers",
    "arizona",
    "arizona-st",
    "arizona-state-sun-devils",
    "arizona-wildcats",
    "baylor",
    "baylor-bears",
    "byu",
    "byu-cougars",
    "cincinnati",
    "cincinnati-bearcats",
    "colorado",
    "colorado-buffaloes",
    "houston",
    "houston-cougars",
    "iowa-state",
    "iowa-state-cyclones",
    "kansas",
    "kansas-jayhawks",
    "kansas-st",
    "kansas-state-wildcats",
    "oklahoma-st",
    "oklahoma-state-cowboys",
    "tcu",
    "tcu-horned-frogs",
    "texas-tech",
    "texas-tech-red-raiders",
    "ucf",
    "ucf-knights",
    "utah",
    "utah-utes",
    "west-virginia",
    "west-virginia-mountaineers",
  ],
    teamAbbrevs: [
    "ARIZ",
    "ASU",
    "BAY",
    "BYU",
    "CIN",
    "COLO",
    "HOU",
    "ISU",
    "KSU",
    "KU",
    "OKST",
    "TCU",
    "TTU",
    "UCF",
    "UTAH",
    "WVU",
  ],
  },
  {
    slug: "big-east-conference",
    name: "Big East Conference",
    teamSlugs: [
    "Butler",
    "Butler Bulldogs",
    "Creighton",
    "Creighton Bluejays",
    "DePaul",
    "DePaul Blue Demons",
    "Georgetown",
    "Georgetown Hoyas",
    "Marquette",
    "Marquette Golden Eagles",
    "Providence",
    "Providence Friars",
    "Seton Hall",
    "Seton Hall Pirates",
    "St John's",
    "St. John's Red Storm",
    "UConn",
    "UConn Huskies",
    "Villanova",
    "Villanova Wildcats",
    "Xavier",
    "Xavier Musketeers",
    "butler",
    "butler-bulldogs",
    "creighton",
    "creighton-bluejays",
    "depaul",
    "depaul-blue",
    "depaul-blue-demons",
    "georgetown",
    "georgetown-hoyas",
    "marquette",
    "marquette-golden",
    "marquette-golden-eagles",
    "providence",
    "providence-friars",
    "seton-hall",
    "seton-hall-pirates",
    "st-johns",
    "st-johns-red",
    "st-johns-red-storm",
    "uconn",
    "uconn-huskies",
    "villanova",
    "villanova-wildcats",
    "xavier",
    "xavier-musketeers",
  ],
    teamNames: [
    "Butler",
    "Butler Bulldogs",
    "Creighton",
    "Creighton Bluejays",
    "DePaul",
    "DePaul Blue Demons",
    "Georgetown",
    "Georgetown Hoyas",
    "Marquette",
    "Marquette Golden Eagles",
    "Providence",
    "Providence Friars",
    "Seton Hall",
    "Seton Hall Pirates",
    "St John's",
    "St. John's Red Storm",
    "UConn",
    "UConn Huskies",
    "Villanova",
    "Villanova Wildcats",
    "Xavier",
    "Xavier Musketeers",
    "butler",
    "butler-bulldogs",
    "creighton",
    "creighton-bluejays",
    "depaul",
    "depaul-blue-demons",
    "georgetown",
    "georgetown-hoyas",
    "marquette",
    "marquette-golden-eagles",
    "providence",
    "providence-friars",
    "seton-hall",
    "seton-hall-pirates",
    "st-johns",
    "st-johns-red-storm",
    "uconn",
    "uconn-huskies",
    "villanova",
    "villanova-wildcats",
    "xavier",
    "xavier-musketeers",
  ],
    teamAbbrevs: [
    "BUT",
    "CONN",
    "CREI",
    "DEP",
    "GTWN",
    "HALL",
    "MARQ",
    "PROV",
    "SJU",
    "VILL",
    "XAV",
  ],
  },
  {
    slug: "big-sky-conference",
    name: "Big Sky Conference",
    teamSlugs: [
    "E Washington",
    "Eastern Washington Eagles",
    "Idaho",
    "Idaho St",
    "Idaho State Bengals",
    "Idaho Vandals",
    "Montana",
    "Montana Grizzlies",
    "Montana St",
    "Montana State Bobcats",
    "N Arizona",
    "N Colorado",
    "Northern Arizona Lumberjacks",
    "Northern Colorado Bears",
    "Portland St",
    "Portland State Vikings",
    "Sacramento St",
    "Sacramento State Hornets",
    "Weber St",
    "Weber State Wildcats",
    "e-washington",
    "eastern-washington",
    "eastern-washington-eagles",
    "idaho",
    "idaho-st",
    "idaho-state",
    "idaho-state-bengals",
    "idaho-vandals",
    "montana",
    "montana-grizzlies",
    "montana-st",
    "montana-state",
    "montana-state-bobcats",
    "n-arizona",
    "n-colorado",
    "northern-arizona",
    "northern-arizona-lumberjacks",
    "northern-colorado",
    "northern-colorado-bears",
    "portland-st",
    "portland-state",
    "portland-state-vikings",
    "sacramento-st",
    "sacramento-state",
    "sacramento-state-hornets",
    "weber-st",
    "weber-state",
    "weber-state-wildcats",
  ],
    teamNames: [
    "E Washington",
    "Eastern Washington Eagles",
    "Idaho",
    "Idaho St",
    "Idaho State Bengals",
    "Idaho Vandals",
    "Montana",
    "Montana Grizzlies",
    "Montana St",
    "Montana State Bobcats",
    "N Arizona",
    "N Colorado",
    "Northern Arizona Lumberjacks",
    "Northern Colorado Bears",
    "Portland St",
    "Portland State Vikings",
    "Sacramento St",
    "Sacramento State Hornets",
    "Weber St",
    "Weber State Wildcats",
    "e-washington",
    "eastern-washington-eagles",
    "idaho",
    "idaho-st",
    "idaho-state-bengals",
    "idaho-vandals",
    "montana",
    "montana-grizzlies",
    "montana-st",
    "montana-state-bobcats",
    "n-arizona",
    "n-colorado",
    "northern-arizona-lumberjacks",
    "northern-colorado-bears",
    "portland-st",
    "portland-state-vikings",
    "sacramento-st",
    "sacramento-state-hornets",
    "weber-st",
    "weber-state-wildcats",
  ],
    teamAbbrevs: [
    "EWU",
    "IDHO",
    "IDST",
    "MONT",
    "MTST",
    "NAU",
    "PRST",
    "SAC",
    "UNCO",
    "WEB",
  ],
  },
  {
    slug: "big-south-conference",
    name: "Big South Conference",
    teamSlugs: [
    "Charleston So",
    "Charleston Southern Buccaneers",
    "Gardner-Webb",
    "Gardner-Webb Runnin' Bulldogs",
    "High Point",
    "High Point Panthers",
    "Longwood",
    "Longwood Lancers",
    "Presbyterian",
    "Presbyterian Blue Hose",
    "Radford",
    "Radford Highlanders",
    "SC Upstate",
    "South Carolina Upstate Spartans",
    "UNC Asheville",
    "UNC Asheville Bulldogs",
    "Winthrop",
    "Winthrop Eagles",
    "charleston-so",
    "charleston-southern",
    "charleston-southern-buccaneers",
    "gardner-webb",
    "gardner-webb-runnin",
    "gardner-webb-runnin-bulldogs",
    "high-point",
    "high-point-panthers",
    "longwood",
    "longwood-lancers",
    "presbyterian",
    "presbyterian-blue",
    "presbyterian-blue-hose",
    "radford",
    "radford-highlanders",
    "sc-upstate",
    "south-carolina-upstate",
    "south-carolina-upstate-spartans",
    "unc-asheville",
    "unc-asheville-bulldogs",
    "winthrop",
    "winthrop-eagles",
  ],
    teamNames: [
    "Charleston So",
    "Charleston Southern Buccaneers",
    "Gardner-Webb",
    "Gardner-Webb Runnin' Bulldogs",
    "High Point",
    "High Point Panthers",
    "Longwood",
    "Longwood Lancers",
    "Presbyterian",
    "Presbyterian Blue Hose",
    "Radford",
    "Radford Highlanders",
    "SC Upstate",
    "South Carolina Upstate Spartans",
    "UNC Asheville",
    "UNC Asheville Bulldogs",
    "Winthrop",
    "Winthrop Eagles",
    "charleston-so",
    "charleston-southern-buccaneers",
    "gardner-webb",
    "gardner-webb-runnin-bulldogs",
    "high-point",
    "high-point-panthers",
    "longwood",
    "longwood-lancers",
    "presbyterian",
    "presbyterian-blue-hose",
    "radford",
    "radford-highlanders",
    "sc-upstate",
    "south-carolina-upstate-spartans",
    "unc-asheville",
    "unc-asheville-bulldogs",
    "winthrop",
    "winthrop-eagles",
  ],
    teamAbbrevs: [
    "CHSO",
    "GWEB",
    "HPU",
    "LONG",
    "PRES",
    "RAD",
    "UNCA",
    "UPST",
    "WIN",
  ],
  },
  {
    slug: "big-ten-conference",
    name: "Big Ten Conference",
    teamSlugs: [
    "Illinois",
    "Illinois Fighting Illini",
    "Indiana",
    "Indiana Hoosiers",
    "Iowa",
    "Iowa Hawkeyes",
    "Maryland",
    "Maryland Terrapins",
    "Michigan",
    "Michigan St",
    "Michigan State Spartans",
    "Michigan Wolverines",
    "Minnesota",
    "Minnesota Golden Gophers",
    "Nebraska",
    "Nebraska Cornhuskers",
    "Northwestern",
    "Northwestern Wildcats",
    "Ohio State",
    "Ohio State Buckeyes",
    "Oregon",
    "Oregon Ducks",
    "Penn State",
    "Penn State Nittany Lions",
    "Purdue",
    "Purdue Boilermakers",
    "Rutgers",
    "Rutgers Scarlet Knights",
    "UCLA",
    "UCLA Bruins",
    "USC",
    "USC Trojans",
    "Washington",
    "Washington Huskies",
    "Wisconsin",
    "Wisconsin Badgers",
    "illinois",
    "illinois-fighting",
    "illinois-fighting-illini",
    "indiana",
    "indiana-hoosiers",
    "iowa",
    "iowa-hawkeyes",
    "maryland",
    "maryland-terrapins",
    "michigan",
    "michigan-st",
    "michigan-state",
    "michigan-state-spartans",
    "michigan-wolverines",
    "minnesota",
    "minnesota-golden",
    "minnesota-golden-gophers",
    "nebraska",
    "nebraska-cornhuskers",
    "northwestern",
    "northwestern-wildcats",
    "ohio-state",
    "ohio-state-buckeyes",
    "oregon",
    "oregon-ducks",
    "penn-state",
    "penn-state-nittany",
    "penn-state-nittany-lions",
    "purdue",
    "purdue-boilermakers",
    "rutgers",
    "rutgers-scarlet",
    "rutgers-scarlet-knights",
    "ucla",
    "ucla-bruins",
    "usc",
    "usc-trojans",
    "washington",
    "washington-huskies",
    "wisconsin",
    "wisconsin-badgers",
  ],
    teamNames: [
    "Illinois",
    "Illinois Fighting Illini",
    "Indiana",
    "Indiana Hoosiers",
    "Iowa",
    "Iowa Hawkeyes",
    "Maryland",
    "Maryland Terrapins",
    "Michigan",
    "Michigan St",
    "Michigan State Spartans",
    "Michigan Wolverines",
    "Minnesota",
    "Minnesota Golden Gophers",
    "Nebraska",
    "Nebraska Cornhuskers",
    "Northwestern",
    "Northwestern Wildcats",
    "Ohio State",
    "Ohio State Buckeyes",
    "Oregon",
    "Oregon Ducks",
    "Penn State",
    "Penn State Nittany Lions",
    "Purdue",
    "Purdue Boilermakers",
    "Rutgers",
    "Rutgers Scarlet Knights",
    "UCLA",
    "UCLA Bruins",
    "USC",
    "USC Trojans",
    "Washington",
    "Washington Huskies",
    "Wisconsin",
    "Wisconsin Badgers",
    "illinois",
    "illinois-fighting-illini",
    "indiana",
    "indiana-hoosiers",
    "iowa",
    "iowa-hawkeyes",
    "maryland",
    "maryland-terrapins",
    "michigan",
    "michigan-st",
    "michigan-state-spartans",
    "michigan-wolverines",
    "minnesota",
    "minnesota-golden-gophers",
    "nebraska",
    "nebraska-cornhuskers",
    "northwestern",
    "northwestern-wildcats",
    "ohio-state",
    "ohio-state-buckeyes",
    "oregon",
    "oregon-ducks",
    "penn-state",
    "penn-state-nittany-lions",
    "purdue",
    "purdue-boilermakers",
    "rutgers",
    "rutgers-scarlet-knights",
    "ucla",
    "ucla-bruins",
    "usc",
    "usc-trojans",
    "washington",
    "washington-huskies",
    "wisconsin",
    "wisconsin-badgers",
  ],
    teamAbbrevs: [
    "ILL",
    "IOWA",
    "IU",
    "MD",
    "MICH",
    "MINN",
    "MSU",
    "NEB",
    "NU",
    "ORE",
    "OSU",
    "PSU",
    "PUR",
    "RUTG",
    "UCLA",
    "USC",
    "WASH",
    "WIS",
  ],
  },
  {
    slug: "big-west-conference",
    name: "Big West Conference",
    teamSlugs: [
    "Bakersfield",
    "CSU Northridge",
    "Cal Poly",
    "Cal Poly Mustangs",
    "Cal State Bakersfield Roadrunners",
    "Cal State Fullerton Titans",
    "Cal State Northridge Matadors",
    "Fullerton",
    "Hawai'i",
    "Hawai'i Rainbow Warriors",
    "Long Beach St",
    "Long Beach State Beach",
    "Santa Barbara",
    "UC Davis",
    "UC Davis Aggies",
    "UC Irvine",
    "UC Irvine Anteaters",
    "UC Riverside",
    "UC Riverside Highlanders",
    "UC San Diego",
    "UC San Diego Tritons",
    "UC Santa Barbara Gauchos",
    "bakersfield",
    "cal-poly",
    "cal-poly-mustangs",
    "cal-state-bakersfield",
    "cal-state-bakersfield-roadrunners",
    "cal-state-fullerton",
    "cal-state-fullerton-titans",
    "cal-state-northridge",
    "cal-state-northridge-matadors",
    "csu-northridge",
    "fullerton",
    "hawaii",
    "hawaii-rainbow",
    "hawaii-rainbow-warriors",
    "long-beach-st",
    "long-beach-state",
    "long-beach-state-beach",
    "santa-barbara",
    "uc-davis",
    "uc-davis-aggies",
    "uc-irvine",
    "uc-irvine-anteaters",
    "uc-riverside",
    "uc-riverside-highlanders",
    "uc-san-diego",
    "uc-san-diego-tritons",
    "uc-santa-barbara",
    "uc-santa-barbara-gauchos",
  ],
    teamNames: [
    "Bakersfield",
    "CSU Northridge",
    "Cal Poly",
    "Cal Poly Mustangs",
    "Cal State Bakersfield Roadrunners",
    "Cal State Fullerton Titans",
    "Cal State Northridge Matadors",
    "Fullerton",
    "Hawai'i",
    "Hawai'i Rainbow Warriors",
    "Long Beach St",
    "Long Beach State Beach",
    "Santa Barbara",
    "UC Davis",
    "UC Davis Aggies",
    "UC Irvine",
    "UC Irvine Anteaters",
    "UC Riverside",
    "UC Riverside Highlanders",
    "UC San Diego",
    "UC San Diego Tritons",
    "UC Santa Barbara Gauchos",
    "bakersfield",
    "cal-poly",
    "cal-poly-mustangs",
    "cal-state-bakersfield-roadrunners",
    "cal-state-fullerton-titans",
    "cal-state-northridge-matadors",
    "csu-northridge",
    "fullerton",
    "hawaii",
    "hawaii-rainbow-warriors",
    "long-beach-st",
    "long-beach-state-beach",
    "santa-barbara",
    "uc-davis",
    "uc-davis-aggies",
    "uc-irvine",
    "uc-irvine-anteaters",
    "uc-riverside",
    "uc-riverside-highlanders",
    "uc-san-diego",
    "uc-san-diego-tritons",
    "uc-santa-barbara-gauchos",
  ],
    teamAbbrevs: [
    "CP",
    "CSUB",
    "CSUF",
    "CSUN",
    "HAW",
    "LBSU",
    "UCD",
    "UCI",
    "UCR",
    "UCSB",
    "UCSD",
  ],
  },
  {
    slug: "coastal-athletic-association",
    name: "Coastal Athletic Association",
    teamSlugs: [
    "Campbell",
    "Campbell Fighting Camels",
    "Charleston",
    "Charleston Cougars",
    "Drexel",
    "Drexel Dragons",
    "Elon",
    "Elon Phoenix",
    "Hampton",
    "Hampton Pirates",
    "Hofstra",
    "Hofstra Pride",
    "Monmouth",
    "Monmouth Hawks",
    "NC A&T",
    "North Carolina A&T Aggies",
    "Northeastern",
    "Northeastern Huskies",
    "Stony Brook",
    "Stony Brook Seawolves",
    "Towson",
    "Towson Tigers",
    "UNC Wilmington",
    "UNC Wilmington Seahawks",
    "William & Mary",
    "William & Mary Tribe",
    "campbell",
    "campbell-fighting",
    "campbell-fighting-camels",
    "charleston",
    "charleston-cougars",
    "drexel",
    "drexel-dragons",
    "elon",
    "elon-phoenix",
    "hampton",
    "hampton-pirates",
    "hofstra",
    "hofstra-pride",
    "monmouth",
    "monmouth-hawks",
    "nc-a-t",
    "north-carolina-a-t-aggies",
    "north-carolina-at",
    "north-carolina-at-aggies",
    "northeastern",
    "northeastern-huskies",
    "stony-brook",
    "stony-brook-seawolves",
    "towson",
    "towson-tigers",
    "unc-wilmington",
    "unc-wilmington-seahawks",
    "william-mary",
    "william-mary-tribe",
  ],
    teamNames: [
    "Campbell",
    "Campbell Fighting Camels",
    "Charleston",
    "Charleston Cougars",
    "Drexel",
    "Drexel Dragons",
    "Elon",
    "Elon Phoenix",
    "Hampton",
    "Hampton Pirates",
    "Hofstra",
    "Hofstra Pride",
    "Monmouth",
    "Monmouth Hawks",
    "NC A&T",
    "North Carolina A&T Aggies",
    "Northeastern",
    "Northeastern Huskies",
    "Stony Brook",
    "Stony Brook Seawolves",
    "Towson",
    "Towson Tigers",
    "UNC Wilmington",
    "UNC Wilmington Seahawks",
    "William & Mary",
    "William & Mary Tribe",
    "campbell",
    "campbell-fighting-camels",
    "charleston",
    "charleston-cougars",
    "drexel",
    "drexel-dragons",
    "elon",
    "elon-phoenix",
    "hampton",
    "hampton-pirates",
    "hofstra",
    "hofstra-pride",
    "monmouth",
    "monmouth-hawks",
    "nc-a-t",
    "north-carolina-a-t-aggies",
    "northeastern",
    "northeastern-huskies",
    "stony-brook",
    "stony-brook-seawolves",
    "towson",
    "towson-tigers",
    "unc-wilmington",
    "unc-wilmington-seahawks",
    "william-mary",
    "william-mary-tribe",
  ],
    teamAbbrevs: [
    "CAM",
    "COFC",
    "DREX",
    "ELON",
    "HAMP",
    "HOF",
    "MONM",
    "NCAT",
    "NE",
    "STBK",
    "TOW",
    "UNCW",
    "W&M",
  ],
  },
  {
    slug: "college-basketball-crown",
    name: "College Basketball Crown",
    teamSlugs: [
    "Baylor",
    "Baylor Bears",
    "Colorado",
    "Colorado Buffaloes",
    "Creighton",
    "Creighton Bluejays",
    "Minnesota",
    "Minnesota Golden Gophers",
    "Oklahoma",
    "Oklahoma Sooners",
    "Rutgers",
    "Rutgers Scarlet Knights",
    "Stanford",
    "Stanford Cardinal",
    "West Virginia",
    "West Virginia Mountaineers",
    "baylor",
    "baylor-bears",
    "colorado",
    "colorado-buffaloes",
    "creighton",
    "creighton-bluejays",
    "minnesota",
    "minnesota-golden",
    "minnesota-golden-gophers",
    "oklahoma",
    "oklahoma-sooners",
    "rutgers",
    "rutgers-scarlet",
    "rutgers-scarlet-knights",
    "stanford",
    "stanford-cardinal",
    "west-virginia",
    "west-virginia-mountaineers",
  ],
    teamNames: [
    "Baylor",
    "Baylor Bears",
    "Colorado",
    "Colorado Buffaloes",
    "Creighton",
    "Creighton Bluejays",
    "Minnesota",
    "Minnesota Golden Gophers",
    "Oklahoma",
    "Oklahoma Sooners",
    "Rutgers",
    "Rutgers Scarlet Knights",
    "Stanford",
    "Stanford Cardinal",
    "West Virginia",
    "West Virginia Mountaineers",
    "baylor",
    "baylor-bears",
    "colorado",
    "colorado-buffaloes",
    "creighton",
    "creighton-bluejays",
    "minnesota",
    "minnesota-golden-gophers",
    "oklahoma",
    "oklahoma-sooners",
    "rutgers",
    "rutgers-scarlet-knights",
    "stanford",
    "stanford-cardinal",
    "west-virginia",
    "west-virginia-mountaineers",
  ],
    teamAbbrevs: [
    "BAY",
    "COLO",
    "CREI",
    "MINN",
    "OU",
    "RUTG",
    "STAN",
    "WVU",
  ],
  },
  {
    slug: "conference-usa",
    name: "Conference USA",
    teamSlugs: [
    "Delaware",
    "Delaware Blue Hens",
    "FIU",
    "Florida International Panthers",
    "Jacksonville State Gamecocks",
    "Jax State",
    "Kennesaw St",
    "Kennesaw State Owls",
    "Liberty",
    "Liberty Flames",
    "Louisiana Tech",
    "Louisiana Tech Bulldogs",
    "MTSU",
    "Middle Tennessee Blue Raiders",
    "Missouri St",
    "Missouri State Bears",
    "New Mexico St",
    "New Mexico State Aggies",
    "Sam Houston",
    "Sam Houston Bearkats",
    "UTEP",
    "UTEP Miners",
    "Western KY",
    "Western Kentucky Hilltoppers",
    "delaware",
    "delaware-blue",
    "delaware-blue-hens",
    "fiu",
    "florida-international",
    "florida-international-panthers",
    "jacksonville-state",
    "jacksonville-state-gamecocks",
    "jax-state",
    "kennesaw-st",
    "kennesaw-state",
    "kennesaw-state-owls",
    "liberty",
    "liberty-flames",
    "louisiana-tech",
    "louisiana-tech-bulldogs",
    "middle-tennessee-blue",
    "middle-tennessee-blue-raiders",
    "missouri-st",
    "missouri-state",
    "missouri-state-bears",
    "mtsu",
    "new-mexico-st",
    "new-mexico-state",
    "new-mexico-state-aggies",
    "sam-houston",
    "sam-houston-bearkats",
    "utep",
    "utep-miners",
    "western-kentucky",
    "western-kentucky-hilltoppers",
    "western-ky",
  ],
    teamNames: [
    "Delaware",
    "Delaware Blue Hens",
    "FIU",
    "Florida International Panthers",
    "Jacksonville State Gamecocks",
    "Jax State",
    "Kennesaw St",
    "Kennesaw State Owls",
    "Liberty",
    "Liberty Flames",
    "Louisiana Tech",
    "Louisiana Tech Bulldogs",
    "MTSU",
    "Middle Tennessee Blue Raiders",
    "Missouri St",
    "Missouri State Bears",
    "New Mexico St",
    "New Mexico State Aggies",
    "Sam Houston",
    "Sam Houston Bearkats",
    "UTEP",
    "UTEP Miners",
    "Western KY",
    "Western Kentucky Hilltoppers",
    "delaware",
    "delaware-blue-hens",
    "fiu",
    "florida-international-panthers",
    "jacksonville-state-gamecocks",
    "jax-state",
    "kennesaw-st",
    "kennesaw-state-owls",
    "liberty",
    "liberty-flames",
    "louisiana-tech",
    "louisiana-tech-bulldogs",
    "middle-tennessee-blue-raiders",
    "missouri-st",
    "missouri-state-bears",
    "mtsu",
    "new-mexico-st",
    "new-mexico-state-aggies",
    "sam-houston",
    "sam-houston-bearkats",
    "utep",
    "utep-miners",
    "western-kentucky-hilltoppers",
    "western-ky",
  ],
    teamAbbrevs: [
    "DEL",
    "FIU",
    "JXST",
    "KENN",
    "LIB",
    "LT",
    "MOST",
    "MTSU",
    "NMSU",
    "SHSU",
    "UTEP",
    "WKU",
  ],
  },
  {
    slug: "horizon-league",
    name: "Horizon League",
    teamSlugs: [
    "Cleveland St",
    "Cleveland State Vikings",
    "Detroit Mercy",
    "Detroit Mercy Titans",
    "Green Bay",
    "Green Bay Phoenix",
    "IU Indianapolis Jaguars",
    "IU Indy",
    "Milwaukee",
    "Milwaukee Panthers",
    "N Kentucky",
    "Northern Kentucky Norse",
    "Oakland",
    "Oakland Golden Grizzlies",
    "Purdue FW",
    "Purdue Fort Wayne Mastodons",
    "Robert Morris",
    "Robert Morris Colonials",
    "Wright St",
    "Wright State Raiders",
    "Youngstown St",
    "Youngstown State Penguins",
    "cleveland-st",
    "cleveland-state",
    "cleveland-state-vikings",
    "detroit-mercy",
    "detroit-mercy-titans",
    "green-bay",
    "green-bay-phoenix",
    "iu-indianapolis",
    "iu-indianapolis-jaguars",
    "iu-indy",
    "milwaukee",
    "milwaukee-panthers",
    "n-kentucky",
    "northern-kentucky",
    "northern-kentucky-norse",
    "oakland",
    "oakland-golden",
    "oakland-golden-grizzlies",
    "purdue-fort-wayne",
    "purdue-fort-wayne-mastodons",
    "purdue-fw",
    "robert-morris",
    "robert-morris-colonials",
    "wright-st",
    "wright-state",
    "wright-state-raiders",
    "youngstown-st",
    "youngstown-state",
    "youngstown-state-penguins",
  ],
    teamNames: [
    "Cleveland St",
    "Cleveland State Vikings",
    "Detroit Mercy",
    "Detroit Mercy Titans",
    "Green Bay",
    "Green Bay Phoenix",
    "IU Indianapolis Jaguars",
    "IU Indy",
    "Milwaukee",
    "Milwaukee Panthers",
    "N Kentucky",
    "Northern Kentucky Norse",
    "Oakland",
    "Oakland Golden Grizzlies",
    "Purdue FW",
    "Purdue Fort Wayne Mastodons",
    "Robert Morris",
    "Robert Morris Colonials",
    "Wright St",
    "Wright State Raiders",
    "Youngstown St",
    "Youngstown State Penguins",
    "cleveland-st",
    "cleveland-state-vikings",
    "detroit-mercy",
    "detroit-mercy-titans",
    "green-bay",
    "green-bay-phoenix",
    "iu-indianapolis-jaguars",
    "iu-indy",
    "milwaukee",
    "milwaukee-panthers",
    "n-kentucky",
    "northern-kentucky-norse",
    "oakland",
    "oakland-golden-grizzlies",
    "purdue-fort-wayne-mastodons",
    "purdue-fw",
    "robert-morris",
    "robert-morris-colonials",
    "wright-st",
    "wright-state-raiders",
    "youngstown-st",
    "youngstown-state-penguins",
  ],
    teamAbbrevs: [
    "CLE",
    "DETM",
    "GB",
    "IUIN",
    "MILW",
    "NKU",
    "OAK",
    "PFW",
    "RMU",
    "WRST",
    "YSU",
  ],
  },
  {
    slug: "ivy-league",
    name: "Ivy League",
    teamSlugs: [
    "Brown",
    "Brown Bears",
    "Columbia",
    "Columbia Lions",
    "Cornell",
    "Cornell Big Red",
    "Dartmouth",
    "Dartmouth Big Green",
    "Harvard",
    "Harvard Crimson",
    "Penn",
    "Pennsylvania Quakers",
    "Princeton",
    "Princeton Tigers",
    "Yale",
    "Yale Bulldogs",
    "brown",
    "brown-bears",
    "columbia",
    "columbia-lions",
    "cornell",
    "cornell-big",
    "cornell-big-red",
    "dartmouth",
    "dartmouth-big",
    "dartmouth-big-green",
    "harvard",
    "harvard-crimson",
    "penn",
    "pennsylvania",
    "pennsylvania-quakers",
    "princeton",
    "princeton-tigers",
    "yale",
    "yale-bulldogs",
  ],
    teamNames: [
    "Brown",
    "Brown Bears",
    "Columbia",
    "Columbia Lions",
    "Cornell",
    "Cornell Big Red",
    "Dartmouth",
    "Dartmouth Big Green",
    "Harvard",
    "Harvard Crimson",
    "Penn",
    "Pennsylvania Quakers",
    "Princeton",
    "Princeton Tigers",
    "Yale",
    "Yale Bulldogs",
    "brown",
    "brown-bears",
    "columbia",
    "columbia-lions",
    "cornell",
    "cornell-big-red",
    "dartmouth",
    "dartmouth-big-green",
    "harvard",
    "harvard-crimson",
    "penn",
    "pennsylvania-quakers",
    "princeton",
    "princeton-tigers",
    "yale",
    "yale-bulldogs",
  ],
    teamAbbrevs: [
    "BRWN",
    "COLU",
    "COR",
    "DART",
    "HARV",
    "PENN",
    "PRIN",
    "YALE",
  ],
  },
  {
    slug: "metro-atlantic-athletic-conference",
    name: "Metro Atlantic Athletic Conference",
    teamSlugs: [
    "Canisius",
    "Canisius Golden Griffins",
    "Fairfield",
    "Fairfield Stags",
    "Iona",
    "Iona Gaels",
    "Manhattan",
    "Manhattan Jaspers",
    "Marist",
    "Marist Red Foxes",
    "Merrimack",
    "Merrimack Warriors",
    "Mount St Marys",
    "Mount St. Mary's Mountaineers",
    "Niagara",
    "Niagara Purple Eagles",
    "Quinnipiac",
    "Quinnipiac Bobcats",
    "Rider",
    "Rider Broncs",
    "Sacred Heart",
    "Sacred Heart Pioneers",
    "Saint Peter's",
    "Saint Peter's Peacocks",
    "Siena",
    "Siena Saints",
    "canisius",
    "canisius-golden",
    "canisius-golden-griffins",
    "fairfield",
    "fairfield-stags",
    "iona",
    "iona-gaels",
    "manhattan",
    "manhattan-jaspers",
    "marist",
    "marist-red",
    "marist-red-foxes",
    "merrimack",
    "merrimack-warriors",
    "mount-st-marys",
    "mount-st-marys-mountaineers",
    "niagara",
    "niagara-purple",
    "niagara-purple-eagles",
    "quinnipiac",
    "quinnipiac-bobcats",
    "rider",
    "rider-broncs",
    "sacred-heart",
    "sacred-heart-pioneers",
    "saint-peters",
    "saint-peters-peacocks",
    "siena",
    "siena-saints",
  ],
    teamNames: [
    "Canisius",
    "Canisius Golden Griffins",
    "Fairfield",
    "Fairfield Stags",
    "Iona",
    "Iona Gaels",
    "Manhattan",
    "Manhattan Jaspers",
    "Marist",
    "Marist Red Foxes",
    "Merrimack",
    "Merrimack Warriors",
    "Mount St Marys",
    "Mount St. Mary's Mountaineers",
    "Niagara",
    "Niagara Purple Eagles",
    "Quinnipiac",
    "Quinnipiac Bobcats",
    "Rider",
    "Rider Broncs",
    "Sacred Heart",
    "Sacred Heart Pioneers",
    "Saint Peter's",
    "Saint Peter's Peacocks",
    "Siena",
    "Siena Saints",
    "canisius",
    "canisius-golden-griffins",
    "fairfield",
    "fairfield-stags",
    "iona",
    "iona-gaels",
    "manhattan",
    "manhattan-jaspers",
    "marist",
    "marist-red-foxes",
    "merrimack",
    "merrimack-warriors",
    "mount-st-marys",
    "mount-st-marys-mountaineers",
    "niagara",
    "niagara-purple-eagles",
    "quinnipiac",
    "quinnipiac-bobcats",
    "rider",
    "rider-broncs",
    "sacred-heart",
    "sacred-heart-pioneers",
    "saint-peters",
    "saint-peters-peacocks",
    "siena",
    "siena-saints",
  ],
    teamAbbrevs: [
    "CAN",
    "FAIR",
    "IONA",
    "MAN",
    "MRMK",
    "MRST",
    "MSM",
    "NIA",
    "QUIN",
    "RID",
    "SHU",
    "SIE",
    "SPU",
  ],
  },
  {
    slug: "mid-american-conference",
    name: "Mid-American Conference",
    teamSlugs: [
    "Akron",
    "Akron Zips",
    "Ball State",
    "Ball State Cardinals",
    "Bowling Green",
    "Bowling Green Falcons",
    "Buffalo",
    "Buffalo Bulls",
    "C Michigan",
    "Central Michigan Chippewas",
    "E Michigan",
    "Eastern Michigan Eagles",
    "Kent State",
    "Kent State Golden Flashes",
    "Massachusetts Minutemen",
    "Miami (OH) RedHawks",
    "Miami OH",
    "N Illinois",
    "Northern Illinois Huskies",
    "Ohio",
    "Ohio Bobcats",
    "Toledo",
    "Toledo Rockets",
    "UMass",
    "W Michigan",
    "Western Michigan Broncos",
    "akron",
    "akron-zips",
    "ball-state",
    "ball-state-cardinals",
    "bowling-green",
    "bowling-green-falcons",
    "buffalo",
    "buffalo-bulls",
    "c-michigan",
    "central-michigan",
    "central-michigan-chippewas",
    "e-michigan",
    "eastern-michigan",
    "eastern-michigan-eagles",
    "kent-state",
    "kent-state-golden",
    "kent-state-golden-flashes",
    "massachusetts",
    "massachusetts-minutemen",
    "miami-oh",
    "miami-oh-redhawks",
    "n-illinois",
    "northern-illinois",
    "northern-illinois-huskies",
    "ohio",
    "ohio-bobcats",
    "toledo",
    "toledo-rockets",
    "umass",
    "w-michigan",
    "western-michigan",
    "western-michigan-broncos",
  ],
    teamNames: [
    "Akron",
    "Akron Zips",
    "Ball State",
    "Ball State Cardinals",
    "Bowling Green",
    "Bowling Green Falcons",
    "Buffalo",
    "Buffalo Bulls",
    "C Michigan",
    "Central Michigan Chippewas",
    "E Michigan",
    "Eastern Michigan Eagles",
    "Kent State",
    "Kent State Golden Flashes",
    "Massachusetts Minutemen",
    "Miami (OH) RedHawks",
    "Miami OH",
    "N Illinois",
    "Northern Illinois Huskies",
    "Ohio",
    "Ohio Bobcats",
    "Toledo",
    "Toledo Rockets",
    "UMass",
    "W Michigan",
    "Western Michigan Broncos",
    "akron",
    "akron-zips",
    "ball-state",
    "ball-state-cardinals",
    "bowling-green",
    "bowling-green-falcons",
    "buffalo",
    "buffalo-bulls",
    "c-michigan",
    "central-michigan-chippewas",
    "e-michigan",
    "eastern-michigan-eagles",
    "kent-state",
    "kent-state-golden-flashes",
    "massachusetts-minutemen",
    "miami-oh",
    "miami-oh-redhawks",
    "n-illinois",
    "northern-illinois-huskies",
    "ohio",
    "ohio-bobcats",
    "toledo",
    "toledo-rockets",
    "umass",
    "w-michigan",
    "western-michigan-broncos",
  ],
    teamAbbrevs: [
    "AKR",
    "BALL",
    "BGSU",
    "BUF",
    "CMU",
    "EMU",
    "KENT",
    "M-OH",
    "MASS",
    "NIU",
    "OHIO",
    "TOL",
    "WMU",
  ],
  },
  {
    slug: "mid-eastern-athletic-conference",
    name: "Mid-Eastern Athletic Conference",
    teamSlugs: [
    "Coppin St",
    "Coppin State Eagles",
    "Delaware St",
    "Delaware State Hornets",
    "Howard",
    "Howard Bison",
    "MD Eastern",
    "Maryland Eastern Shore Hawks",
    "Morgan St",
    "Morgan State Bears",
    "NC Central",
    "Norfolk St",
    "Norfolk State Spartans",
    "North Carolina Central Eagles",
    "SC State",
    "South Carolina State Bulldogs",
    "coppin-st",
    "coppin-state",
    "coppin-state-eagles",
    "delaware-st",
    "delaware-state",
    "delaware-state-hornets",
    "howard",
    "howard-bison",
    "maryland-eastern-shore",
    "maryland-eastern-shore-hawks",
    "md-eastern",
    "morgan-st",
    "morgan-state",
    "morgan-state-bears",
    "nc-central",
    "norfolk-st",
    "norfolk-state",
    "norfolk-state-spartans",
    "north-carolina-central",
    "north-carolina-central-eagles",
    "sc-state",
    "south-carolina-state",
    "south-carolina-state-bulldogs",
  ],
    teamNames: [
    "Coppin St",
    "Coppin State Eagles",
    "Delaware St",
    "Delaware State Hornets",
    "Howard",
    "Howard Bison",
    "MD Eastern",
    "Maryland Eastern Shore Hawks",
    "Morgan St",
    "Morgan State Bears",
    "NC Central",
    "Norfolk St",
    "Norfolk State Spartans",
    "North Carolina Central Eagles",
    "SC State",
    "South Carolina State Bulldogs",
    "coppin-st",
    "coppin-state-eagles",
    "delaware-st",
    "delaware-state-hornets",
    "howard",
    "howard-bison",
    "maryland-eastern-shore-hawks",
    "md-eastern",
    "morgan-st",
    "morgan-state-bears",
    "nc-central",
    "norfolk-st",
    "norfolk-state-spartans",
    "north-carolina-central-eagles",
    "sc-state",
    "south-carolina-state-bulldogs",
  ],
    teamAbbrevs: [
    "COPP",
    "DSU",
    "HOW",
    "MORG",
    "NCCU",
    "NORF",
    "SCST",
    "UMES",
  ],
  },
  {
    slug: "missouri-valley-conference",
    name: "Missouri Valley Conference",
    teamSlugs: [
    "Belmont",
    "Belmont Bruins",
    "Bradley",
    "Bradley Braves",
    "Drake",
    "Drake Bulldogs",
    "Evansville",
    "Evansville Purple Aces",
    "Illinois St",
    "Illinois State Redbirds",
    "Indiana St",
    "Indiana State Sycamores",
    "Murray St",
    "Murray State Racers",
    "Northern Iowa",
    "Northern Iowa Panthers",
    "S Illinois",
    "Southern Illinois Salukis",
    "UIC",
    "UIC Flames",
    "Valparaiso",
    "Valparaiso Beacons",
    "belmont",
    "belmont-bruins",
    "bradley",
    "bradley-braves",
    "drake",
    "drake-bulldogs",
    "evansville",
    "evansville-purple",
    "evansville-purple-aces",
    "illinois-st",
    "illinois-state",
    "illinois-state-redbirds",
    "indiana-st",
    "indiana-state",
    "indiana-state-sycamores",
    "murray-st",
    "murray-state",
    "murray-state-racers",
    "northern-iowa",
    "northern-iowa-panthers",
    "s-illinois",
    "southern-illinois",
    "southern-illinois-salukis",
    "uic",
    "uic-flames",
    "valparaiso",
    "valparaiso-beacons",
  ],
    teamNames: [
    "Belmont",
    "Belmont Bruins",
    "Bradley",
    "Bradley Braves",
    "Drake",
    "Drake Bulldogs",
    "Evansville",
    "Evansville Purple Aces",
    "Illinois St",
    "Illinois State Redbirds",
    "Indiana St",
    "Indiana State Sycamores",
    "Murray St",
    "Murray State Racers",
    "Northern Iowa",
    "Northern Iowa Panthers",
    "S Illinois",
    "Southern Illinois Salukis",
    "UIC",
    "UIC Flames",
    "Valparaiso",
    "Valparaiso Beacons",
    "belmont",
    "belmont-bruins",
    "bradley",
    "bradley-braves",
    "drake",
    "drake-bulldogs",
    "evansville",
    "evansville-purple-aces",
    "illinois-st",
    "illinois-state-redbirds",
    "indiana-st",
    "indiana-state-sycamores",
    "murray-st",
    "murray-state-racers",
    "northern-iowa",
    "northern-iowa-panthers",
    "s-illinois",
    "southern-illinois-salukis",
    "uic",
    "uic-flames",
    "valparaiso",
    "valparaiso-beacons",
  ],
    teamAbbrevs: [
    "BEL",
    "BRAD",
    "DRKE",
    "EVAN",
    "ILST",
    "INST",
    "MUR",
    "SIU",
    "UIC",
    "UNI",
    "VAL",
  ],
  },
  {
    slug: "mountain-west-conference",
    name: "Mountain West Conference",
    teamSlugs: [
    "Air Force",
    "Air Force Falcons",
    "Boise St",
    "Boise State Broncos",
    "Colorado St",
    "Colorado State Rams",
    "Fresno St",
    "Fresno State Bulldogs",
    "Grand Canyon",
    "Grand Canyon Lopes",
    "Nevada",
    "Nevada Wolf Pack",
    "New Mexico",
    "New Mexico Lobos",
    "San Diego St",
    "San Diego State Aztecs",
    "San Jos\u00e9 St",
    "San Jos\u00e9 State Spartans",
    "UNLV",
    "UNLV Rebels",
    "Utah State",
    "Utah State Aggies",
    "Wyoming",
    "Wyoming Cowboys",
    "air-force",
    "air-force-falcons",
    "boise-st",
    "boise-state",
    "boise-state-broncos",
    "colorado-st",
    "colorado-state",
    "colorado-state-rams",
    "fresno-st",
    "fresno-state",
    "fresno-state-bulldogs",
    "grand-canyon",
    "grand-canyon-lopes",
    "nevada",
    "nevada-wolf",
    "nevada-wolf-pack",
    "new-mexico",
    "new-mexico-lobos",
    "san-diego-st",
    "san-diego-state",
    "san-diego-state-aztecs",
    "san-jos-st",
    "san-jos-state-spartans",
    "san-jose-state",
    "san-jose-state-spartans",
    "unlv",
    "unlv-rebels",
    "utah-state",
    "utah-state-aggies",
    "wyoming",
    "wyoming-cowboys",
  ],
    teamNames: [
    "Air Force",
    "Air Force Falcons",
    "Boise St",
    "Boise State Broncos",
    "Colorado St",
    "Colorado State Rams",
    "Fresno St",
    "Fresno State Bulldogs",
    "Grand Canyon",
    "Grand Canyon Lopes",
    "Nevada",
    "Nevada Wolf Pack",
    "New Mexico",
    "New Mexico Lobos",
    "San Diego St",
    "San Diego State Aztecs",
    "San Jos\u00e9 St",
    "San Jos\u00e9 State Spartans",
    "UNLV",
    "UNLV Rebels",
    "Utah State",
    "Utah State Aggies",
    "Wyoming",
    "Wyoming Cowboys",
    "air-force",
    "air-force-falcons",
    "boise-st",
    "boise-state-broncos",
    "colorado-st",
    "colorado-state-rams",
    "fresno-st",
    "fresno-state-bulldogs",
    "grand-canyon",
    "grand-canyon-lopes",
    "nevada",
    "nevada-wolf-pack",
    "new-mexico",
    "new-mexico-lobos",
    "san-diego-st",
    "san-diego-state-aztecs",
    "san-jos-st",
    "san-jos-state-spartans",
    "unlv",
    "unlv-rebels",
    "utah-state",
    "utah-state-aggies",
    "wyoming",
    "wyoming-cowboys",
  ],
    teamAbbrevs: [
    "AF",
    "BOIS",
    "CSU",
    "FRES",
    "GCU",
    "NEV",
    "SDSU",
    "SJSU",
    "UNLV",
    "UNM",
    "USU",
    "WYO",
  ],
  },
  {
    slug: "northeast-conference",
    name: "Northeast Conference",
    teamSlugs: [
    "C Connecticut",
    "Central Connecticut Blue Devils",
    "Chicago St",
    "Chicago State Cougars",
    "FDU",
    "Fairleigh Dickinson Knights",
    "Le Moyne",
    "Le Moyne Dolphins",
    "Long Island",
    "Long Island University Sharks",
    "Mercyhurst",
    "Mercyhurst Lakers",
    "New Haven",
    "New Haven Chargers",
    "Saint Francis",
    "Saint Francis Red Wolves",
    "Stonehill",
    "Stonehill Skyhawks",
    "Wagner",
    "Wagner Seahawks",
    "c-connecticut",
    "central-connecticut-blue",
    "central-connecticut-blue-devils",
    "chicago-st",
    "chicago-state",
    "chicago-state-cougars",
    "fairleigh-dickinson",
    "fairleigh-dickinson-knights",
    "fdu",
    "le-moyne",
    "le-moyne-dolphins",
    "long-island",
    "long-island-university",
    "long-island-university-sharks",
    "mercyhurst",
    "mercyhurst-lakers",
    "new-haven",
    "new-haven-chargers",
    "saint-francis",
    "saint-francis-red",
    "saint-francis-red-wolves",
    "stonehill",
    "stonehill-skyhawks",
    "wagner",
    "wagner-seahawks",
  ],
    teamNames: [
    "C Connecticut",
    "Central Connecticut Blue Devils",
    "Chicago St",
    "Chicago State Cougars",
    "FDU",
    "Fairleigh Dickinson Knights",
    "Le Moyne",
    "Le Moyne Dolphins",
    "Long Island",
    "Long Island University Sharks",
    "Mercyhurst",
    "Mercyhurst Lakers",
    "New Haven",
    "New Haven Chargers",
    "Saint Francis",
    "Saint Francis Red Wolves",
    "Stonehill",
    "Stonehill Skyhawks",
    "Wagner",
    "Wagner Seahawks",
    "c-connecticut",
    "central-connecticut-blue-devils",
    "chicago-st",
    "chicago-state-cougars",
    "fairleigh-dickinson-knights",
    "fdu",
    "le-moyne",
    "le-moyne-dolphins",
    "long-island",
    "long-island-university-sharks",
    "mercyhurst",
    "mercyhurst-lakers",
    "new-haven",
    "new-haven-chargers",
    "saint-francis",
    "saint-francis-red-wolves",
    "stonehill",
    "stonehill-skyhawks",
    "wagner",
    "wagner-seahawks",
  ],
    teamAbbrevs: [
    "CCSU",
    "CHST",
    "FDU",
    "LEM",
    "LIU",
    "MERC",
    "NHVN",
    "SFPA",
    "STO",
    "WAG",
  ],
  },
  {
    slug: "ohio-valley-conference",
    name: "Ohio Valley Conference",
    teamSlugs: [
    "E Illinois",
    "Eastern Illinois Panthers",
    "Lindenwood",
    "Lindenwood Lions",
    "Little Rock",
    "Little Rock Trojans",
    "Morehead St",
    "Morehead State Eagles",
    "SE Missouri",
    "SIU Edwardsville Cougars",
    "SIUE",
    "So Indiana",
    "Southeast Missouri State Redhawks",
    "Southern Indiana Screaming Eagles",
    "Tennessee St",
    "Tennessee State Tigers",
    "Tennessee Tech",
    "Tennessee Tech Golden Eagles",
    "UT Martin",
    "UT Martin Skyhawks",
    "W Illinois",
    "Western Illinois Leathernecks",
    "e-illinois",
    "eastern-illinois",
    "eastern-illinois-panthers",
    "lindenwood",
    "lindenwood-lions",
    "little-rock",
    "little-rock-trojans",
    "morehead-st",
    "morehead-state",
    "morehead-state-eagles",
    "se-missouri",
    "siu-edwardsville",
    "siu-edwardsville-cougars",
    "siue",
    "so-indiana",
    "southeast-missouri-state",
    "southeast-missouri-state-redhawks",
    "southern-indiana-screaming",
    "southern-indiana-screaming-eagles",
    "tennessee-st",
    "tennessee-state",
    "tennessee-state-tigers",
    "tennessee-tech",
    "tennessee-tech-golden",
    "tennessee-tech-golden-eagles",
    "ut-martin",
    "ut-martin-skyhawks",
    "w-illinois",
    "western-illinois",
    "western-illinois-leathernecks",
  ],
    teamNames: [
    "E Illinois",
    "Eastern Illinois Panthers",
    "Lindenwood",
    "Lindenwood Lions",
    "Little Rock",
    "Little Rock Trojans",
    "Morehead St",
    "Morehead State Eagles",
    "SE Missouri",
    "SIU Edwardsville Cougars",
    "SIUE",
    "So Indiana",
    "Southeast Missouri State Redhawks",
    "Southern Indiana Screaming Eagles",
    "Tennessee St",
    "Tennessee State Tigers",
    "Tennessee Tech",
    "Tennessee Tech Golden Eagles",
    "UT Martin",
    "UT Martin Skyhawks",
    "W Illinois",
    "Western Illinois Leathernecks",
    "e-illinois",
    "eastern-illinois-panthers",
    "lindenwood",
    "lindenwood-lions",
    "little-rock",
    "little-rock-trojans",
    "morehead-st",
    "morehead-state-eagles",
    "se-missouri",
    "siu-edwardsville-cougars",
    "siue",
    "so-indiana",
    "southeast-missouri-state-redhawks",
    "southern-indiana-screaming-eagles",
    "tennessee-st",
    "tennessee-state-tigers",
    "tennessee-tech",
    "tennessee-tech-golden-eagles",
    "ut-martin",
    "ut-martin-skyhawks",
    "w-illinois",
    "western-illinois-leathernecks",
  ],
    teamAbbrevs: [
    "EIU",
    "LIN",
    "LR",
    "MORE",
    "SEMO",
    "SIUE",
    "TNST",
    "TNTC",
    "USI",
    "UTM",
    "WIU",
  ],
  },
  {
    slug: "patriot-league",
    name: "Patriot League",
    teamSlugs: [
    "American",
    "American University Eagles",
    "Army",
    "Army Black Knights",
    "Boston U",
    "Boston University Terriers",
    "Bucknell",
    "Bucknell Bison",
    "Colgate",
    "Colgate Raiders",
    "Holy Cross",
    "Holy Cross Crusaders",
    "Lafayette",
    "Lafayette Leopards",
    "Lehigh",
    "Lehigh Mountain Hawks",
    "Loyola MD",
    "Loyola Maryland Greyhounds",
    "Navy",
    "Navy Midshipmen",
    "american",
    "american-university",
    "american-university-eagles",
    "army",
    "army-black",
    "army-black-knights",
    "boston-u",
    "boston-university",
    "boston-university-terriers",
    "bucknell",
    "bucknell-bison",
    "colgate",
    "colgate-raiders",
    "holy-cross",
    "holy-cross-crusaders",
    "lafayette",
    "lafayette-leopards",
    "lehigh",
    "lehigh-mountain",
    "lehigh-mountain-hawks",
    "loyola-maryland",
    "loyola-maryland-greyhounds",
    "loyola-md",
    "navy",
    "navy-midshipmen",
  ],
    teamNames: [
    "American",
    "American University Eagles",
    "Army",
    "Army Black Knights",
    "Boston U",
    "Boston University Terriers",
    "Bucknell",
    "Bucknell Bison",
    "Colgate",
    "Colgate Raiders",
    "Holy Cross",
    "Holy Cross Crusaders",
    "Lafayette",
    "Lafayette Leopards",
    "Lehigh",
    "Lehigh Mountain Hawks",
    "Loyola MD",
    "Loyola Maryland Greyhounds",
    "Navy",
    "Navy Midshipmen",
    "american",
    "american-university-eagles",
    "army",
    "army-black-knights",
    "boston-u",
    "boston-university-terriers",
    "bucknell",
    "bucknell-bison",
    "colgate",
    "colgate-raiders",
    "holy-cross",
    "holy-cross-crusaders",
    "lafayette",
    "lafayette-leopards",
    "lehigh",
    "lehigh-mountain-hawks",
    "loyola-maryland-greyhounds",
    "loyola-md",
    "navy",
    "navy-midshipmen",
  ],
    teamAbbrevs: [
    "AMER",
    "ARMY",
    "BU",
    "BUCK",
    "COLG",
    "HC",
    "L-MD",
    "LAF",
    "LEH",
    "NAVY",
  ],
  },
  {
    slug: "southeastern-conference",
    name: "Southeastern Conference",
    teamSlugs: [
    "Alabama",
    "Alabama Crimson Tide",
    "Arkansas",
    "Arkansas Razorbacks",
    "Auburn",
    "Auburn Tigers",
    "Florida",
    "Florida Gators",
    "Georgia",
    "Georgia Bulldogs",
    "Kentucky",
    "Kentucky Wildcats",
    "LSU",
    "LSU Tigers",
    "Mississippi St",
    "Mississippi State Bulldogs",
    "Missouri",
    "Missouri Tigers",
    "Oklahoma",
    "Oklahoma Sooners",
    "Ole Miss",
    "Ole Miss Rebels",
    "South Carolina",
    "South Carolina Gamecocks",
    "Tennessee",
    "Tennessee Volunteers",
    "Texas",
    "Texas A&M",
    "Texas A&M Aggies",
    "Texas Longhorns",
    "Vanderbilt",
    "Vanderbilt Commodores",
    "alabama",
    "alabama-crimson",
    "alabama-crimson-tide",
    "arkansas",
    "arkansas-razorbacks",
    "auburn",
    "auburn-tigers",
    "florida",
    "florida-gators",
    "georgia",
    "georgia-bulldogs",
    "kentucky",
    "kentucky-wildcats",
    "lsu",
    "lsu-tigers",
    "mississippi-st",
    "mississippi-state",
    "mississippi-state-bulldogs",
    "missouri",
    "missouri-tigers",
    "oklahoma",
    "oklahoma-sooners",
    "ole-miss",
    "ole-miss-rebels",
    "south-carolina",
    "south-carolina-gamecocks",
    "tennessee",
    "tennessee-volunteers",
    "texas",
    "texas-a-m",
    "texas-a-m-aggies",
    "texas-am",
    "texas-am-aggies",
    "texas-longhorns",
    "vanderbilt",
    "vanderbilt-commodores",
  ],
    teamNames: [
    "Alabama",
    "Alabama Crimson Tide",
    "Arkansas",
    "Arkansas Razorbacks",
    "Auburn",
    "Auburn Tigers",
    "Florida",
    "Florida Gators",
    "Georgia",
    "Georgia Bulldogs",
    "Kentucky",
    "Kentucky Wildcats",
    "LSU",
    "LSU Tigers",
    "Mississippi St",
    "Mississippi State Bulldogs",
    "Missouri",
    "Missouri Tigers",
    "Oklahoma",
    "Oklahoma Sooners",
    "Ole Miss",
    "Ole Miss Rebels",
    "South Carolina",
    "South Carolina Gamecocks",
    "Tennessee",
    "Tennessee Volunteers",
    "Texas",
    "Texas A&M",
    "Texas A&M Aggies",
    "Texas Longhorns",
    "Vanderbilt",
    "Vanderbilt Commodores",
    "alabama",
    "alabama-crimson-tide",
    "arkansas",
    "arkansas-razorbacks",
    "auburn",
    "auburn-tigers",
    "florida",
    "florida-gators",
    "georgia",
    "georgia-bulldogs",
    "kentucky",
    "kentucky-wildcats",
    "lsu",
    "lsu-tigers",
    "mississippi-st",
    "mississippi-state-bulldogs",
    "missouri",
    "missouri-tigers",
    "oklahoma",
    "oklahoma-sooners",
    "ole-miss",
    "ole-miss-rebels",
    "south-carolina",
    "south-carolina-gamecocks",
    "tennessee",
    "tennessee-volunteers",
    "texas",
    "texas-a-m",
    "texas-a-m-aggies",
    "texas-longhorns",
    "vanderbilt",
    "vanderbilt-commodores",
  ],
    teamAbbrevs: [
    "ALA",
    "ARK",
    "AUB",
    "FLA",
    "LSU",
    "MISS",
    "MIZ",
    "MSST",
    "OU",
    "SC",
    "TA&M",
    "TENN",
    "TEX",
    "UGA",
    "UK",
    "VAN",
  ],
  },
] as const;

export const OTHER_NCAA_M_CONFERENCE_SLUG = "other";

function nameToSlug(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[''.]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function normalizeName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[''.]/g, "")
    .replace(/\s+/g, " ");
}

function slugMatches(teamSlug: string, conferenceSlug: string): boolean {
  return Boolean(teamSlug && conferenceSlug && teamSlug === conferenceSlug);
}

function teamMatchesConference(
  team: { name: string; abbreviation: string; slug: string },
  conference: NcaaConferenceMeta,
): boolean {
  const slug = team.slug.trim().toLowerCase();
  const nameSlug = nameToSlug(team.name);
  const abbrev = team.abbreviation.trim().toUpperCase();
  const normalizedTeamName = normalizeName(team.name);

  for (const conferenceSlug of conference.teamSlugs) {
    if (slugMatches(slug, conferenceSlug)) return true;
    if (nameSlug && slugMatches(nameSlug, conferenceSlug)) return true;
  }

  for (const conferenceName of conference.teamNames) {
    const normalizedConferenceName = normalizeName(conferenceName);
    if (normalizedConferenceName === normalizedTeamName) return true;
    if (normalizedConferenceName.startsWith(`${normalizedTeamName} `)) return true;
  }

  if (abbrev && conference.teamAbbrevs.includes(abbrev)) return true;
  return false;
}

export function conferenceForNcaaTeam(
  team: { name: string; abbreviation: string; slug: string },
): string {
  for (const conference of NCAA_M_CONFERENCES) {
    if (teamMatchesConference(team, conference)) {
      return conference.slug;
    }
  }
  return OTHER_NCAA_M_CONFERENCE_SLUG;
}

export function getNcaaConference(slug: string): NcaaConferenceMeta | undefined {
  return NCAA_M_CONFERENCES.find((conference) => conference.slug === slug);
}

export interface NcaaConferenceGroup<T> {
  conference: NcaaConferenceMeta | { slug: string; name: string };
  teams: T[];
}

export function groupNcaaTeamsByConference<T extends { name: string; abbreviation: string; slug: string }>(
  teams: T[],
): NcaaConferenceGroup<T>[] {
  const buckets = new Map<string, T[]>();

  for (const team of teams) {
    const conferenceSlug = conferenceForNcaaTeam(team);
    const existing = buckets.get(conferenceSlug) ?? [];
    existing.push(team);
    buckets.set(conferenceSlug, existing);
  }

  const groups: NcaaConferenceGroup<T>[] = NCAA_M_CONFERENCES.map((conference) => ({
    conference,
    teams: (buckets.get(conference.slug) ?? []).sort((a, b) => a.name.localeCompare(b.name)),
  })).filter((group) => group.teams.length > 0);

  const otherTeams = buckets.get(OTHER_NCAA_M_CONFERENCE_SLUG) ?? [];
  if (otherTeams.length > 0) {
    groups.push({
      conference: { slug: OTHER_NCAA_M_CONFERENCE_SLUG, name: "Other" },
      teams: otherTeams.sort((a, b) => a.name.localeCompare(b.name)),
    });
  }

  return groups;
}
