// Auto-generated from ESPN men's college basketball conference groups.
// Regenerate with: python3 scripts/generate-ncaa-conferences.py
// Generated: 2026-06-19

export interface NcaaConferenceMeta {
  slug: string;
  name: string;
  teamSlugs: readonly string[];
  teamNames: readonly string[];
  teamAbbrevs: readonly string[];
}

export const NCAA_M_CONFERENCES: readonly NcaaConferenceMeta[] = [
  {
    slug: "america-east-conference",
    name: "America East Conference",
    teamSlugs: [
    "binghamton-bearcats",
    "bryant-bulldogs",
    "maine-black-bears",
    "new-hampshire-wildcats",
    "njit-highlanders",
    "ualbany-great-danes",
    "umass-lowell-river-hawks",
    "umbc-retrievers",
    "vermont-catamounts",
  ],
    teamNames: [
    "Binghamton Bearcats",
    "Bryant Bulldogs",
    "Maine Black Bears",
    "NJIT Highlanders",
    "New Hampshire Wildcats",
    "UAlbany Great Danes",
    "UMBC Retrievers",
    "UMass Lowell River Hawks",
    "Vermont Catamounts",
  ],
    teamAbbrevs: [
    "BING",
    "BRY",
    "ME",
    "NJIT",
    "UALB",
    "UMBC",
    "UML",
    "UNH",
    "UVM",
  ],
  },
  {
    slug: "american-conference",
    name: "American Conference",
    teamSlugs: [
    "charlotte-49ers",
    "east-carolina-pirates",
    "florida-atlantic-owls",
    "memphis-tigers",
    "north-texas-mean-green",
    "rice-owls",
    "south-florida-bulls",
    "temple-owls",
    "tulane-green-wave",
    "tulsa-golden-hurricane",
    "uab-blazers",
    "utsa-roadrunners",
    "wichita-state-shockers",
  ],
    teamNames: [
    "Charlotte 49ers",
    "East Carolina Pirates",
    "Florida Atlantic Owls",
    "Memphis Tigers",
    "North Texas Mean Green",
    "Rice Owls",
    "South Florida Bulls",
    "Temple Owls",
    "Tulane Green Wave",
    "Tulsa Golden Hurricane",
    "UAB Blazers",
    "UTSA Roadrunners",
    "Wichita State Shockers",
  ],
    teamAbbrevs: [
    "CLT",
    "ECU",
    "FAU",
    "MEM",
    "RICE",
    "TEM",
    "TLSA",
    "TULN",
    "UAB",
    "UNT",
    "USF",
    "UTSA",
    "WICH",
  ],
  },
  {
    slug: "atlantic-10-conference",
    name: "Atlantic 10 Conference",
    teamSlugs: [
    "davidson-wildcats",
    "dayton-flyers",
    "duquesne-dukes",
    "fordham-rams",
    "george-mason-patriots",
    "george-washington-revolutionaries",
    "la-salle-explorers",
    "loyola-chicago-ramblers",
    "rhode-island-rams",
    "richmond-spiders",
    "saint-joseph-s-hawks",
    "saint-josephs-hawks",
    "saint-louis-billikens",
    "st-bonaventure-bonnies",
    "vcu-rams",
  ],
    teamNames: [
    "Davidson Wildcats",
    "Dayton Flyers",
    "Duquesne Dukes",
    "Fordham Rams",
    "George Mason Patriots",
    "George Washington Revolutionaries",
    "La Salle Explorers",
    "Loyola Chicago Ramblers",
    "Rhode Island Rams",
    "Richmond Spiders",
    "Saint Joseph's Hawks",
    "Saint Louis Billikens",
    "St. Bonaventure Bonnies",
    "VCU Rams",
  ],
    teamAbbrevs: [
    "DAV",
    "DAY",
    "DUQ",
    "FOR",
    "GMU",
    "GW",
    "JOES",
    "LAS",
    "LUC",
    "RICH",
    "SBU",
    "SLU",
    "URI",
    "VCU",
  ],
  },
  {
    slug: "atlantic-coast-conference",
    name: "Atlantic Coast Conference",
    teamSlugs: [
    "boston-college-eagles",
    "california-golden-bears",
    "clemson-tigers",
    "duke-blue-devils",
    "florida-state-seminoles",
    "georgia-tech-yellow-jackets",
    "louisville-cardinals",
    "miami-hurricanes",
    "nc-state-wolfpack",
    "north-carolina-tar-heels",
    "notre-dame-fighting-irish",
    "pittsburgh-panthers",
    "smu-mustangs",
    "stanford-cardinal",
    "syracuse-orange",
    "virginia-cavaliers",
    "virginia-tech-hokies",
    "wake-forest-demon-deacons",
  ],
    teamNames: [
    "Boston College Eagles",
    "California Golden Bears",
    "Clemson Tigers",
    "Duke Blue Devils",
    "Florida State Seminoles",
    "Georgia Tech Yellow Jackets",
    "Louisville Cardinals",
    "Miami Hurricanes",
    "NC State Wolfpack",
    "North Carolina Tar Heels",
    "Notre Dame Fighting Irish",
    "Pittsburgh Panthers",
    "SMU Mustangs",
    "Stanford Cardinal",
    "Syracuse Orange",
    "Virginia Cavaliers",
    "Virginia Tech Hokies",
    "Wake Forest Demon Deacons",
  ],
    teamAbbrevs: [
    "BC",
    "CAL",
    "CLEM",
    "DUKE",
    "FSU",
    "GT",
    "LOU",
    "MIA",
    "NCSU",
    "ND",
    "PITT",
    "SMU",
    "STAN",
    "SYR",
    "UNC",
    "UVA",
    "VT",
    "WAKE",
  ],
  },
  {
    slug: "atlantic-sun-conference",
    name: "Atlantic Sun Conference",
    teamSlugs: [
    "austin-peay-governors",
    "bellarmine-knights",
    "central-arkansas-bears",
    "eastern-kentucky-colonels",
    "florida-gulf-coast-eagles",
    "jacksonville-dolphins",
    "lipscomb-bisons",
    "north-alabama-lions",
    "north-florida-ospreys",
    "queens-university-royals",
    "stetson-hatters",
    "west-georgia-wolves",
  ],
    teamNames: [
    "Austin Peay Governors",
    "Bellarmine Knights",
    "Central Arkansas Bears",
    "Eastern Kentucky Colonels",
    "Florida Gulf Coast Eagles",
    "Jacksonville Dolphins",
    "Lipscomb Bisons",
    "North Alabama Lions",
    "North Florida Ospreys",
    "Queens University Royals",
    "Stetson Hatters",
    "West Georgia Wolves",
  ],
    teamAbbrevs: [
    "APSU",
    "BELL",
    "CARK",
    "EKU",
    "FGCU",
    "JAX",
    "LIP",
    "QUC",
    "STET",
    "UNA",
    "UNF",
    "WGA",
  ],
  },
  {
    slug: "big-12-conference",
    name: "Big 12 Conference",
    teamSlugs: [
    "arizona-state-sun-devils",
    "arizona-wildcats",
    "baylor-bears",
    "byu-cougars",
    "cincinnati-bearcats",
    "colorado-buffaloes",
    "houston-cougars",
    "iowa-state-cyclones",
    "kansas-jayhawks",
    "kansas-state-wildcats",
    "oklahoma-state-cowboys",
    "tcu-horned-frogs",
    "texas-tech-red-raiders",
    "ucf-knights",
    "utah-utes",
    "west-virginia-mountaineers",
  ],
    teamNames: [
    "Arizona State Sun Devils",
    "Arizona Wildcats",
    "BYU Cougars",
    "Baylor Bears",
    "Cincinnati Bearcats",
    "Colorado Buffaloes",
    "Houston Cougars",
    "Iowa State Cyclones",
    "Kansas Jayhawks",
    "Kansas State Wildcats",
    "Oklahoma State Cowboys",
    "TCU Horned Frogs",
    "Texas Tech Red Raiders",
    "UCF Knights",
    "Utah Utes",
    "West Virginia Mountaineers",
  ],
    teamAbbrevs: [
    "ARIZ",
    "ASU",
    "BAY",
    "BYU",
    "CIN",
    "COLO",
    "HOU",
    "ISU",
    "KSU",
    "KU",
    "OKST",
    "TCU",
    "TTU",
    "UCF",
    "UTAH",
    "WVU",
  ],
  },
  {
    slug: "big-east-conference",
    name: "Big East Conference",
    teamSlugs: [
    "butler-bulldogs",
    "creighton-bluejays",
    "depaul-blue-demons",
    "georgetown-hoyas",
    "marquette-golden-eagles",
    "providence-friars",
    "seton-hall-pirates",
    "st-john-s-red-storm",
    "st-johns-red-storm",
    "uconn-huskies",
    "villanova-wildcats",
    "xavier-musketeers",
  ],
    teamNames: [
    "Butler Bulldogs",
    "Creighton Bluejays",
    "DePaul Blue Demons",
    "Georgetown Hoyas",
    "Marquette Golden Eagles",
    "Providence Friars",
    "Seton Hall Pirates",
    "St. John's Red Storm",
    "UConn Huskies",
    "Villanova Wildcats",
    "Xavier Musketeers",
  ],
    teamAbbrevs: [
    "BUT",
    "CONN",
    "CREI",
    "DEP",
    "GTWN",
    "HALL",
    "MARQ",
    "PROV",
    "SJU",
    "VILL",
    "XAV",
  ],
  },
  {
    slug: "big-sky-conference",
    name: "Big Sky Conference",
    teamSlugs: [
    "eastern-washington-eagles",
    "idaho-state-bengals",
    "idaho-vandals",
    "montana-grizzlies",
    "montana-state-bobcats",
    "northern-arizona-lumberjacks",
    "northern-colorado-bears",
    "portland-state-vikings",
    "sacramento-state-hornets",
    "weber-state-wildcats",
  ],
    teamNames: [
    "Eastern Washington Eagles",
    "Idaho State Bengals",
    "Idaho Vandals",
    "Montana Grizzlies",
    "Montana State Bobcats",
    "Northern Arizona Lumberjacks",
    "Northern Colorado Bears",
    "Portland State Vikings",
    "Sacramento State Hornets",
    "Weber State Wildcats",
  ],
    teamAbbrevs: [
    "EWU",
    "IDHO",
    "IDST",
    "MONT",
    "MTST",
    "NAU",
    "PRST",
    "SAC",
    "UNCO",
    "WEB",
  ],
  },
  {
    slug: "big-south-conference",
    name: "Big South Conference",
    teamSlugs: [
    "charleston-southern-buccaneers",
    "gardner-webb-runnin-bulldogs",
    "high-point-panthers",
    "longwood-lancers",
    "presbyterian-blue-hose",
    "radford-highlanders",
    "south-carolina-upstate-spartans",
    "unc-asheville-bulldogs",
    "winthrop-eagles",
  ],
    teamNames: [
    "Charleston Southern Buccaneers",
    "Gardner-Webb Runnin' Bulldogs",
    "High Point Panthers",
    "Longwood Lancers",
    "Presbyterian Blue Hose",
    "Radford Highlanders",
    "South Carolina Upstate Spartans",
    "UNC Asheville Bulldogs",
    "Winthrop Eagles",
  ],
    teamAbbrevs: [
    "CHSO",
    "GWEB",
    "HPU",
    "LONG",
    "PRES",
    "RAD",
    "UNCA",
    "UPST",
    "WIN",
  ],
  },
  {
    slug: "big-ten-conference",
    name: "Big Ten Conference",
    teamSlugs: [
    "illinois-fighting-illini",
    "indiana-hoosiers",
    "iowa-hawkeyes",
    "maryland-terrapins",
    "michigan-state-spartans",
    "michigan-wolverines",
    "minnesota-golden-gophers",
    "nebraska-cornhuskers",
    "northwestern-wildcats",
    "ohio-state-buckeyes",
    "oregon-ducks",
    "penn-state-nittany-lions",
    "purdue-boilermakers",
    "rutgers-scarlet-knights",
    "ucla-bruins",
    "usc-trojans",
    "washington-huskies",
    "wisconsin-badgers",
  ],
    teamNames: [
    "Illinois Fighting Illini",
    "Indiana Hoosiers",
    "Iowa Hawkeyes",
    "Maryland Terrapins",
    "Michigan State Spartans",
    "Michigan Wolverines",
    "Minnesota Golden Gophers",
    "Nebraska Cornhuskers",
    "Northwestern Wildcats",
    "Ohio State Buckeyes",
    "Oregon Ducks",
    "Penn State Nittany Lions",
    "Purdue Boilermakers",
    "Rutgers Scarlet Knights",
    "UCLA Bruins",
    "USC Trojans",
    "Washington Huskies",
    "Wisconsin Badgers",
  ],
    teamAbbrevs: [
    "ILL",
    "IOWA",
    "IU",
    "MD",
    "MICH",
    "MINN",
    "MSU",
    "NEB",
    "NU",
    "ORE",
    "OSU",
    "PSU",
    "PUR",
    "RUTG",
    "UCLA",
    "USC",
    "WASH",
    "WIS",
  ],
  },
  {
    slug: "big-west-conference",
    name: "Big West Conference",
    teamSlugs: [
    "cal-poly-mustangs",
    "cal-state-bakersfield-roadrunners",
    "cal-state-fullerton-titans",
    "cal-state-northridge-matadors",
    "hawai-i-rainbow-warriors",
    "hawaii-rainbow-warriors",
    "long-beach-state-beach",
    "uc-davis-aggies",
    "uc-irvine-anteaters",
    "uc-riverside-highlanders",
    "uc-san-diego-tritons",
    "uc-santa-barbara-gauchos",
  ],
    teamNames: [
    "Cal Poly Mustangs",
    "Cal State Bakersfield Roadrunners",
    "Cal State Fullerton Titans",
    "Cal State Northridge Matadors",
    "Hawai'i Rainbow Warriors",
    "Long Beach State Beach",
    "UC Davis Aggies",
    "UC Irvine Anteaters",
    "UC Riverside Highlanders",
    "UC San Diego Tritons",
    "UC Santa Barbara Gauchos",
  ],
    teamAbbrevs: [
    "CP",
    "CSUB",
    "CSUF",
    "CSUN",
    "HAW",
    "LBSU",
    "UCD",
    "UCI",
    "UCR",
    "UCSB",
    "UCSD",
  ],
  },
  {
    slug: "coastal-athletic-association",
    name: "Coastal Athletic Association",
    teamSlugs: [
    "campbell-fighting-camels",
    "charleston-cougars",
    "drexel-dragons",
    "elon-phoenix",
    "hampton-pirates",
    "hofstra-pride",
    "monmouth-hawks",
    "north-carolina-a-t-aggies",
    "north-carolina-at-aggies",
    "northeastern-huskies",
    "stony-brook-seawolves",
    "towson-tigers",
    "unc-wilmington-seahawks",
    "william-mary-tribe",
  ],
    teamNames: [
    "Campbell Fighting Camels",
    "Charleston Cougars",
    "Drexel Dragons",
    "Elon Phoenix",
    "Hampton Pirates",
    "Hofstra Pride",
    "Monmouth Hawks",
    "North Carolina A&T Aggies",
    "Northeastern Huskies",
    "Stony Brook Seawolves",
    "Towson Tigers",
    "UNC Wilmington Seahawks",
    "William & Mary Tribe",
  ],
    teamAbbrevs: [
    "CAM",
    "COFC",
    "DREX",
    "ELON",
    "HAMP",
    "HOF",
    "MONM",
    "NCAT",
    "NE",
    "STBK",
    "TOW",
    "UNCW",
    "W&M",
  ],
  },
  {
    slug: "college-basketball-crown",
    name: "College Basketball Crown",
    teamSlugs: [
    "baylor-bears",
    "colorado-buffaloes",
    "creighton-bluejays",
    "minnesota-golden-gophers",
    "oklahoma-sooners",
    "rutgers-scarlet-knights",
    "stanford-cardinal",
    "west-virginia-mountaineers",
  ],
    teamNames: [
    "Baylor Bears",
    "Colorado Buffaloes",
    "Creighton Bluejays",
    "Minnesota Golden Gophers",
    "Oklahoma Sooners",
    "Rutgers Scarlet Knights",
    "Stanford Cardinal",
    "West Virginia Mountaineers",
  ],
    teamAbbrevs: [
    "BAY",
    "COLO",
    "CREI",
    "MINN",
    "OU",
    "RUTG",
    "STAN",
    "WVU",
  ],
  },
  {
    slug: "conference-usa",
    name: "Conference USA",
    teamSlugs: [
    "delaware-blue-hens",
    "florida-international-panthers",
    "jacksonville-state-gamecocks",
    "kennesaw-state-owls",
    "liberty-flames",
    "louisiana-tech-bulldogs",
    "middle-tennessee-blue-raiders",
    "missouri-state-bears",
    "new-mexico-state-aggies",
    "sam-houston-bearkats",
    "utep-miners",
    "western-kentucky-hilltoppers",
  ],
    teamNames: [
    "Delaware Blue Hens",
    "Florida International Panthers",
    "Jacksonville State Gamecocks",
    "Kennesaw State Owls",
    "Liberty Flames",
    "Louisiana Tech Bulldogs",
    "Middle Tennessee Blue Raiders",
    "Missouri State Bears",
    "New Mexico State Aggies",
    "Sam Houston Bearkats",
    "UTEP Miners",
    "Western Kentucky Hilltoppers",
  ],
    teamAbbrevs: [
    "DEL",
    "FIU",
    "JXST",
    "KENN",
    "LIB",
    "LT",
    "MOST",
    "MTSU",
    "NMSU",
    "SHSU",
    "UTEP",
    "WKU",
  ],
  },
  {
    slug: "horizon-league",
    name: "Horizon League",
    teamSlugs: [
    "cleveland-state-vikings",
    "detroit-mercy-titans",
    "green-bay-phoenix",
    "iu-indianapolis-jaguars",
    "milwaukee-panthers",
    "northern-kentucky-norse",
    "oakland-golden-grizzlies",
    "purdue-fort-wayne-mastodons",
    "robert-morris-colonials",
    "wright-state-raiders",
    "youngstown-state-penguins",
  ],
    teamNames: [
    "Cleveland State Vikings",
    "Detroit Mercy Titans",
    "Green Bay Phoenix",
    "IU Indianapolis Jaguars",
    "Milwaukee Panthers",
    "Northern Kentucky Norse",
    "Oakland Golden Grizzlies",
    "Purdue Fort Wayne Mastodons",
    "Robert Morris Colonials",
    "Wright State Raiders",
    "Youngstown State Penguins",
  ],
    teamAbbrevs: [
    "CLE",
    "DETM",
    "GB",
    "IUIN",
    "MILW",
    "NKU",
    "OAK",
    "PFW",
    "RMU",
    "WRST",
    "YSU",
  ],
  },
  {
    slug: "ivy-league",
    name: "Ivy League",
    teamSlugs: [
    "brown-bears",
    "columbia-lions",
    "cornell-big-red",
    "dartmouth-big-green",
    "harvard-crimson",
    "pennsylvania-quakers",
    "princeton-tigers",
    "yale-bulldogs",
  ],
    teamNames: [
    "Brown Bears",
    "Columbia Lions",
    "Cornell Big Red",
    "Dartmouth Big Green",
    "Harvard Crimson",
    "Pennsylvania Quakers",
    "Princeton Tigers",
    "Yale Bulldogs",
  ],
    teamAbbrevs: [
    "BRWN",
    "COLU",
    "COR",
    "DART",
    "HARV",
    "PENN",
    "PRIN",
    "YALE",
  ],
  },
  {
    slug: "metro-atlantic-athletic-conference",
    name: "Metro Atlantic Athletic Conference",
    teamSlugs: [
    "canisius-golden-griffins",
    "fairfield-stags",
    "iona-gaels",
    "manhattan-jaspers",
    "marist-red-foxes",
    "merrimack-warriors",
    "mount-st-mary-s-mountaineers",
    "mount-st-marys-mountaineers",
    "niagara-purple-eagles",
    "quinnipiac-bobcats",
    "rider-broncs",
    "sacred-heart-pioneers",
    "saint-peter-s-peacocks",
    "saint-peters-peacocks",
    "siena-saints",
  ],
    teamNames: [
    "Canisius Golden Griffins",
    "Fairfield Stags",
    "Iona Gaels",
    "Manhattan Jaspers",
    "Marist Red Foxes",
    "Merrimack Warriors",
    "Mount St. Mary's Mountaineers",
    "Niagara Purple Eagles",
    "Quinnipiac Bobcats",
    "Rider Broncs",
    "Sacred Heart Pioneers",
    "Saint Peter's Peacocks",
    "Siena Saints",
  ],
    teamAbbrevs: [
    "CAN",
    "FAIR",
    "IONA",
    "MAN",
    "MRMK",
    "MRST",
    "MSM",
    "NIA",
    "QUIN",
    "RID",
    "SHU",
    "SIE",
    "SPU",
  ],
  },
  {
    slug: "mid-american-conference",
    name: "Mid-American Conference",
    teamSlugs: [
    "akron-zips",
    "ball-state-cardinals",
    "bowling-green-falcons",
    "buffalo-bulls",
    "central-michigan-chippewas",
    "eastern-michigan-eagles",
    "kent-state-golden-flashes",
    "massachusetts-minutemen",
    "miami-oh-redhawks",
    "northern-illinois-huskies",
    "ohio-bobcats",
    "toledo-rockets",
    "western-michigan-broncos",
  ],
    teamNames: [
    "Akron Zips",
    "Ball State Cardinals",
    "Bowling Green Falcons",
    "Buffalo Bulls",
    "Central Michigan Chippewas",
    "Eastern Michigan Eagles",
    "Kent State Golden Flashes",
    "Massachusetts Minutemen",
    "Miami (OH) RedHawks",
    "Northern Illinois Huskies",
    "Ohio Bobcats",
    "Toledo Rockets",
    "Western Michigan Broncos",
  ],
    teamAbbrevs: [
    "AKR",
    "BALL",
    "BGSU",
    "BUF",
    "CMU",
    "EMU",
    "KENT",
    "M-OH",
    "MASS",
    "NIU",
    "OHIO",
    "TOL",
    "WMU",
  ],
  },
  {
    slug: "mid-eastern-athletic-conference",
    name: "Mid-Eastern Athletic Conference",
    teamSlugs: [
    "coppin-state-eagles",
    "delaware-state-hornets",
    "howard-bison",
    "maryland-eastern-shore-hawks",
    "morgan-state-bears",
    "norfolk-state-spartans",
    "north-carolina-central-eagles",
    "south-carolina-state-bulldogs",
  ],
    teamNames: [
    "Coppin State Eagles",
    "Delaware State Hornets",
    "Howard Bison",
    "Maryland Eastern Shore Hawks",
    "Morgan State Bears",
    "Norfolk State Spartans",
    "North Carolina Central Eagles",
    "South Carolina State Bulldogs",
  ],
    teamAbbrevs: [
    "COPP",
    "DSU",
    "HOW",
    "MORG",
    "NCCU",
    "NORF",
    "SCST",
    "UMES",
  ],
  },
  {
    slug: "missouri-valley-conference",
    name: "Missouri Valley Conference",
    teamSlugs: [
    "belmont-bruins",
    "bradley-braves",
    "drake-bulldogs",
    "evansville-purple-aces",
    "illinois-state-redbirds",
    "indiana-state-sycamores",
    "murray-state-racers",
    "northern-iowa-panthers",
    "southern-illinois-salukis",
    "uic-flames",
    "valparaiso-beacons",
  ],
    teamNames: [
    "Belmont Bruins",
    "Bradley Braves",
    "Drake Bulldogs",
    "Evansville Purple Aces",
    "Illinois State Redbirds",
    "Indiana State Sycamores",
    "Murray State Racers",
    "Northern Iowa Panthers",
    "Southern Illinois Salukis",
    "UIC Flames",
    "Valparaiso Beacons",
  ],
    teamAbbrevs: [
    "BEL",
    "BRAD",
    "DRKE",
    "EVAN",
    "ILST",
    "INST",
    "MUR",
    "SIU",
    "UIC",
    "UNI",
    "VAL",
  ],
  },
  {
    slug: "mountain-west-conference",
    name: "Mountain West Conference",
    teamSlugs: [
    "air-force-falcons",
    "boise-state-broncos",
    "colorado-state-rams",
    "fresno-state-bulldogs",
    "grand-canyon-lopes",
    "nevada-wolf-pack",
    "new-mexico-lobos",
    "san-diego-state-aztecs",
    "san-jos-state-spartans",
    "san-jose-state-spartans",
    "unlv-rebels",
    "utah-state-aggies",
    "wyoming-cowboys",
  ],
    teamNames: [
    "Air Force Falcons",
    "Boise State Broncos",
    "Colorado State Rams",
    "Fresno State Bulldogs",
    "Grand Canyon Lopes",
    "Nevada Wolf Pack",
    "New Mexico Lobos",
    "San Diego State Aztecs",
    "San Jos\u00e9 State Spartans",
    "UNLV Rebels",
    "Utah State Aggies",
    "Wyoming Cowboys",
  ],
    teamAbbrevs: [
    "AF",
    "BOIS",
    "CSU",
    "FRES",
    "GCU",
    "NEV",
    "SDSU",
    "SJSU",
    "UNLV",
    "UNM",
    "USU",
    "WYO",
  ],
  },
  {
    slug: "northeast-conference",
    name: "Northeast Conference",
    teamSlugs: [
    "central-connecticut-blue-devils",
    "chicago-state-cougars",
    "fairleigh-dickinson-knights",
    "le-moyne-dolphins",
    "long-island-university-sharks",
    "mercyhurst-lakers",
    "new-haven-chargers",
    "saint-francis-red-wolves",
    "stonehill-skyhawks",
    "wagner-seahawks",
  ],
    teamNames: [
    "Central Connecticut Blue Devils",
    "Chicago State Cougars",
    "Fairleigh Dickinson Knights",
    "Le Moyne Dolphins",
    "Long Island University Sharks",
    "Mercyhurst Lakers",
    "New Haven Chargers",
    "Saint Francis Red Wolves",
    "Stonehill Skyhawks",
    "Wagner Seahawks",
  ],
    teamAbbrevs: [
    "CCSU",
    "CHST",
    "FDU",
    "LEM",
    "LIU",
    "MERC",
    "NHVN",
    "SFPA",
    "STO",
    "WAG",
  ],
  },
  {
    slug: "ohio-valley-conference",
    name: "Ohio Valley Conference",
    teamSlugs: [
    "eastern-illinois-panthers",
    "lindenwood-lions",
    "little-rock-trojans",
    "morehead-state-eagles",
    "siu-edwardsville-cougars",
    "southeast-missouri-state-redhawks",
    "southern-indiana-screaming-eagles",
    "tennessee-state-tigers",
    "tennessee-tech-golden-eagles",
    "ut-martin-skyhawks",
    "western-illinois-leathernecks",
  ],
    teamNames: [
    "Eastern Illinois Panthers",
    "Lindenwood Lions",
    "Little Rock Trojans",
    "Morehead State Eagles",
    "SIU Edwardsville Cougars",
    "Southeast Missouri State Redhawks",
    "Southern Indiana Screaming Eagles",
    "Tennessee State Tigers",
    "Tennessee Tech Golden Eagles",
    "UT Martin Skyhawks",
    "Western Illinois Leathernecks",
  ],
    teamAbbrevs: [
    "EIU",
    "LIN",
    "LR",
    "MORE",
    "SEMO",
    "SIUE",
    "TNST",
    "TNTC",
    "USI",
    "UTM",
    "WIU",
  ],
  },
  {
    slug: "patriot-league",
    name: "Patriot League",
    teamSlugs: [
    "american-university-eagles",
    "army-black-knights",
    "boston-university-terriers",
    "bucknell-bison",
    "colgate-raiders",
    "holy-cross-crusaders",
    "lafayette-leopards",
    "lehigh-mountain-hawks",
    "loyola-maryland-greyhounds",
    "navy-midshipmen",
  ],
    teamNames: [
    "American University Eagles",
    "Army Black Knights",
    "Boston University Terriers",
    "Bucknell Bison",
    "Colgate Raiders",
    "Holy Cross Crusaders",
    "Lafayette Leopards",
    "Lehigh Mountain Hawks",
    "Loyola Maryland Greyhounds",
    "Navy Midshipmen",
  ],
    teamAbbrevs: [
    "AMER",
    "ARMY",
    "BU",
    "BUCK",
    "COLG",
    "HC",
    "L-MD",
    "LAF",
    "LEH",
    "NAVY",
  ],
  },
  {
    slug: "southeastern-conference",
    name: "Southeastern Conference",
    teamSlugs: [
    "alabama-crimson-tide",
    "arkansas-razorbacks",
    "auburn-tigers",
    "florida-gators",
    "georgia-bulldogs",
    "kentucky-wildcats",
    "lsu-tigers",
    "mississippi-state-bulldogs",
    "missouri-tigers",
    "oklahoma-sooners",
    "ole-miss-rebels",
    "south-carolina-gamecocks",
    "tennessee-volunteers",
    "texas-a-m-aggies",
    "texas-am-aggies",
    "texas-longhorns",
    "vanderbilt-commodores",
  ],
    teamNames: [
    "Alabama Crimson Tide",
    "Arkansas Razorbacks",
    "Auburn Tigers",
    "Florida Gators",
    "Georgia Bulldogs",
    "Kentucky Wildcats",
    "LSU Tigers",
    "Mississippi State Bulldogs",
    "Missouri Tigers",
    "Oklahoma Sooners",
    "Ole Miss Rebels",
    "South Carolina Gamecocks",
    "Tennessee Volunteers",
    "Texas A&M Aggies",
    "Texas Longhorns",
    "Vanderbilt Commodores",
  ],
    teamAbbrevs: [
    "ALA",
    "ARK",
    "AUB",
    "FLA",
    "LSU",
    "MISS",
    "MIZ",
    "MSST",
    "OU",
    "SC",
    "TA&M",
    "TENN",
    "TEX",
    "UGA",
    "UK",
    "VAN",
  ],
  },
] as const;

export const OTHER_NCAA_M_CONFERENCE_SLUG = "other";

function nameToSlug(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function teamMatchesConference(
  team: { name: string; abbreviation: string; slug: string },
  conference: NcaaConferenceMeta,
): boolean {
  const slug = team.slug.trim().toLowerCase();
  const nameSlug = nameToSlug(team.name);
  const abbrev = team.abbreviation.trim().toUpperCase();

  if (conference.teamSlugs.includes(slug)) return true;
  if (nameSlug && conference.teamSlugs.includes(nameSlug)) return true;
  if (conference.teamNames.includes(team.name)) return true;
  if (abbrev && conference.teamAbbrevs.includes(abbrev)) return true;
  return false;
}

export function conferenceForNcaaTeam(
  team: { name: string; abbreviation: string; slug: string },
): string {
  for (const conference of NCAA_M_CONFERENCES) {
    if (teamMatchesConference(team, conference)) {
      return conference.slug;
    }
  }
  return OTHER_NCAA_M_CONFERENCE_SLUG;
}

export function getNcaaConference(slug: string): NcaaConferenceMeta | undefined {
  return NCAA_M_CONFERENCES.find((conference) => conference.slug === slug);
}

export interface NcaaConferenceGroup<T> {
  conference: NcaaConferenceMeta | { slug: string; name: string };
  teams: T[];
}

export function groupNcaaTeamsByConference<T extends { name: string; abbreviation: string; slug: string }>(
  teams: T[],
): NcaaConferenceGroup<T>[] {
  const buckets = new Map<string, T[]>();

  for (const team of teams) {
    const conferenceSlug = conferenceForNcaaTeam(team);
    const existing = buckets.get(conferenceSlug) ?? [];
    existing.push(team);
    buckets.set(conferenceSlug, existing);
  }

  const groups: NcaaConferenceGroup<T>[] = NCAA_M_CONFERENCES.map((conference) => ({
    conference,
    teams: (buckets.get(conference.slug) ?? []).sort((a, b) => a.name.localeCompare(b.name)),
  })).filter((group) => group.teams.length > 0);

  const otherTeams = buckets.get(OTHER_NCAA_M_CONFERENCE_SLUG) ?? [];
  if (otherTeams.length > 0) {
    groups.push({
      conference: { slug: OTHER_NCAA_M_CONFERENCE_SLUG, name: "Other" },
      teams: otherTeams.sort((a, b) => a.name.localeCompare(b.name)),
    });
  }

  return groups;
}
