// Auto-generated from ESPN women's D1 standings.
// Regenerate: python3 scripts/generate-ncaa-w-conferences.py
// Generated: 2026-08-12

import type { CollegeConferenceGroup } from "./college-conference-core";

export interface NcaaWConferenceMeta {
  slug: string;
  name: string;
  teamSlugs: readonly string[];
  teamNames: readonly string[];
  teamAbbrevs: readonly string[];
  espnIds: readonly string[];
}

export type NcaaWConferenceGroup<T> = CollegeConferenceGroup<T>;

const CONFERENCES: readonly NcaaWConferenceMeta[] = [
  {
    slug: "america-east-conference",
    name: "America East Conference",
    teamSlugs: [
    "bing",
    "binghamton",
    "binghamton-bearcats",
    "bry",
    "bryant",
    "bryant-bulldogs",
    "maine",
    "maine-black-bears",
    "me",
    "new-hampshire",
    "new-hampshire-wildcats",
    "njit",
    "njit-highlanders",
    "ualb",
    "ualbany",
    "ualbany-great-danes",
    "umass-lowell",
    "umass-lowell-river-hawks",
    "umbc",
    "umbc-retrievers",
    "uml",
    "unh",
    "uvm",
    "vermont",
    "vermont-catamounts",
  ],
    teamNames: [
    "Binghamton",
    "Binghamton Bearcats",
    "Bryant",
    "Bryant Bulldogs",
    "Maine",
    "Maine Black Bears",
    "NJIT",
    "NJIT Highlanders",
    "New Hampshire",
    "New Hampshire Wildcats",
    "UAlbany",
    "UAlbany Great Danes",
    "UMBC",
    "UMBC Retrievers",
    "UMass Lowell",
    "UMass Lowell River Hawks",
    "Vermont",
    "Vermont Catamounts",
    "binghamton",
    "binghamton-bearcats",
    "bryant",
    "bryant-bulldogs",
    "maine",
    "maine-black-bears",
    "new-hampshire",
    "new-hampshire-wildcats",
    "njit",
    "njit-highlanders",
    "ualbany",
    "ualbany-great-danes",
    "umass-lowell",
    "umass-lowell-river-hawks",
    "umbc",
    "umbc-retrievers",
    "vermont",
    "vermont-catamounts",
  ],
    teamAbbrevs: [
    "BING",
    "BRY",
    "ME",
    "NJIT",
    "UALB",
    "UMBC",
    "UML",
    "UNH",
    "UVM",
    "bing",
    "bry",
    "me",
    "njit",
    "ualb",
    "umbc",
    "uml",
    "unh",
    "uvm",
  ],
    espnIds: [
    "160",
    "2066",
    "2349",
    "2378",
    "261",
    "2803",
    "2885",
    "311",
    "399",
  ],
  },  {
    slug: "american-conference",
    name: "American Conference",
    teamSlugs: [
    "charlotte",
    "charlotte-49ers",
    "clt",
    "east-carolina",
    "east-carolina-pirates",
    "ecu",
    "fau",
    "florida-atlantic-owls",
    "mem",
    "memphis",
    "memphis-tigers",
    "north-texas",
    "north-texas-mean-green",
    "rice",
    "rice-owls",
    "south-florida",
    "south-florida-bulls",
    "tem",
    "temple",
    "temple-owls",
    "tlsa",
    "tulane",
    "tulane-green-wave",
    "tuln",
    "tulsa",
    "tulsa-golden-hurricane",
    "uab",
    "uab-blazers",
    "unt",
    "usf",
    "utsa",
    "utsa-roadrunners",
    "wich",
    "wichita-st",
    "wichita-state-shockers",
  ],
    teamNames: [
    "Charlotte",
    "Charlotte 49ers",
    "East Carolina",
    "East Carolina Pirates",
    "FAU",
    "Florida Atlantic Owls",
    "Memphis",
    "Memphis Tigers",
    "North Texas",
    "North Texas Mean Green",
    "Rice",
    "Rice Owls",
    "South Florida",
    "South Florida Bulls",
    "Temple",
    "Temple Owls",
    "Tulane",
    "Tulane Green Wave",
    "Tulsa",
    "Tulsa Golden Hurricane",
    "UAB",
    "UAB Blazers",
    "UTSA",
    "UTSA Roadrunners",
    "Wichita St",
    "Wichita State Shockers",
    "charlotte",
    "charlotte-49ers",
    "east-carolina",
    "east-carolina-pirates",
    "fau",
    "florida-atlantic-owls",
    "memphis",
    "memphis-tigers",
    "north-texas",
    "north-texas-mean-green",
    "rice",
    "rice-owls",
    "south-florida",
    "south-florida-bulls",
    "temple",
    "temple-owls",
    "tulane",
    "tulane-green-wave",
    "tulsa",
    "tulsa-golden-hurricane",
    "uab",
    "uab-blazers",
    "utsa",
    "utsa-roadrunners",
    "wichita-st",
    "wichita-state-shockers",
  ],
    teamAbbrevs: [
    "CLT",
    "ECU",
    "FAU",
    "MEM",
    "RICE",
    "TEM",
    "TLSA",
    "TULN",
    "UAB",
    "UNT",
    "USF",
    "UTSA",
    "WICH",
    "clt",
    "ecu",
    "fau",
    "mem",
    "rice",
    "tem",
    "tlsa",
    "tuln",
    "uab",
    "unt",
    "usf",
    "utsa",
    "wich",
  ],
    espnIds: [
    "151",
    "202",
    "218",
    "2226",
    "235",
    "242",
    "2429",
    "249",
    "2636",
    "2655",
    "2724",
    "5",
    "58",
  ],
  },  {
    slug: "atlantic-10-conference",
    name: "Atlantic 10 Conference",
    teamSlugs: [
    "dav",
    "davidson",
    "davidson-wildcats",
    "day",
    "dayton",
    "dayton-flyers",
    "duq",
    "duquesne",
    "duquesne-dukes",
    "for",
    "fordham",
    "fordham-rams",
    "g-washington",
    "george-mason",
    "george-mason-patriots",
    "george-washington-revolutionaries",
    "gmu",
    "gw",
    "joes",
    "la-salle",
    "la-salle-explorers",
    "las",
    "loyola-chicago",
    "loyola-chicago-ramblers",
    "luc",
    "rhode-island",
    "rhode-island-rams",
    "rich",
    "richmond",
    "richmond-spiders",
    "saint-josephs",
    "saint-josephs-hawks",
    "saint-louis",
    "saint-louis-billikens",
    "sbu",
    "slu",
    "st-bonaventure",
    "st-bonaventure-bonnies",
    "uri",
    "vcu",
    "vcu-rams",
  ],
    teamNames: [
    "Davidson",
    "Davidson Wildcats",
    "Dayton",
    "Dayton Flyers",
    "Duquesne",
    "Duquesne Dukes",
    "Fordham",
    "Fordham Rams",
    "G Washington",
    "George Mason",
    "George Mason Patriots",
    "George Washington Revolutionaries",
    "La Salle",
    "La Salle Explorers",
    "Loyola Chicago",
    "Loyola Chicago Ramblers",
    "Rhode Island",
    "Rhode Island Rams",
    "Richmond",
    "Richmond Spiders",
    "Saint Joseph's",
    "Saint Joseph's Hawks",
    "Saint Louis",
    "Saint Louis Billikens",
    "St Bonaventure",
    "St. Bonaventure Bonnies",
    "VCU",
    "VCU Rams",
    "davidson",
    "davidson-wildcats",
    "dayton",
    "dayton-flyers",
    "duquesne",
    "duquesne-dukes",
    "fordham",
    "fordham-rams",
    "g-washington",
    "george-mason",
    "george-mason-patriots",
    "george-washington-revolutionaries",
    "la-salle",
    "la-salle-explorers",
    "loyola-chicago",
    "loyola-chicago-ramblers",
    "rhode-island",
    "rhode-island-rams",
    "richmond",
    "richmond-spiders",
    "saint-josephs",
    "saint-josephs-hawks",
    "saint-louis",
    "saint-louis-billikens",
    "st-bonaventure",
    "st-bonaventure-bonnies",
    "vcu",
    "vcu-rams",
  ],
    teamAbbrevs: [
    "DAV",
    "DAY",
    "DUQ",
    "FOR",
    "GMU",
    "GW",
    "JOES",
    "LAS",
    "LUC",
    "RICH",
    "SBU",
    "SLU",
    "URI",
    "VCU",
    "dav",
    "day",
    "duq",
    "for",
    "gmu",
    "gw",
    "joes",
    "las",
    "luc",
    "rich",
    "sbu",
    "slu",
    "uri",
    "vcu",
  ],
    espnIds: [
    "139",
    "179",
    "2166",
    "2168",
    "2184",
    "2230",
    "2244",
    "227",
    "2325",
    "2350",
    "257",
    "2603",
    "2670",
    "45",
  ],
  },  {
    slug: "atlantic-coast-conference",
    name: "Atlantic Coast Conference",
    teamSlugs: [
    "bc",
    "boston-college",
    "boston-college-eagles",
    "cal",
    "california",
    "california-golden-bears",
    "clem",
    "clemson",
    "clemson-tigers",
    "duke",
    "duke-blue-devils",
    "florida-st",
    "florida-state-seminoles",
    "fsu",
    "georgia-tech",
    "georgia-tech-yellow-jackets",
    "gt",
    "lou",
    "louisville",
    "louisville-cardinals",
    "mia",
    "miami",
    "miami-hurricanes",
    "nc-state",
    "nc-state-wolfpack",
    "ncsu",
    "nd",
    "north-carolina",
    "north-carolina-tar-heels",
    "notre-dame",
    "notre-dame-fighting-irish",
    "pitt",
    "pittsburgh-panthers",
    "smu",
    "smu-mustangs",
    "stan",
    "stanford",
    "stanford-cardinal",
    "syr",
    "syracuse",
    "syracuse-orange",
    "unc",
    "uva",
    "virginia",
    "virginia-cavaliers",
    "virginia-tech",
    "virginia-tech-hokies",
    "vt",
    "wake",
    "wake-forest",
    "wake-forest-demon-deacons",
  ],
    teamNames: [
    "Boston College",
    "Boston College Eagles",
    "California",
    "California Golden Bears",
    "Clemson",
    "Clemson Tigers",
    "Duke",
    "Duke Blue Devils",
    "Florida St",
    "Florida State Seminoles",
    "Georgia Tech",
    "Georgia Tech Yellow Jackets",
    "Louisville",
    "Louisville Cardinals",
    "Miami",
    "Miami Hurricanes",
    "NC State",
    "NC State Wolfpack",
    "North Carolina",
    "North Carolina Tar Heels",
    "Notre Dame",
    "Notre Dame Fighting Irish",
    "Pitt",
    "Pittsburgh Panthers",
    "SMU",
    "SMU Mustangs",
    "Stanford",
    "Stanford Cardinal",
    "Syracuse",
    "Syracuse Orange",
    "Virginia",
    "Virginia Cavaliers",
    "Virginia Tech",
    "Virginia Tech Hokies",
    "Wake Forest",
    "Wake Forest Demon Deacons",
    "boston-college",
    "boston-college-eagles",
    "california",
    "california-golden-bears",
    "clemson",
    "clemson-tigers",
    "duke",
    "duke-blue-devils",
    "florida-st",
    "florida-state-seminoles",
    "georgia-tech",
    "georgia-tech-yellow-jackets",
    "louisville",
    "louisville-cardinals",
    "miami",
    "miami-hurricanes",
    "nc-state",
    "nc-state-wolfpack",
    "north-carolina",
    "north-carolina-tar-heels",
    "notre-dame",
    "notre-dame-fighting-irish",
    "pitt",
    "pittsburgh-panthers",
    "smu",
    "smu-mustangs",
    "stanford",
    "stanford-cardinal",
    "syracuse",
    "syracuse-orange",
    "virginia",
    "virginia-cavaliers",
    "virginia-tech",
    "virginia-tech-hokies",
    "wake-forest",
    "wake-forest-demon-deacons",
  ],
    teamAbbrevs: [
    "BC",
    "CAL",
    "CLEM",
    "DUKE",
    "FSU",
    "GT",
    "LOU",
    "MIA",
    "NCSU",
    "ND",
    "PITT",
    "SMU",
    "STAN",
    "SYR",
    "UNC",
    "UVA",
    "VT",
    "WAKE",
    "bc",
    "cal",
    "clem",
    "duke",
    "fsu",
    "gt",
    "lou",
    "mia",
    "ncsu",
    "nd",
    "pitt",
    "smu",
    "stan",
    "syr",
    "unc",
    "uva",
    "vt",
    "wake",
  ],
    espnIds: [
    "103",
    "150",
    "152",
    "153",
    "154",
    "183",
    "221",
    "228",
    "2390",
    "24",
    "25",
    "2567",
    "258",
    "259",
    "52",
    "59",
    "87",
    "97",
  ],
  },  {
    slug: "atlantic-sun-conference",
    name: "Atlantic Sun Conference",
    teamSlugs: [
    "apsu",
    "austin-peay",
    "austin-peay-governors",
    "bell",
    "bellarmine",
    "bellarmine-knights",
    "c-arkansas",
    "cark",
    "central-arkansas-bears",
    "e-kentucky",
    "eastern-kentucky-colonels",
    "eku",
    "fgcu",
    "florida-gulf-coast-eagles",
    "jacksonville",
    "jacksonville-dolphins",
    "jax",
    "lip",
    "lipscomb",
    "lipscomb-bisons",
    "north-alabama",
    "north-alabama-lions",
    "north-florida",
    "north-florida-ospreys",
    "quc",
    "queens",
    "queens-university-royals",
    "stet",
    "stetson",
    "stetson-hatters",
    "una",
    "unf",
    "west-georgia",
    "west-georgia-wolves",
    "wga",
  ],
    teamNames: [
    "Austin Peay",
    "Austin Peay Governors",
    "Bellarmine",
    "Bellarmine Knights",
    "C Arkansas",
    "Central Arkansas Bears",
    "E Kentucky",
    "Eastern Kentucky Colonels",
    "FGCU",
    "Florida Gulf Coast Eagles",
    "Jacksonville",
    "Jacksonville Dolphins",
    "Lipscomb",
    "Lipscomb Bisons",
    "North Alabama",
    "North Alabama Lions",
    "North Florida",
    "North Florida Ospreys",
    "Queens",
    "Queens University Royals",
    "Stetson",
    "Stetson Hatters",
    "West Georgia",
    "West Georgia Wolves",
    "austin-peay",
    "austin-peay-governors",
    "bellarmine",
    "bellarmine-knights",
    "c-arkansas",
    "central-arkansas-bears",
    "e-kentucky",
    "eastern-kentucky-colonels",
    "fgcu",
    "florida-gulf-coast-eagles",
    "jacksonville",
    "jacksonville-dolphins",
    "lipscomb",
    "lipscomb-bisons",
    "north-alabama",
    "north-alabama-lions",
    "north-florida",
    "north-florida-ospreys",
    "queens",
    "queens-university-royals",
    "stetson",
    "stetson-hatters",
    "west-georgia",
    "west-georgia-wolves",
  ],
    teamAbbrevs: [
    "APSU",
    "BELL",
    "CARK",
    "EKU",
    "FGCU",
    "JAX",
    "LIP",
    "QUC",
    "STET",
    "UNA",
    "UNF",
    "WGA",
    "apsu",
    "bell",
    "cark",
    "eku",
    "fgcu",
    "jax",
    "lip",
    "quc",
    "stet",
    "una",
    "unf",
    "wga",
  ],
    espnIds: [
    "2046",
    "2110",
    "2198",
    "2453",
    "2454",
    "2511",
    "2698",
    "288",
    "294",
    "526",
    "56",
    "91",
  ],
  },  {
    slug: "big-12-conference",
    name: "Big 12 Conference",
    teamSlugs: [
    "ariz",
    "arizona",
    "arizona-st",
    "arizona-state-sun-devils",
    "arizona-wildcats",
    "asu",
    "bay",
    "baylor",
    "baylor-bears",
    "byu",
    "byu-cougars",
    "cin",
    "cincinnati",
    "cincinnati-bearcats",
    "colo",
    "colorado",
    "colorado-buffaloes",
    "hou",
    "houston",
    "houston-cougars",
    "iowa-state",
    "iowa-state-cyclones",
    "isu",
    "kansas",
    "kansas-jayhawks",
    "kansas-st",
    "kansas-state-wildcats",
    "ksu",
    "ku",
    "oklahoma-st",
    "oklahoma-state-cowgirls",
    "okst",
    "tcu",
    "tcu-horned-frogs",
    "texas-tech",
    "texas-tech-lady-raiders",
    "ttu",
    "ucf",
    "ucf-knights",
    "utah",
    "utah-utes",
    "west-virginia",
    "west-virginia-mountaineers",
    "wvu",
  ],
    teamNames: [
    "Arizona",
    "Arizona St",
    "Arizona State Sun Devils",
    "Arizona Wildcats",
    "BYU",
    "BYU Cougars",
    "Baylor",
    "Baylor Bears",
    "Cincinnati",
    "Cincinnati Bearcats",
    "Colorado",
    "Colorado Buffaloes",
    "Houston",
    "Houston Cougars",
    "Iowa State",
    "Iowa State Cyclones",
    "Kansas",
    "Kansas Jayhawks",
    "Kansas St",
    "Kansas State Wildcats",
    "Oklahoma St",
    "Oklahoma State Cowgirls",
    "TCU",
    "TCU Horned Frogs",
    "Texas Tech",
    "Texas Tech Lady Raiders",
    "UCF",
    "UCF Knights",
    "Utah",
    "Utah Utes",
    "West Virginia",
    "West Virginia Mountaineers",
    "arizona",
    "arizona-st",
    "arizona-state-sun-devils",
    "arizona-wildcats",
    "baylor",
    "baylor-bears",
    "byu",
    "byu-cougars",
    "cincinnati",
    "cincinnati-bearcats",
    "colorado",
    "colorado-buffaloes",
    "houston",
    "houston-cougars",
    "iowa-state",
    "iowa-state-cyclones",
    "kansas",
    "kansas-jayhawks",
    "kansas-st",
    "kansas-state-wildcats",
    "oklahoma-st",
    "oklahoma-state-cowgirls",
    "tcu",
    "tcu-horned-frogs",
    "texas-tech",
    "texas-tech-lady-raiders",
    "ucf",
    "ucf-knights",
    "utah",
    "utah-utes",
    "west-virginia",
    "west-virginia-mountaineers",
  ],
    teamAbbrevs: [
    "ARIZ",
    "ASU",
    "BAY",
    "BYU",
    "CIN",
    "COLO",
    "HOU",
    "ISU",
    "KSU",
    "KU",
    "OKST",
    "TCU",
    "TTU",
    "UCF",
    "UTAH",
    "WVU",
    "ariz",
    "asu",
    "bay",
    "byu",
    "cin",
    "colo",
    "hou",
    "isu",
    "ksu",
    "ku",
    "okst",
    "tcu",
    "ttu",
    "ucf",
    "utah",
    "wvu",
  ],
    espnIds: [
    "12",
    "197",
    "2116",
    "2132",
    "2305",
    "2306",
    "239",
    "248",
    "252",
    "254",
    "2628",
    "2641",
    "277",
    "38",
    "66",
    "9",
  ],
  },  {
    slug: "big-east-conference",
    name: "Big East Conference",
    teamSlugs: [
    "btlr",
    "butler",
    "butler-bulldogs",
    "conn",
    "crei",
    "creighton",
    "creighton-bluejays",
    "dep",
    "depaul",
    "depaul-blue-demons",
    "georgetown",
    "georgetown-hoyas",
    "gtwn",
    "hall",
    "marq",
    "marquette",
    "marquette-golden-eagles",
    "prov",
    "providence",
    "providence-friars",
    "seton-hall",
    "seton-hall-pirates",
    "sju",
    "st-johns",
    "st-johns-red-storm",
    "uconn",
    "uconn-huskies",
    "vill",
    "villanova",
    "villanova-wildcats",
    "xav",
    "xavier",
    "xavier-musketeers",
  ],
    teamNames: [
    "Butler",
    "Butler Bulldogs",
    "Creighton",
    "Creighton Bluejays",
    "DePaul",
    "DePaul Blue Demons",
    "Georgetown",
    "Georgetown Hoyas",
    "Marquette",
    "Marquette Golden Eagles",
    "Providence",
    "Providence Friars",
    "Seton Hall",
    "Seton Hall Pirates",
    "St John's",
    "St. John's Red Storm",
    "UConn",
    "UConn Huskies",
    "Villanova",
    "Villanova Wildcats",
    "Xavier",
    "Xavier Musketeers",
    "butler",
    "butler-bulldogs",
    "creighton",
    "creighton-bluejays",
    "depaul",
    "depaul-blue-demons",
    "georgetown",
    "georgetown-hoyas",
    "marquette",
    "marquette-golden-eagles",
    "providence",
    "providence-friars",
    "seton-hall",
    "seton-hall-pirates",
    "st-johns",
    "st-johns-red-storm",
    "uconn",
    "uconn-huskies",
    "villanova",
    "villanova-wildcats",
    "xavier",
    "xavier-musketeers",
  ],
    teamAbbrevs: [
    "BTLR",
    "CONN",
    "CREI",
    "DEP",
    "GTWN",
    "HALL",
    "MARQ",
    "PROV",
    "SJU",
    "VILL",
    "XAV",
    "btlr",
    "conn",
    "crei",
    "dep",
    "gtwn",
    "hall",
    "marq",
    "prov",
    "sju",
    "vill",
    "xav",
  ],
    espnIds: [
    "156",
    "2086",
    "222",
    "2507",
    "2550",
    "2599",
    "269",
    "2752",
    "305",
    "41",
    "46",
  ],
  },  {
    slug: "big-sky-conference",
    name: "Big Sky Conference",
    teamSlugs: [
    "e-washington",
    "eastern-washington-eagles",
    "ewu",
    "idaho",
    "idaho-st",
    "idaho-state-bengals",
    "idaho-vandals",
    "idho",
    "idst",
    "mont",
    "montana",
    "montana-lady-griz",
    "montana-st",
    "montana-state-bobcats",
    "mtst",
    "n-arizona",
    "n-colorado",
    "nau",
    "northern-arizona-lumberjacks",
    "northern-colorado-bears",
    "portland-st",
    "portland-state-vikings",
    "prst",
    "sac",
    "sacramento-st",
    "sacramento-state-hornets",
    "unco",
    "web",
    "weber-st",
    "weber-state-wildcats",
  ],
    teamNames: [
    "E Washington",
    "Eastern Washington Eagles",
    "Idaho",
    "Idaho St",
    "Idaho State Bengals",
    "Idaho Vandals",
    "Montana",
    "Montana Lady Griz",
    "Montana St",
    "Montana State Bobcats",
    "N Arizona",
    "N Colorado",
    "Northern Arizona Lumberjacks",
    "Northern Colorado Bears",
    "Portland St",
    "Portland State Vikings",
    "Sacramento St",
    "Sacramento State Hornets",
    "Weber St",
    "Weber State Wildcats",
    "e-washington",
    "eastern-washington-eagles",
    "idaho",
    "idaho-st",
    "idaho-state-bengals",
    "idaho-vandals",
    "montana",
    "montana-lady-griz",
    "montana-st",
    "montana-state-bobcats",
    "n-arizona",
    "n-colorado",
    "northern-arizona-lumberjacks",
    "northern-colorado-bears",
    "portland-st",
    "portland-state-vikings",
    "sacramento-st",
    "sacramento-state-hornets",
    "weber-st",
    "weber-state-wildcats",
  ],
    teamAbbrevs: [
    "EWU",
    "IDHO",
    "IDST",
    "MONT",
    "MTST",
    "NAU",
    "PRST",
    "SAC",
    "UNCO",
    "WEB",
    "ewu",
    "idho",
    "idst",
    "mont",
    "mtst",
    "nau",
    "prst",
    "sac",
    "unco",
    "web",
  ],
    espnIds: [
    "147",
    "149",
    "16",
    "2458",
    "2464",
    "2502",
    "2692",
    "304",
    "331",
    "70",
  ],
  },  {
    slug: "big-south-conference",
    name: "Big South Conference",
    teamSlugs: [
    "charleston-so",
    "charleston-southern-buccaneers",
    "chso",
    "gardner-webb",
    "gardner-webb-runnin-bulldogs",
    "gweb",
    "high-point",
    "high-point-panthers",
    "hpu",
    "long",
    "longwood",
    "longwood-lancers",
    "pres",
    "presbyterian",
    "presbyterian-blue-hose",
    "rad",
    "radford",
    "radford-highlanders",
    "sc-upstate",
    "south-carolina-upstate-spartans",
    "unc-asheville",
    "unc-asheville-bulldogs",
    "unca",
    "upst",
    "win",
    "winthrop",
    "winthrop-eagles",
  ],
    teamNames: [
    "Charleston So",
    "Charleston Southern Buccaneers",
    "Gardner-Webb",
    "Gardner-Webb Runnin' Bulldogs",
    "High Point",
    "High Point Panthers",
    "Longwood",
    "Longwood Lancers",
    "Presbyterian",
    "Presbyterian Blue Hose",
    "Radford",
    "Radford Highlanders",
    "SC Upstate",
    "South Carolina Upstate Spartans",
    "UNC Asheville",
    "UNC Asheville Bulldogs",
    "Winthrop",
    "Winthrop Eagles",
    "charleston-so",
    "charleston-southern-buccaneers",
    "gardner-webb",
    "gardner-webb-runnin-bulldogs",
    "high-point",
    "high-point-panthers",
    "longwood",
    "longwood-lancers",
    "presbyterian",
    "presbyterian-blue-hose",
    "radford",
    "radford-highlanders",
    "sc-upstate",
    "south-carolina-upstate-spartans",
    "unc-asheville",
    "unc-asheville-bulldogs",
    "winthrop",
    "winthrop-eagles",
  ],
    teamAbbrevs: [
    "CHSO",
    "GWEB",
    "HPU",
    "LONG",
    "PRES",
    "RAD",
    "UNCA",
    "UPST",
    "WIN",
    "chso",
    "gweb",
    "hpu",
    "long",
    "pres",
    "rad",
    "unca",
    "upst",
    "win",
  ],
    espnIds: [
    "2127",
    "2241",
    "2272",
    "2344",
    "2427",
    "2506",
    "2515",
    "2737",
    "2908",
  ],
  },  {
    slug: "big-ten-conference",
    name: "Big Ten Conference",
    teamSlugs: [
    "ill",
    "illinois",
    "illinois-fighting-illini",
    "indiana",
    "indiana-hoosiers",
    "iowa",
    "iowa-hawkeyes",
    "iu",
    "maryland",
    "maryland-terrapins",
    "md",
    "mich",
    "michigan",
    "michigan-st",
    "michigan-state-spartans",
    "michigan-wolverines",
    "minn",
    "minnesota",
    "minnesota-golden-gophers",
    "msu",
    "neb",
    "nebraska",
    "nebraska-cornhuskers",
    "northwestern",
    "northwestern-wildcats",
    "nu",
    "ohio-state",
    "ohio-state-buckeyes",
    "ore",
    "oregon",
    "oregon-ducks",
    "osu",
    "penn-state",
    "penn-state-lady-lions",
    "psu",
    "pur",
    "purdue",
    "purdue-boilermakers",
    "rutg",
    "rutgers",
    "rutgers-scarlet-knights",
    "ucla",
    "ucla-bruins",
    "usc",
    "usc-trojans",
    "wash",
    "washington",
    "washington-huskies",
    "wis",
    "wisconsin",
    "wisconsin-badgers",
  ],
    teamNames: [
    "Illinois",
    "Illinois Fighting Illini",
    "Indiana",
    "Indiana Hoosiers",
    "Iowa",
    "Iowa Hawkeyes",
    "Maryland",
    "Maryland Terrapins",
    "Michigan",
    "Michigan St",
    "Michigan State Spartans",
    "Michigan Wolverines",
    "Minnesota",
    "Minnesota Golden Gophers",
    "Nebraska",
    "Nebraska Cornhuskers",
    "Northwestern",
    "Northwestern Wildcats",
    "Ohio State",
    "Ohio State Buckeyes",
    "Oregon",
    "Oregon Ducks",
    "Penn State",
    "Penn State Lady Lions",
    "Purdue",
    "Purdue Boilermakers",
    "Rutgers",
    "Rutgers Scarlet Knights",
    "UCLA",
    "UCLA Bruins",
    "USC",
    "USC Trojans",
    "Washington",
    "Washington Huskies",
    "Wisconsin",
    "Wisconsin Badgers",
    "illinois",
    "illinois-fighting-illini",
    "indiana",
    "indiana-hoosiers",
    "iowa",
    "iowa-hawkeyes",
    "maryland",
    "maryland-terrapins",
    "michigan",
    "michigan-st",
    "michigan-state-spartans",
    "michigan-wolverines",
    "minnesota",
    "minnesota-golden-gophers",
    "nebraska",
    "nebraska-cornhuskers",
    "northwestern",
    "northwestern-wildcats",
    "ohio-state",
    "ohio-state-buckeyes",
    "oregon",
    "oregon-ducks",
    "penn-state",
    "penn-state-lady-lions",
    "purdue",
    "purdue-boilermakers",
    "rutgers",
    "rutgers-scarlet-knights",
    "ucla",
    "ucla-bruins",
    "usc",
    "usc-trojans",
    "washington",
    "washington-huskies",
    "wisconsin",
    "wisconsin-badgers",
  ],
    teamAbbrevs: [
    "ILL",
    "IOWA",
    "IU",
    "MD",
    "MICH",
    "MINN",
    "MSU",
    "NEB",
    "NU",
    "ORE",
    "OSU",
    "PSU",
    "PUR",
    "RUTG",
    "UCLA",
    "USC",
    "WASH",
    "WIS",
    "ill",
    "iowa",
    "iu",
    "md",
    "mich",
    "minn",
    "msu",
    "neb",
    "nu",
    "ore",
    "osu",
    "psu",
    "pur",
    "rutg",
    "ucla",
    "usc",
    "wash",
    "wis",
  ],
    espnIds: [
    "120",
    "127",
    "130",
    "135",
    "158",
    "164",
    "194",
    "213",
    "2294",
    "2483",
    "2509",
    "26",
    "264",
    "275",
    "30",
    "356",
    "77",
    "84",
  ],
  },  {
    slug: "big-west-conference",
    name: "Big West Conference",
    teamSlugs: [
    "bakersfield",
    "cal-poly",
    "cal-poly-mustangs",
    "cal-state-bakersfield-roadrunners",
    "cal-state-fullerton-titans",
    "cal-state-northridge-matadors",
    "cp",
    "csu-northridge",
    "csub",
    "csuf",
    "csun",
    "fullerton",
    "haw",
    "hawaii",
    "hawaii-rainbow-warriors",
    "lbsu",
    "long-beach-st",
    "long-beach-state-beach",
    "santa-barbara",
    "uc-davis",
    "uc-davis-aggies",
    "uc-irvine",
    "uc-irvine-anteaters",
    "uc-riverside",
    "uc-riverside-highlanders",
    "uc-san-diego",
    "uc-san-diego-tritons",
    "uc-santa-barbara-gauchos",
    "ucd",
    "uci",
    "ucr",
    "ucsb",
    "ucsd",
  ],
    teamNames: [
    "Bakersfield",
    "CSU Northridge",
    "Cal Poly",
    "Cal Poly Mustangs",
    "Cal State Bakersfield Roadrunners",
    "Cal State Fullerton Titans",
    "Cal State Northridge Matadors",
    "Fullerton",
    "Hawai'i",
    "Hawai'i Rainbow Warriors",
    "Long Beach St",
    "Long Beach State Beach",
    "Santa Barbara",
    "UC Davis",
    "UC Davis Aggies",
    "UC Irvine",
    "UC Irvine Anteaters",
    "UC Riverside",
    "UC Riverside Highlanders",
    "UC San Diego",
    "UC San Diego Tritons",
    "UC Santa Barbara Gauchos",
    "bakersfield",
    "cal-poly",
    "cal-poly-mustangs",
    "cal-state-bakersfield-roadrunners",
    "cal-state-fullerton-titans",
    "cal-state-northridge-matadors",
    "csu-northridge",
    "fullerton",
    "hawaii",
    "hawaii-rainbow-warriors",
    "long-beach-st",
    "long-beach-state-beach",
    "santa-barbara",
    "uc-davis",
    "uc-davis-aggies",
    "uc-irvine",
    "uc-irvine-anteaters",
    "uc-riverside",
    "uc-riverside-highlanders",
    "uc-san-diego",
    "uc-san-diego-tritons",
    "uc-santa-barbara-gauchos",
  ],
    teamAbbrevs: [
    "CP",
    "CSUB",
    "CSUF",
    "CSUN",
    "HAW",
    "LBSU",
    "UCD",
    "UCI",
    "UCR",
    "UCSB",
    "UCSD",
    "cp",
    "csub",
    "csuf",
    "csun",
    "haw",
    "lbsu",
    "ucd",
    "uci",
    "ucr",
    "ucsb",
    "ucsd",
  ],
    espnIds: [
    "13",
    "2239",
    "2463",
    "2540",
    "27",
    "28",
    "2934",
    "299",
    "300",
    "302",
    "62",
  ],
  },  {
    slug: "coastal-athletic-association",
    name: "Coastal Athletic Association",
    teamSlugs: [
    "cam",
    "campbell",
    "campbell-fighting-camels",
    "charleston",
    "charleston-cougars",
    "cofc",
    "drex",
    "drexel",
    "drexel-dragons",
    "elon",
    "elon-phoenix",
    "hamp",
    "hampton",
    "hampton-lady-pirates",
    "hof",
    "hofstra",
    "hofstra-pride",
    "monm",
    "monmouth",
    "monmouth-hawks",
    "nc-a-t",
    "ncat",
    "ne",
    "north-carolina-a-t-aggies",
    "northeastern",
    "northeastern-huskies",
    "stbk",
    "stony-brook",
    "stony-brook-seawolves",
    "tow",
    "towson",
    "towson-tigers",
    "unc-wilmington",
    "unc-wilmington-seahawks",
    "uncw",
    "w-m",
    "william-mary",
    "william-mary-tribe",
  ],
    teamNames: [
    "Campbell",
    "Campbell Fighting Camels",
    "Charleston",
    "Charleston Cougars",
    "Drexel",
    "Drexel Dragons",
    "Elon",
    "Elon Phoenix",
    "Hampton",
    "Hampton Lady Pirates",
    "Hofstra",
    "Hofstra Pride",
    "Monmouth",
    "Monmouth Hawks",
    "NC A&T",
    "North Carolina A&T Aggies",
    "Northeastern",
    "Northeastern Huskies",
    "Stony Brook",
    "Stony Brook Seawolves",
    "Towson",
    "Towson Tigers",
    "UNC Wilmington",
    "UNC Wilmington Seahawks",
    "William & Mary",
    "William & Mary Tribe",
    "campbell",
    "campbell-fighting-camels",
    "charleston",
    "charleston-cougars",
    "drexel",
    "drexel-dragons",
    "elon",
    "elon-phoenix",
    "hampton",
    "hampton-lady-pirates",
    "hofstra",
    "hofstra-pride",
    "monmouth",
    "monmouth-hawks",
    "nc-a-t",
    "north-carolina-a-t-aggies",
    "northeastern",
    "northeastern-huskies",
    "stony-brook",
    "stony-brook-seawolves",
    "towson",
    "towson-tigers",
    "unc-wilmington",
    "unc-wilmington-seahawks",
    "william-mary",
    "william-mary-tribe",
  ],
    teamAbbrevs: [
    "CAM",
    "COFC",
    "DREX",
    "ELON",
    "HAMP",
    "HOF",
    "MONM",
    "NCAT",
    "NE",
    "STBK",
    "TOW",
    "UNCW",
    "W&M",
    "cam",
    "cofc",
    "drex",
    "elon",
    "hamp",
    "hof",
    "monm",
    "ncat",
    "ne",
    "stbk",
    "tow",
    "uncw",
    "w-m",
  ],
    espnIds: [
    "111",
    "119",
    "2097",
    "2182",
    "2210",
    "2261",
    "2275",
    "232",
    "2405",
    "2448",
    "2619",
    "2729",
    "350",
  ],
  },  {
    slug: "conference-usa",
    name: "Conference USA",
    teamSlugs: [
    "del",
    "delaware",
    "delaware-blue-hens",
    "fiu",
    "florida-international-panthers",
    "jacksonville-state-gamecocks",
    "jax-state",
    "jxst",
    "kenn",
    "kennesaw-st",
    "kennesaw-state-owls",
    "lib",
    "liberty",
    "liberty-flames",
    "louisiana-tech",
    "louisiana-tech-lady-techsters",
    "lt",
    "middle-tennessee-blue-raiders",
    "missouri-st",
    "missouri-state-lady-bears",
    "most",
    "mtsu",
    "new-mexico-st",
    "new-mexico-state-aggies",
    "nmsu",
    "sam-houston",
    "sam-houston-bearkats",
    "shsu",
    "utep",
    "utep-miners",
    "western-kentucky-lady-toppers",
    "western-ky",
    "wku",
  ],
    teamNames: [
    "Delaware",
    "Delaware Blue Hens",
    "FIU",
    "Florida International Panthers",
    "Jacksonville State Gamecocks",
    "Jax State",
    "Kennesaw St",
    "Kennesaw State Owls",
    "Liberty",
    "Liberty Flames",
    "Louisiana Tech",
    "Louisiana Tech Lady Techsters",
    "MTSU",
    "Middle Tennessee Blue Raiders",
    "Missouri St",
    "Missouri State Lady Bears",
    "New Mexico St",
    "New Mexico State Aggies",
    "Sam Houston",
    "Sam Houston Bearkats",
    "UTEP",
    "UTEP Miners",
    "Western KY",
    "Western Kentucky Lady Toppers",
    "delaware",
    "delaware-blue-hens",
    "fiu",
    "florida-international-panthers",
    "jacksonville-state-gamecocks",
    "jax-state",
    "kennesaw-st",
    "kennesaw-state-owls",
    "liberty",
    "liberty-flames",
    "louisiana-tech",
    "louisiana-tech-lady-techsters",
    "middle-tennessee-blue-raiders",
    "missouri-st",
    "missouri-state-lady-bears",
    "mtsu",
    "new-mexico-st",
    "new-mexico-state-aggies",
    "sam-houston",
    "sam-houston-bearkats",
    "utep",
    "utep-miners",
    "western-kentucky-lady-toppers",
    "western-ky",
  ],
    teamAbbrevs: [
    "DEL",
    "FIU",
    "JXST",
    "KENN",
    "LIB",
    "LT",
    "MOST",
    "MTSU",
    "NMSU",
    "SHSU",
    "UTEP",
    "WKU",
    "del",
    "fiu",
    "jxst",
    "kenn",
    "lib",
    "lt",
    "most",
    "mtsu",
    "nmsu",
    "shsu",
    "utep",
    "wku",
  ],
    espnIds: [
    "166",
    "2229",
    "2335",
    "2348",
    "2393",
    "2534",
    "2623",
    "2638",
    "338",
    "48",
    "55",
    "98",
  ],
  },  {
    slug: "horizon-league",
    name: "Horizon League",
    teamSlugs: [
    "cle",
    "cleveland-st",
    "cleveland-state-vikings",
    "detm",
    "detroit-mercy",
    "detroit-mercy-titans",
    "gb",
    "green-bay",
    "green-bay-phoenix",
    "iu-indianapolis-jaguars",
    "iu-indy",
    "iuin",
    "milw",
    "milwaukee",
    "milwaukee-panthers",
    "n-kentucky",
    "nku",
    "northern-kentucky-norse",
    "oak",
    "oakland",
    "oakland-golden-grizzlies",
    "pfw",
    "purdue-fort-wayne-mastodons",
    "purdue-fw",
    "rmu",
    "robert-morris",
    "robert-morris-colonials",
    "wright-st",
    "wright-state-raiders",
    "wrst",
    "youngstown-st",
    "youngstown-state-penguins",
    "ysu",
  ],
    teamNames: [
    "Cleveland St",
    "Cleveland State Vikings",
    "Detroit Mercy",
    "Detroit Mercy Titans",
    "Green Bay",
    "Green Bay Phoenix",
    "IU Indianapolis Jaguars",
    "IU Indy",
    "Milwaukee",
    "Milwaukee Panthers",
    "N Kentucky",
    "Northern Kentucky Norse",
    "Oakland",
    "Oakland Golden Grizzlies",
    "Purdue FW",
    "Purdue Fort Wayne Mastodons",
    "Robert Morris",
    "Robert Morris Colonials",
    "Wright St",
    "Wright State Raiders",
    "Youngstown St",
    "Youngstown State Penguins",
    "cleveland-st",
    "cleveland-state-vikings",
    "detroit-mercy",
    "detroit-mercy-titans",
    "green-bay",
    "green-bay-phoenix",
    "iu-indianapolis-jaguars",
    "iu-indy",
    "milwaukee",
    "milwaukee-panthers",
    "n-kentucky",
    "northern-kentucky-norse",
    "oakland",
    "oakland-golden-grizzlies",
    "purdue-fort-wayne-mastodons",
    "purdue-fw",
    "robert-morris",
    "robert-morris-colonials",
    "wright-st",
    "wright-state-raiders",
    "youngstown-st",
    "youngstown-state-penguins",
  ],
    teamAbbrevs: [
    "CLE",
    "DETM",
    "GB",
    "IUIN",
    "MILW",
    "NKU",
    "OAK",
    "PFW",
    "RMU",
    "WRST",
    "YSU",
    "cle",
    "detm",
    "gb",
    "iuin",
    "milw",
    "nku",
    "oak",
    "pfw",
    "rmu",
    "wrst",
    "ysu",
  ],
    espnIds: [
    "2174",
    "2473",
    "2523",
    "270",
    "2739",
    "2750",
    "2754",
    "2870",
    "325",
    "85",
    "94",
  ],
  },  {
    slug: "ivy-league",
    name: "Ivy League",
    teamSlugs: [
    "brown",
    "brown-bears",
    "brwn",
    "colu",
    "columbia",
    "columbia-lions",
    "cor",
    "cornell",
    "cornell-big-red",
    "dart",
    "dartmouth",
    "dartmouth-big-green",
    "harv",
    "harvard",
    "harvard-crimson",
    "penn",
    "pennsylvania-quakers",
    "prin",
    "princeton",
    "princeton-tigers",
    "yale",
    "yale-bulldogs",
  ],
    teamNames: [
    "Brown",
    "Brown Bears",
    "Columbia",
    "Columbia Lions",
    "Cornell",
    "Cornell Big Red",
    "Dartmouth",
    "Dartmouth Big Green",
    "Harvard",
    "Harvard Crimson",
    "Penn",
    "Pennsylvania Quakers",
    "Princeton",
    "Princeton Tigers",
    "Yale",
    "Yale Bulldogs",
    "brown",
    "brown-bears",
    "columbia",
    "columbia-lions",
    "cornell",
    "cornell-big-red",
    "dartmouth",
    "dartmouth-big-green",
    "harvard",
    "harvard-crimson",
    "penn",
    "pennsylvania-quakers",
    "princeton",
    "princeton-tigers",
    "yale",
    "yale-bulldogs",
  ],
    teamAbbrevs: [
    "BRWN",
    "COLU",
    "COR",
    "DART",
    "HARV",
    "PENN",
    "PRIN",
    "YALE",
    "brwn",
    "colu",
    "cor",
    "dart",
    "harv",
    "penn",
    "prin",
    "yale",
  ],
    espnIds: [
    "108",
    "159",
    "163",
    "171",
    "172",
    "219",
    "225",
    "43",
  ],
  },  {
    slug: "metro-conference",
    name: "Metro Conference",
    teamSlugs: [
    "can",
    "canisius",
    "canisius-golden-griffins",
    "fair",
    "fairfield",
    "fairfield-stags",
    "iona",
    "iona-gaels",
    "man",
    "manhattan",
    "manhattan-jaspers",
    "marist",
    "marist-red-foxes",
    "merrimack",
    "merrimack-warriors",
    "mount-st-marys",
    "mount-st-marys-mountaineers",
    "mrmk",
    "mrst",
    "msm",
    "nia",
    "niagara",
    "niagara-purple-eagles",
    "quin",
    "quinnipiac",
    "quinnipiac-bobcats",
    "rid",
    "rider",
    "rider-broncs",
    "sacred-heart",
    "sacred-heart-pioneers",
    "saint-peters",
    "saint-peters-peacocks",
    "shu",
    "sie",
    "siena",
    "siena-saints",
    "spu",
  ],
    teamNames: [
    "Canisius",
    "Canisius Golden Griffins",
    "Fairfield",
    "Fairfield Stags",
    "Iona",
    "Iona Gaels",
    "Manhattan",
    "Manhattan Jaspers",
    "Marist",
    "Marist Red Foxes",
    "Merrimack",
    "Merrimack Warriors",
    "Mount St Marys",
    "Mount St. Mary's Mountaineers",
    "Niagara",
    "Niagara Purple Eagles",
    "Quinnipiac",
    "Quinnipiac Bobcats",
    "Rider",
    "Rider Broncs",
    "Sacred Heart",
    "Sacred Heart Pioneers",
    "Saint Peter's",
    "Saint Peter's Peacocks",
    "Siena",
    "Siena Saints",
    "canisius",
    "canisius-golden-griffins",
    "fairfield",
    "fairfield-stags",
    "iona",
    "iona-gaels",
    "manhattan",
    "manhattan-jaspers",
    "marist",
    "marist-red-foxes",
    "merrimack",
    "merrimack-warriors",
    "mount-st-marys",
    "mount-st-marys-mountaineers",
    "niagara",
    "niagara-purple-eagles",
    "quinnipiac",
    "quinnipiac-bobcats",
    "rider",
    "rider-broncs",
    "sacred-heart",
    "sacred-heart-pioneers",
    "saint-peters",
    "saint-peters-peacocks",
    "siena",
    "siena-saints",
  ],
    teamAbbrevs: [
    "CAN",
    "FAIR",
    "IONA",
    "MAN",
    "MRMK",
    "MRST",
    "MSM",
    "NIA",
    "QUIN",
    "RID",
    "SHU",
    "SIE",
    "SPU",
    "can",
    "fair",
    "iona",
    "man",
    "mrmk",
    "mrst",
    "msm",
    "nia",
    "quin",
    "rid",
    "shu",
    "sie",
    "spu",
  ],
    espnIds: [
    "116",
    "2099",
    "2217",
    "2363",
    "2368",
    "2514",
    "2520",
    "2529",
    "2561",
    "2612",
    "2771",
    "314",
    "315",
  ],
  },  {
    slug: "mid-american-conference",
    name: "Mid-American Conference",
    teamSlugs: [
    "akr",
    "akron",
    "akron-zips",
    "ball",
    "ball-state",
    "ball-state-cardinals",
    "bgsu",
    "bowling-green",
    "bowling-green-falcons",
    "buf",
    "buffalo",
    "buffalo-bulls",
    "c-michigan",
    "central-michigan-chippewas",
    "cmu",
    "e-michigan",
    "eastern-michigan-eagles",
    "emu",
    "kent",
    "kent-state",
    "kent-state-golden-flashes",
    "m-oh",
    "mass",
    "massachusetts-minutewomen",
    "miami-oh",
    "miami-oh-redhawks",
    "n-illinois",
    "niu",
    "northern-illinois-huskies",
    "ohio",
    "ohio-bobcats",
    "tol",
    "toledo",
    "toledo-rockets",
    "umass",
    "w-michigan",
    "western-michigan-broncos",
    "wmu",
  ],
    teamNames: [
    "Akron",
    "Akron Zips",
    "Ball State",
    "Ball State Cardinals",
    "Bowling Green",
    "Bowling Green Falcons",
    "Buffalo",
    "Buffalo Bulls",
    "C Michigan",
    "Central Michigan Chippewas",
    "E Michigan",
    "Eastern Michigan Eagles",
    "Kent State",
    "Kent State Golden Flashes",
    "Massachusetts Minutewomen",
    "Miami (OH) RedHawks",
    "Miami OH",
    "N Illinois",
    "Northern Illinois Huskies",
    "Ohio",
    "Ohio Bobcats",
    "Toledo",
    "Toledo Rockets",
    "UMass",
    "W Michigan",
    "Western Michigan Broncos",
    "akron",
    "akron-zips",
    "ball-state",
    "ball-state-cardinals",
    "bowling-green",
    "bowling-green-falcons",
    "buffalo",
    "buffalo-bulls",
    "c-michigan",
    "central-michigan-chippewas",
    "e-michigan",
    "eastern-michigan-eagles",
    "kent-state",
    "kent-state-golden-flashes",
    "massachusetts-minutewomen",
    "miami-oh",
    "miami-oh-redhawks",
    "n-illinois",
    "northern-illinois-huskies",
    "ohio",
    "ohio-bobcats",
    "toledo",
    "toledo-rockets",
    "umass",
    "w-michigan",
    "western-michigan-broncos",
  ],
    teamAbbrevs: [
    "AKR",
    "BALL",
    "BGSU",
    "BUF",
    "CMU",
    "EMU",
    "KENT",
    "M-OH",
    "MASS",
    "NIU",
    "OHIO",
    "TOL",
    "WMU",
    "akr",
    "ball",
    "bgsu",
    "buf",
    "cmu",
    "emu",
    "kent",
    "m-oh",
    "mass",
    "niu",
    "ohio",
    "tol",
    "wmu",
  ],
    espnIds: [
    "113",
    "189",
    "193",
    "195",
    "2006",
    "2050",
    "2084",
    "2117",
    "2199",
    "2309",
    "2459",
    "2649",
    "2711",
  ],
  },  {
    slug: "mid-eastern-athletic-conference",
    name: "Mid-Eastern Athletic Conference",
    teamSlugs: [
    "copp",
    "coppin-st",
    "coppin-state-eagles",
    "delaware-st",
    "delaware-state-hornets",
    "dsu",
    "how",
    "howard",
    "howard-bison",
    "maryland-eastern-shore-hawks",
    "md-eastern",
    "morg",
    "morgan-st",
    "morgan-state-lady-bears",
    "nc-central",
    "nccu",
    "norf",
    "norfolk-st",
    "norfolk-state-spartans",
    "north-carolina-central-eagles",
    "sc-state",
    "scst",
    "south-carolina-state-lady-bulldogs",
    "umes",
  ],
    teamNames: [
    "Coppin St",
    "Coppin State Eagles",
    "Delaware St",
    "Delaware State Hornets",
    "Howard",
    "Howard Bison",
    "MD Eastern",
    "Maryland Eastern Shore Hawks",
    "Morgan St",
    "Morgan State Lady Bears",
    "NC Central",
    "Norfolk St",
    "Norfolk State Spartans",
    "North Carolina Central Eagles",
    "SC State",
    "South Carolina State Lady Bulldogs",
    "coppin-st",
    "coppin-state-eagles",
    "delaware-st",
    "delaware-state-hornets",
    "howard",
    "howard-bison",
    "maryland-eastern-shore-hawks",
    "md-eastern",
    "morgan-st",
    "morgan-state-lady-bears",
    "nc-central",
    "norfolk-st",
    "norfolk-state-spartans",
    "north-carolina-central-eagles",
    "sc-state",
    "south-carolina-state-lady-bulldogs",
  ],
    teamAbbrevs: [
    "COPP",
    "DSU",
    "HOW",
    "MORG",
    "NCCU",
    "NORF",
    "SCST",
    "UMES",
    "copp",
    "dsu",
    "how",
    "morg",
    "nccu",
    "norf",
    "scst",
    "umes",
  ],
    espnIds: [
    "2154",
    "2169",
    "2379",
    "2415",
    "2428",
    "2450",
    "2569",
    "47",
  ],
  },  {
    slug: "missouri-valley-conference",
    name: "Missouri Valley Conference",
    teamSlugs: [
    "bel",
    "belmont",
    "belmont-bruins",
    "brad",
    "bradley",
    "bradley-braves",
    "drake",
    "drake-bulldogs",
    "drke",
    "evan",
    "evansville",
    "evansville-purple-aces",
    "illinois-st",
    "illinois-state-redbirds",
    "ilst",
    "indiana-st",
    "indiana-state-sycamores",
    "inst",
    "mur",
    "murray-st",
    "murray-state-racers",
    "northern-iowa",
    "northern-iowa-panthers",
    "s-illinois",
    "siu",
    "southern-illinois-salukis",
    "uic",
    "uic-flames",
    "uni",
    "val",
    "valparaiso",
    "valparaiso-beacons",
  ],
    teamNames: [
    "Belmont",
    "Belmont Bruins",
    "Bradley",
    "Bradley Braves",
    "Drake",
    "Drake Bulldogs",
    "Evansville",
    "Evansville Purple Aces",
    "Illinois St",
    "Illinois State Redbirds",
    "Indiana St",
    "Indiana State Sycamores",
    "Murray St",
    "Murray State Racers",
    "Northern Iowa",
    "Northern Iowa Panthers",
    "S Illinois",
    "Southern Illinois Salukis",
    "UIC",
    "UIC Flames",
    "Valparaiso",
    "Valparaiso Beacons",
    "belmont",
    "belmont-bruins",
    "bradley",
    "bradley-braves",
    "drake",
    "drake-bulldogs",
    "evansville",
    "evansville-purple-aces",
    "illinois-st",
    "illinois-state-redbirds",
    "indiana-st",
    "indiana-state-sycamores",
    "murray-st",
    "murray-state-racers",
    "northern-iowa",
    "northern-iowa-panthers",
    "s-illinois",
    "southern-illinois-salukis",
    "uic",
    "uic-flames",
    "valparaiso",
    "valparaiso-beacons",
  ],
    teamAbbrevs: [
    "BEL",
    "BRAD",
    "DRKE",
    "EVAN",
    "ILST",
    "INST",
    "MUR",
    "SIU",
    "UIC",
    "UNI",
    "VAL",
    "bel",
    "brad",
    "drke",
    "evan",
    "ilst",
    "inst",
    "mur",
    "siu",
    "uic",
    "uni",
    "val",
  ],
    espnIds: [
    "2057",
    "2181",
    "2287",
    "2460",
    "2674",
    "282",
    "339",
    "71",
    "79",
    "82",
    "93",
  ],
  },  {
    slug: "mountain-west-conference",
    name: "Mountain West Conference",
    teamSlugs: [
    "af",
    "air-force",
    "air-force-falcons",
    "bois",
    "boise-st",
    "boise-state-broncos",
    "colorado-st",
    "colorado-state-rams",
    "csu",
    "fres",
    "fresno-st",
    "fresno-state-bulldogs",
    "gcu",
    "grand-canyon",
    "grand-canyon-lopes",
    "nev",
    "nevada",
    "nevada-wolf-pack",
    "new-mexico",
    "new-mexico-lobos",
    "san-diego-st",
    "san-diego-state-aztecs",
    "san-jos-st",
    "san-jos-state-spartans",
    "sdsu",
    "sjsu",
    "unlv",
    "unlv-lady-rebels",
    "unm",
    "usu",
    "utah-state",
    "utah-state-aggies",
    "wyo",
    "wyoming",
    "wyoming-cowgirls",
  ],
    teamNames: [
    "Air Force",
    "Air Force Falcons",
    "Boise St",
    "Boise State Broncos",
    "Colorado St",
    "Colorado State Rams",
    "Fresno St",
    "Fresno State Bulldogs",
    "Grand Canyon",
    "Grand Canyon Lopes",
    "Nevada",
    "Nevada Wolf Pack",
    "New Mexico",
    "New Mexico Lobos",
    "San Diego St",
    "San Diego State Aztecs",
    "San Jos\u00e9 St",
    "San Jos\u00e9 State Spartans",
    "UNLV",
    "UNLV Lady Rebels",
    "Utah State",
    "Utah State Aggies",
    "Wyoming",
    "Wyoming Cowgirls",
    "air-force",
    "air-force-falcons",
    "boise-st",
    "boise-state-broncos",
    "colorado-st",
    "colorado-state-rams",
    "fresno-st",
    "fresno-state-bulldogs",
    "grand-canyon",
    "grand-canyon-lopes",
    "nevada",
    "nevada-wolf-pack",
    "new-mexico",
    "new-mexico-lobos",
    "san-diego-st",
    "san-diego-state-aztecs",
    "san-jos-st",
    "san-jos-state-spartans",
    "unlv",
    "unlv-lady-rebels",
    "utah-state",
    "utah-state-aggies",
    "wyoming",
    "wyoming-cowgirls",
  ],
    teamAbbrevs: [
    "AF",
    "BOIS",
    "CSU",
    "FRES",
    "GCU",
    "NEV",
    "SDSU",
    "SJSU",
    "UNLV",
    "UNM",
    "USU",
    "WYO",
    "af",
    "bois",
    "csu",
    "fres",
    "gcu",
    "nev",
    "sdsu",
    "sjsu",
    "unlv",
    "unm",
    "usu",
    "wyo",
  ],
    espnIds: [
    "167",
    "2005",
    "21",
    "2253",
    "23",
    "2439",
    "2440",
    "2751",
    "278",
    "328",
    "36",
    "68",
  ],
  },  {
    slug: "northeast-conference",
    name: "Northeast Conference",
    teamSlugs: [
    "c-connecticut",
    "ccsu",
    "central-connecticut-blue-devils",
    "chicago-st",
    "chicago-state-cougars",
    "chst",
    "fairleigh-dickinson-knights",
    "fdu",
    "le-moyne",
    "le-moyne-dolphins",
    "lem",
    "liu",
    "long-island",
    "long-island-university-sharks",
    "merc",
    "mercyhurst",
    "mercyhurst-lakers",
    "new-haven",
    "new-haven-chargers",
    "nhvn",
    "saint-francis",
    "saint-francis-red-wolves",
    "sfpa",
    "sto",
    "stonehill",
    "stonehill-skyhawks",
    "wag",
    "wagner",
    "wagner-seahawks",
  ],
    teamNames: [
    "C Connecticut",
    "Central Connecticut Blue Devils",
    "Chicago St",
    "Chicago State Cougars",
    "FDU",
    "Fairleigh Dickinson Knights",
    "Le Moyne",
    "Le Moyne Dolphins",
    "Long Island",
    "Long Island University Sharks",
    "Mercyhurst",
    "Mercyhurst Lakers",
    "New Haven",
    "New Haven Chargers",
    "Saint Francis",
    "Saint Francis Red Wolves",
    "Stonehill",
    "Stonehill Skyhawks",
    "Wagner",
    "Wagner Seahawks",
    "c-connecticut",
    "central-connecticut-blue-devils",
    "chicago-st",
    "chicago-state-cougars",
    "fairleigh-dickinson-knights",
    "fdu",
    "le-moyne",
    "le-moyne-dolphins",
    "long-island",
    "long-island-university-sharks",
    "mercyhurst",
    "mercyhurst-lakers",
    "new-haven",
    "new-haven-chargers",
    "saint-francis",
    "saint-francis-red-wolves",
    "stonehill",
    "stonehill-skyhawks",
    "wagner",
    "wagner-seahawks",
  ],
    teamAbbrevs: [
    "CCSU",
    "CHST",
    "FDU",
    "LEM",
    "LIU",
    "MERC",
    "NHVN",
    "SFPA",
    "STO",
    "WAG",
    "ccsu",
    "chst",
    "fdu",
    "lem",
    "liu",
    "merc",
    "nhvn",
    "sfpa",
    "sto",
    "wag",
  ],
    espnIds: [
    "112358",
    "161",
    "2115",
    "2130",
    "2330",
    "2385",
    "2441",
    "2598",
    "2681",
    "284",
  ],
  },  {
    slug: "ohio-valley-conference",
    name: "Ohio Valley Conference",
    teamSlugs: [
    "e-illinois",
    "eastern-illinois-panthers",
    "eiu",
    "lin",
    "lindenwood",
    "lindenwood-lions",
    "little-rock",
    "little-rock-trojans",
    "lr",
    "more",
    "morehead-st",
    "morehead-state-eagles",
    "s-indiana",
    "se-missouri",
    "semo",
    "siu-edwardsville-cougars",
    "siue",
    "southeast-missouri-state-redhawks",
    "southern-indiana-screaming-eagles",
    "tennessee-st",
    "tennessee-state-lady-tigers",
    "tennessee-tech",
    "tennessee-tech-golden-eagles",
    "tnst",
    "tntc",
    "usi",
    "ut-martin",
    "ut-martin-skyhawks",
    "utm",
    "w-illinois",
    "western-illinois-leathernecks",
    "wiu",
  ],
    teamNames: [
    "E Illinois",
    "Eastern Illinois Panthers",
    "Lindenwood",
    "Lindenwood Lions",
    "Little Rock",
    "Little Rock Trojans",
    "Morehead St",
    "Morehead State Eagles",
    "S Indiana",
    "SE Missouri",
    "SIU Edwardsville Cougars",
    "SIUE",
    "Southeast Missouri State Redhawks",
    "Southern Indiana Screaming Eagles",
    "Tennessee St",
    "Tennessee State Lady Tigers",
    "Tennessee Tech",
    "Tennessee Tech Golden Eagles",
    "UT Martin",
    "UT Martin Skyhawks",
    "W Illinois",
    "Western Illinois Leathernecks",
    "e-illinois",
    "eastern-illinois-panthers",
    "lindenwood",
    "lindenwood-lions",
    "little-rock",
    "little-rock-trojans",
    "morehead-st",
    "morehead-state-eagles",
    "s-indiana",
    "se-missouri",
    "siu-edwardsville-cougars",
    "siue",
    "southeast-missouri-state-redhawks",
    "southern-indiana-screaming-eagles",
    "tennessee-st",
    "tennessee-state-lady-tigers",
    "tennessee-tech",
    "tennessee-tech-golden-eagles",
    "ut-martin",
    "ut-martin-skyhawks",
    "w-illinois",
    "western-illinois-leathernecks",
  ],
    teamAbbrevs: [
    "EIU",
    "LIN",
    "LR",
    "MORE",
    "SEMO",
    "SIUE",
    "TNST",
    "TNTC",
    "USI",
    "UTM",
    "WIU",
    "eiu",
    "lin",
    "lr",
    "more",
    "semo",
    "siue",
    "tnst",
    "tntc",
    "usi",
    "utm",
    "wiu",
  ],
    espnIds: [
    "2031",
    "2197",
    "2413",
    "2546",
    "2565",
    "2630",
    "2634",
    "2635",
    "2710",
    "2815",
    "88",
  ],
  },  {
    slug: "patriot-league",
    name: "Patriot League",
    teamSlugs: [
    "amer",
    "american",
    "american-university-eagles",
    "army",
    "army-black-knights",
    "boston-u",
    "boston-university-terriers",
    "bu",
    "buck",
    "bucknell",
    "bucknell-bison",
    "colg",
    "colgate",
    "colgate-raiders",
    "hc",
    "holy-cross",
    "holy-cross-crusaders",
    "l-md",
    "laf",
    "lafayette",
    "lafayette-leopards",
    "leh",
    "lehigh",
    "lehigh-mountain-hawks",
    "loyola-maryland-greyhounds",
    "loyola-md",
    "navy",
    "navy-midshipmen",
  ],
    teamNames: [
    "American",
    "American University Eagles",
    "Army",
    "Army Black Knights",
    "Boston U",
    "Boston University Terriers",
    "Bucknell",
    "Bucknell Bison",
    "Colgate",
    "Colgate Raiders",
    "Holy Cross",
    "Holy Cross Crusaders",
    "Lafayette",
    "Lafayette Leopards",
    "Lehigh",
    "Lehigh Mountain Hawks",
    "Loyola MD",
    "Loyola Maryland Greyhounds",
    "Navy",
    "Navy Midshipmen",
    "american",
    "american-university-eagles",
    "army",
    "army-black-knights",
    "boston-u",
    "boston-university-terriers",
    "bucknell",
    "bucknell-bison",
    "colgate",
    "colgate-raiders",
    "holy-cross",
    "holy-cross-crusaders",
    "lafayette",
    "lafayette-leopards",
    "lehigh",
    "lehigh-mountain-hawks",
    "loyola-maryland-greyhounds",
    "loyola-md",
    "navy",
    "navy-midshipmen",
  ],
    teamAbbrevs: [
    "AMER",
    "ARMY",
    "BU",
    "BUCK",
    "COLG",
    "HC",
    "L-MD",
    "LAF",
    "LEH",
    "NAVY",
    "amer",
    "army",
    "bu",
    "buck",
    "colg",
    "hc",
    "l-md",
    "laf",
    "leh",
    "navy",
  ],
    espnIds: [
    "104",
    "107",
    "2083",
    "2142",
    "2329",
    "2352",
    "2426",
    "322",
    "349",
    "44",
  ],
  },  {
    slug: "southeastern-conference",
    name: "Southeastern Conference",
    teamSlugs: [
    "ala",
    "alabama",
    "alabama-crimson-tide",
    "ark",
    "arkansas",
    "arkansas-razorbacks",
    "aub",
    "auburn",
    "auburn-tigers",
    "fla",
    "florida",
    "florida-gators",
    "georgia",
    "georgia-lady-bulldogs",
    "kentucky",
    "kentucky-wildcats",
    "lsu",
    "lsu-tigers",
    "miss",
    "mississippi-st",
    "mississippi-state-bulldogs",
    "missouri",
    "missouri-tigers",
    "miz",
    "msst",
    "oklahoma",
    "oklahoma-sooners",
    "ole-miss",
    "ole-miss-rebels",
    "ou",
    "sc",
    "south-carolina",
    "south-carolina-gamecocks",
    "ta-m",
    "tenn",
    "tennessee",
    "tennessee-lady-volunteers",
    "tex",
    "texas",
    "texas-a-m",
    "texas-a-m-aggies",
    "texas-longhorns",
    "uga",
    "uk",
    "van",
    "vanderbilt",
    "vanderbilt-commodores",
  ],
    teamNames: [
    "Alabama",
    "Alabama Crimson Tide",
    "Arkansas",
    "Arkansas Razorbacks",
    "Auburn",
    "Auburn Tigers",
    "Florida",
    "Florida Gators",
    "Georgia",
    "Georgia Lady Bulldogs",
    "Kentucky",
    "Kentucky Wildcats",
    "LSU",
    "LSU Tigers",
    "Mississippi St",
    "Mississippi State Bulldogs",
    "Missouri",
    "Missouri Tigers",
    "Oklahoma",
    "Oklahoma Sooners",
    "Ole Miss",
    "Ole Miss Rebels",
    "South Carolina",
    "South Carolina Gamecocks",
    "Tennessee",
    "Tennessee Lady Volunteers",
    "Texas",
    "Texas A&M",
    "Texas A&M Aggies",
    "Texas Longhorns",
    "Vanderbilt",
    "Vanderbilt Commodores",
    "alabama",
    "alabama-crimson-tide",
    "arkansas",
    "arkansas-razorbacks",
    "auburn",
    "auburn-tigers",
    "florida",
    "florida-gators",
    "georgia",
    "georgia-lady-bulldogs",
    "kentucky",
    "kentucky-wildcats",
    "lsu",
    "lsu-tigers",
    "mississippi-st",
    "mississippi-state-bulldogs",
    "missouri",
    "missouri-tigers",
    "oklahoma",
    "oklahoma-sooners",
    "ole-miss",
    "ole-miss-rebels",
    "south-carolina",
    "south-carolina-gamecocks",
    "tennessee",
    "tennessee-lady-volunteers",
    "texas",
    "texas-a-m",
    "texas-a-m-aggies",
    "texas-longhorns",
    "vanderbilt",
    "vanderbilt-commodores",
  ],
    teamAbbrevs: [
    "ALA",
    "ARK",
    "AUB",
    "FLA",
    "LSU",
    "MISS",
    "MIZ",
    "MSST",
    "OU",
    "SC",
    "TA&M",
    "TENN",
    "TEX",
    "UGA",
    "UK",
    "VAN",
    "ala",
    "ark",
    "aub",
    "fla",
    "lsu",
    "miss",
    "miz",
    "msst",
    "ou",
    "sc",
    "ta-m",
    "tenn",
    "tex",
    "uga",
    "uk",
    "van",
  ],
    espnIds: [
    "142",
    "145",
    "2",
    "201",
    "238",
    "245",
    "251",
    "2579",
    "2633",
    "333",
    "344",
    "57",
    "61",
    "8",
    "96",
    "99",
  ],
  },  {
    slug: "southern-conference",
    name: "Southern Conference",
    teamSlugs: [
    "chattanooga",
    "chattanooga-mocs",
    "east-tennessee-state-bucs",
    "etsu",
    "fur",
    "furman",
    "furman-paladins",
    "mer",
    "mercer",
    "mercer-bears",
    "sam",
    "samford",
    "samford-bulldogs",
    "unc-greensboro",
    "unc-greensboro-spartans",
    "uncg",
    "utc",
    "w-carolina",
    "wcu",
    "western-carolina-catamounts",
    "wof",
    "wofford",
    "wofford-terriers",
  ],
    teamNames: [
    "Chattanooga",
    "Chattanooga Mocs",
    "ETSU",
    "East Tennessee State Bucs",
    "Furman",
    "Furman Paladins",
    "Mercer",
    "Mercer Bears",
    "Samford",
    "Samford Bulldogs",
    "UNC Greensboro",
    "UNC Greensboro Spartans",
    "W Carolina",
    "Western Carolina Catamounts",
    "Wofford",
    "Wofford Terriers",
    "chattanooga",
    "chattanooga-mocs",
    "east-tennessee-state-bucs",
    "etsu",
    "furman",
    "furman-paladins",
    "mercer",
    "mercer-bears",
    "samford",
    "samford-bulldogs",
    "unc-greensboro",
    "unc-greensboro-spartans",
    "w-carolina",
    "western-carolina-catamounts",
    "wofford",
    "wofford-terriers",
  ],
    teamAbbrevs: [
    "ETSU",
    "FUR",
    "MER",
    "SAM",
    "UNCG",
    "UTC",
    "WCU",
    "WOF",
    "etsu",
    "fur",
    "mer",
    "sam",
    "uncg",
    "utc",
    "wcu",
    "wof",
  ],
    espnIds: [
    "2193",
    "231",
    "236",
    "2382",
    "2430",
    "2535",
    "2717",
    "2747",
  ],
  },  {
    slug: "southland-conference",
    name: "Southland Conference",
    teamSlugs: [
    "amcc",
    "east-texas-a-m",
    "east-texas-a-m-lions",
    "etam",
    "hcu",
    "hou-christian",
    "houston-christian-huskies",
    "incarnate-word",
    "incarnate-word-cardinals",
    "lam",
    "lamar",
    "lamar-cardinals",
    "lsu-n-orleans",
    "lsu-new-orleans-privateers",
    "mcn",
    "mcneese",
    "mcneese-cowgirls",
    "nich",
    "nicholls",
    "nicholls-colonels",
    "nola",
    "northwestern-state-lady-demons",
    "nwestern-st",
    "nwst",
    "rgv",
    "se-louisiana",
    "se-louisiana-lady-lions",
    "sela",
    "sf-austin",
    "sfa",
    "stephen-f-austin-ladyjacks",
    "texas-a-m-cc",
    "texas-a-m-corpus-christi-islanders",
    "uiw",
    "ut-rio-grande",
    "ut-rio-grande-valley-vaqueros",
  ],
    teamNames: [
    "East Texas A&M",
    "East Texas A&M Lions",
    "Hou Christian",
    "Houston Christian Huskies",
    "Incarnate Word",
    "Incarnate Word Cardinals",
    "LSU N Orleans",
    "LSU New Orleans Privateers",
    "Lamar",
    "Lamar Cardinals",
    "McNeese",
    "McNeese Cowgirls",
    "N'Western St",
    "Nicholls",
    "Nicholls Colonels",
    "Northwestern State Lady Demons",
    "SE Louisiana",
    "SE Louisiana Lady Lions",
    "SF Austin",
    "Stephen F. Austin Ladyjacks",
    "Texas A&M-CC",
    "Texas A&M-Corpus Christi Islanders",
    "UT Rio Grande",
    "UT Rio Grande Valley Vaqueros",
    "east-texas-a-m",
    "east-texas-a-m-lions",
    "hou-christian",
    "houston-christian-huskies",
    "incarnate-word",
    "incarnate-word-cardinals",
    "lamar",
    "lamar-cardinals",
    "lsu-n-orleans",
    "lsu-new-orleans-privateers",
    "mcneese",
    "mcneese-cowgirls",
    "nicholls",
    "nicholls-colonels",
    "northwestern-state-lady-demons",
    "nwestern-st",
    "se-louisiana",
    "se-louisiana-lady-lions",
    "sf-austin",
    "stephen-f-austin-ladyjacks",
    "texas-a-m-cc",
    "texas-a-m-corpus-christi-islanders",
    "ut-rio-grande",
    "ut-rio-grande-valley-vaqueros",
  ],
    teamAbbrevs: [
    "AMCC",
    "ETAM",
    "HCU",
    "LAM",
    "MCN",
    "NICH",
    "NOLA",
    "NWST",
    "RGV",
    "SELA",
    "SFA",
    "UIW",
    "amcc",
    "etam",
    "hcu",
    "lam",
    "mcn",
    "nich",
    "nola",
    "nwst",
    "rgv",
    "sela",
    "sfa",
    "uiw",
  ],
    espnIds: [
    "2277",
    "2320",
    "2377",
    "2443",
    "2447",
    "2466",
    "2545",
    "2617",
    "2837",
    "2916",
    "292",
    "357",
  ],
  },  {
    slug: "southwestern-athletic-conference",
    name: "Southwestern Athletic Conference",
    teamSlugs: [
    "aamu",
    "alabama-a-m",
    "alabama-a-m-bulldogs",
    "alabama-st",
    "alabama-state-lady-hornets",
    "alcn",
    "alcorn-st",
    "alcorn-state-lady-braves",
    "alst",
    "ar-pine-bluff",
    "arkansas-pine-bluff-golden-lions",
    "bcu",
    "bethune",
    "bethune-cookman-wildcats",
    "famu",
    "florida-a-m",
    "florida-a-m-rattlers",
    "gram",
    "grambling",
    "grambling-lady-tigers",
    "jackson-st",
    "jackson-state-lady-tigers",
    "jkst",
    "miss-valley-st",
    "mississippi-valley-state-devilettes",
    "mvsu",
    "prairie-view",
    "prairie-view-a-m-lady-panthers",
    "pv",
    "sou",
    "southern",
    "southern-jaguars",
    "texas-southern",
    "texas-southern-tigers",
    "txso",
    "uapb",
  ],
    teamNames: [
    "AR-Pine Bluff",
    "Alabama A&M",
    "Alabama A&M Bulldogs",
    "Alabama St",
    "Alabama State Lady Hornets",
    "Alcorn St",
    "Alcorn State Lady Braves",
    "Arkansas-Pine Bluff Golden Lions",
    "Bethune",
    "Bethune-Cookman Wildcats",
    "Florida A&M",
    "Florida A&M Rattlers",
    "Grambling",
    "Grambling Lady Tigers",
    "Jackson St",
    "Jackson State Lady Tigers",
    "Miss Valley St",
    "Mississippi Valley State Devilettes",
    "Prairie View",
    "Prairie View A&M Lady Panthers",
    "Southern",
    "Southern Jaguars",
    "Texas Southern",
    "Texas Southern Tigers",
    "alabama-a-m",
    "alabama-a-m-bulldogs",
    "alabama-st",
    "alabama-state-lady-hornets",
    "alcorn-st",
    "alcorn-state-lady-braves",
    "ar-pine-bluff",
    "arkansas-pine-bluff-golden-lions",
    "bethune",
    "bethune-cookman-wildcats",
    "florida-a-m",
    "florida-a-m-rattlers",
    "grambling",
    "grambling-lady-tigers",
    "jackson-st",
    "jackson-state-lady-tigers",
    "miss-valley-st",
    "mississippi-valley-state-devilettes",
    "prairie-view",
    "prairie-view-a-m-lady-panthers",
    "southern",
    "southern-jaguars",
    "texas-southern",
    "texas-southern-tigers",
  ],
    teamAbbrevs: [
    "AAMU",
    "ALCN",
    "ALST",
    "BCU",
    "FAMU",
    "GRAM",
    "JKST",
    "MVSU",
    "PV",
    "SOU",
    "TXSO",
    "UAPB",
    "aamu",
    "alcn",
    "alst",
    "bcu",
    "famu",
    "gram",
    "jkst",
    "mvsu",
    "pv",
    "sou",
    "txso",
    "uapb",
  ],
    espnIds: [
    "2010",
    "2011",
    "2016",
    "2029",
    "2065",
    "2296",
    "2400",
    "2504",
    "2582",
    "2640",
    "2755",
    "50",
  ],
  },  {
    slug: "summit-league",
    name: "Summit League",
    teamSlugs: [
    "den",
    "denver",
    "denver-pioneers",
    "kansas-city",
    "kansas-city-roos",
    "kc",
    "n-dakota-st",
    "ndsu",
    "north-dakota",
    "north-dakota-fighting-hawks",
    "north-dakota-state-bison",
    "oma",
    "omaha",
    "omaha-mavericks",
    "oral-roberts",
    "oral-roberts-golden-eagles",
    "oru",
    "s-dakota-st",
    "sdak",
    "sdst",
    "south-dakota",
    "south-dakota-coyotes",
    "south-dakota-state-jackrabbits",
    "st-thomas",
    "st-thomas-tommies",
    "stmn",
    "und",
  ],
    teamNames: [
    "Denver",
    "Denver Pioneers",
    "Kansas City",
    "Kansas City Roos",
    "N Dakota St",
    "North Dakota",
    "North Dakota Fighting Hawks",
    "North Dakota State Bison",
    "Omaha",
    "Omaha Mavericks",
    "Oral Roberts",
    "Oral Roberts Golden Eagles",
    "S Dakota St",
    "South Dakota",
    "South Dakota Coyotes",
    "South Dakota State Jackrabbits",
    "St Thomas",
    "St. Thomas Tommies",
    "denver",
    "denver-pioneers",
    "kansas-city",
    "kansas-city-roos",
    "n-dakota-st",
    "north-dakota",
    "north-dakota-fighting-hawks",
    "north-dakota-state-bison",
    "omaha",
    "omaha-mavericks",
    "oral-roberts",
    "oral-roberts-golden-eagles",
    "s-dakota-st",
    "south-dakota",
    "south-dakota-coyotes",
    "south-dakota-state-jackrabbits",
    "st-thomas",
    "st-thomas-tommies",
  ],
    teamAbbrevs: [
    "DEN",
    "KC",
    "NDSU",
    "OMA",
    "ORU",
    "SDAK",
    "SDST",
    "STMN",
    "UND",
    "den",
    "kc",
    "ndsu",
    "oma",
    "oru",
    "sdak",
    "sdst",
    "stmn",
    "und",
  ],
    espnIds: [
    "140",
    "155",
    "198",
    "2172",
    "233",
    "2437",
    "2449",
    "2571",
    "2900",
  ],
  },  {
    slug: "sun-belt-conference",
    name: "Sun Belt Conference",
    teamSlugs: [
    "app",
    "app-state",
    "app-state-mountaineers",
    "arkansas-st",
    "arkansas-state-red-wolves",
    "arst",
    "ccu",
    "coastal",
    "coastal-carolina-chanticleers",
    "ga-southern",
    "gaso",
    "gast",
    "georgia-southern-eagles",
    "georgia-st",
    "georgia-state-panthers",
    "james-madison",
    "james-madison-dukes",
    "jmu",
    "louisiana",
    "louisiana-ragin-cajuns",
    "marshall",
    "marshall-thundering-herd",
    "mrsh",
    "odu",
    "old-dominion",
    "old-dominion-monarchs",
    "south-alabama",
    "south-alabama-jaguars",
    "southern-miss",
    "southern-miss-lady-eagles",
    "texas-st",
    "texas-state-bobcats",
    "troy",
    "troy-trojans",
    "txst",
    "ul",
    "ul-monroe",
    "ul-monroe-warhawks",
    "ulm",
    "usa",
    "usm",
  ],
    teamNames: [
    "App State",
    "App State Mountaineers",
    "Arkansas St",
    "Arkansas State Red Wolves",
    "Coastal",
    "Coastal Carolina Chanticleers",
    "GA Southern",
    "Georgia Southern Eagles",
    "Georgia St",
    "Georgia State Panthers",
    "James Madison",
    "James Madison Dukes",
    "Louisiana",
    "Louisiana Ragin' Cajuns",
    "Marshall",
    "Marshall Thundering Herd",
    "Old Dominion",
    "Old Dominion Monarchs",
    "South Alabama",
    "South Alabama Jaguars",
    "Southern Miss",
    "Southern Miss Lady Eagles",
    "Texas St",
    "Texas State Bobcats",
    "Troy",
    "Troy Trojans",
    "UL Monroe",
    "UL Monroe Warhawks",
    "app-state",
    "app-state-mountaineers",
    "arkansas-st",
    "arkansas-state-red-wolves",
    "coastal",
    "coastal-carolina-chanticleers",
    "ga-southern",
    "georgia-southern-eagles",
    "georgia-st",
    "georgia-state-panthers",
    "james-madison",
    "james-madison-dukes",
    "louisiana",
    "louisiana-ragin-cajuns",
    "marshall",
    "marshall-thundering-herd",
    "old-dominion",
    "old-dominion-monarchs",
    "south-alabama",
    "south-alabama-jaguars",
    "southern-miss",
    "southern-miss-lady-eagles",
    "texas-st",
    "texas-state-bobcats",
    "troy",
    "troy-trojans",
    "ul-monroe",
    "ul-monroe-warhawks",
  ],
    teamAbbrevs: [
    "APP",
    "ARST",
    "CCU",
    "GASO",
    "GAST",
    "JMU",
    "MRSH",
    "ODU",
    "TROY",
    "TXST",
    "UL",
    "ULM",
    "USA",
    "USM",
    "app",
    "arst",
    "ccu",
    "gaso",
    "gast",
    "jmu",
    "mrsh",
    "odu",
    "troy",
    "txst",
    "ul",
    "ulm",
    "usa",
    "usm",
  ],
    espnIds: [
    "2026",
    "2032",
    "2247",
    "2433",
    "256",
    "2572",
    "2653",
    "276",
    "290",
    "295",
    "309",
    "324",
    "326",
    "6",
  ],
  },  {
    slug: "united-athletic-conference",
    name: "United Athletic Conference",
    teamSlugs: [
    "abilene-christian-wildcats",
    "abilene-chrstn",
    "acu",
    "ca-baptist",
    "california-baptist-lancers",
    "cbu",
    "southern-utah",
    "southern-utah-thunderbirds",
    "suu",
    "tar",
    "tarleton-st",
    "tarleton-state-texans",
    "ut-arlington",
    "ut-arlington-mavericks",
    "uta",
    "utah-tech",
    "utah-tech-trailblazers",
    "utah-valley",
    "utah-valley-wolverines",
    "utu",
    "uvu",
  ],
    teamNames: [
    "Abilene Christian Wildcats",
    "Abilene Chrstn",
    "CA Baptist",
    "California Baptist Lancers",
    "Southern Utah",
    "Southern Utah Thunderbirds",
    "Tarleton St",
    "Tarleton State Texans",
    "UT Arlington",
    "UT Arlington Mavericks",
    "Utah Tech",
    "Utah Tech Trailblazers",
    "Utah Valley",
    "Utah Valley Wolverines",
    "abilene-christian-wildcats",
    "abilene-chrstn",
    "ca-baptist",
    "california-baptist-lancers",
    "southern-utah",
    "southern-utah-thunderbirds",
    "tarleton-st",
    "tarleton-state-texans",
    "ut-arlington",
    "ut-arlington-mavericks",
    "utah-tech",
    "utah-tech-trailblazers",
    "utah-valley",
    "utah-valley-wolverines",
  ],
    teamAbbrevs: [
    "ACU",
    "CBU",
    "SUU",
    "TAR",
    "UTA",
    "UTU",
    "UVU",
    "acu",
    "cbu",
    "suu",
    "tar",
    "uta",
    "utu",
    "uvu",
  ],
    espnIds: [
    "2000",
    "250",
    "253",
    "2627",
    "2856",
    "3084",
    "3101",
  ],
  },  {
    slug: "west-coast-conference",
    name: "West Coast Conference",
    teamSlugs: [
    "gonz",
    "gonzaga",
    "gonzaga-bulldogs",
    "lmu",
    "loyola-marymount-lions",
    "oregon-st",
    "oregon-state-beavers",
    "orst",
    "pac",
    "pacific",
    "pacific-tigers",
    "pepp",
    "pepperdine",
    "pepperdine-waves",
    "port",
    "portland",
    "portland-pilots",
    "saint-marys",
    "saint-marys-gaels",
    "san-diego",
    "san-diego-toreros",
    "san-francisco",
    "san-francisco-dons",
    "santa-clara",
    "santa-clara-broncos",
    "scu",
    "sea",
    "seattle-u",
    "seattle-u-redhawks",
    "sf",
    "smc",
    "usd",
    "washington-st",
    "washington-state-cougars",
    "wsu",
  ],
    teamNames: [
    "Gonzaga",
    "Gonzaga Bulldogs",
    "LMU",
    "Loyola Marymount Lions",
    "Oregon St",
    "Oregon State Beavers",
    "Pacific",
    "Pacific Tigers",
    "Pepperdine",
    "Pepperdine Waves",
    "Portland",
    "Portland Pilots",
    "Saint Mary's",
    "Saint Mary's Gaels",
    "San Diego",
    "San Diego Toreros",
    "San Francisco",
    "San Francisco Dons",
    "Santa Clara",
    "Santa Clara Broncos",
    "Seattle U",
    "Seattle U Redhawks",
    "Washington St",
    "Washington State Cougars",
    "gonzaga",
    "gonzaga-bulldogs",
    "lmu",
    "loyola-marymount-lions",
    "oregon-st",
    "oregon-state-beavers",
    "pacific",
    "pacific-tigers",
    "pepperdine",
    "pepperdine-waves",
    "portland",
    "portland-pilots",
    "saint-marys",
    "saint-marys-gaels",
    "san-diego",
    "san-diego-toreros",
    "san-francisco",
    "san-francisco-dons",
    "santa-clara",
    "santa-clara-broncos",
    "seattle-u",
    "seattle-u-redhawks",
    "washington-st",
    "washington-state-cougars",
  ],
    teamAbbrevs: [
    "GONZ",
    "LMU",
    "ORST",
    "PAC",
    "PEPP",
    "PORT",
    "SCU",
    "SEA",
    "SF",
    "SMC",
    "USD",
    "WSU",
    "gonz",
    "lmu",
    "orst",
    "pac",
    "pepp",
    "port",
    "scu",
    "sea",
    "sf",
    "smc",
    "usd",
    "wsu",
  ],
    espnIds: [
    "204",
    "2250",
    "2351",
    "2492",
    "2501",
    "2539",
    "2541",
    "2547",
    "2608",
    "265",
    "279",
    "301",
  ],
  },
] as const;

export const ESPN_ID_TO_CONFERENCE: Record<string, string> = {
  "103": "atlantic-coast-conference",
  "104": "patriot-league",
  "107": "patriot-league",
  "108": "ivy-league",
  "111": "coastal-athletic-association",
  "112358": "northeast-conference",
  "113": "mid-american-conference",
  "116": "metro-conference",
  "119": "coastal-athletic-association",
  "12": "big-12-conference",
  "120": "big-ten-conference",
  "127": "big-ten-conference",
  "13": "big-west-conference",
  "130": "big-ten-conference",
  "135": "big-ten-conference",
  "139": "atlantic-10-conference",
  "140": "summit-league",
  "142": "southeastern-conference",
  "145": "southeastern-conference",
  "147": "big-sky-conference",
  "149": "big-sky-conference",
  "150": "atlantic-coast-conference",
  "151": "american-conference",
  "152": "atlantic-coast-conference",
  "153": "atlantic-coast-conference",
  "154": "atlantic-coast-conference",
  "155": "summit-league",
  "156": "big-east-conference",
  "158": "big-ten-conference",
  "159": "ivy-league",
  "16": "big-sky-conference",
  "160": "america-east-conference",
  "161": "northeast-conference",
  "163": "ivy-league",
  "164": "big-ten-conference",
  "166": "conference-usa",
  "167": "mountain-west-conference",
  "171": "ivy-league",
  "172": "ivy-league",
  "179": "atlantic-10-conference",
  "183": "atlantic-coast-conference",
  "189": "mid-american-conference",
  "193": "mid-american-conference",
  "194": "big-ten-conference",
  "195": "mid-american-conference",
  "197": "big-12-conference",
  "198": "summit-league",
  "2": "southeastern-conference",
  "2000": "united-athletic-conference",
  "2005": "mountain-west-conference",
  "2006": "mid-american-conference",
  "201": "southeastern-conference",
  "2010": "southwestern-athletic-conference",
  "2011": "southwestern-athletic-conference",
  "2016": "southwestern-athletic-conference",
  "202": "american-conference",
  "2026": "sun-belt-conference",
  "2029": "southwestern-athletic-conference",
  "2031": "ohio-valley-conference",
  "2032": "sun-belt-conference",
  "204": "west-coast-conference",
  "2046": "atlantic-sun-conference",
  "2050": "mid-american-conference",
  "2057": "missouri-valley-conference",
  "2065": "southwestern-athletic-conference",
  "2066": "america-east-conference",
  "2083": "patriot-league",
  "2084": "mid-american-conference",
  "2086": "big-east-conference",
  "2097": "coastal-athletic-association",
  "2099": "metro-conference",
  "21": "mountain-west-conference",
  "2110": "atlantic-sun-conference",
  "2115": "northeast-conference",
  "2116": "big-12-conference",
  "2117": "mid-american-conference",
  "2127": "big-south-conference",
  "213": "big-ten-conference",
  "2130": "northeast-conference",
  "2132": "big-12-conference",
  "2142": "patriot-league",
  "2154": "mid-eastern-athletic-conference",
  "2166": "atlantic-10-conference",
  "2168": "atlantic-10-conference",
  "2169": "mid-eastern-athletic-conference",
  "2172": "summit-league",
  "2174": "horizon-league",
  "218": "american-conference",
  "2181": "missouri-valley-conference",
  "2182": "coastal-athletic-association",
  "2184": "atlantic-10-conference",
  "219": "ivy-league",
  "2193": "southern-conference",
  "2197": "ohio-valley-conference",
  "2198": "atlantic-sun-conference",
  "2199": "mid-american-conference",
  "221": "atlantic-coast-conference",
  "2210": "coastal-athletic-association",
  "2217": "metro-conference",
  "222": "big-east-conference",
  "2226": "american-conference",
  "2229": "conference-usa",
  "2230": "atlantic-10-conference",
  "2239": "big-west-conference",
  "2241": "big-south-conference",
  "2244": "atlantic-10-conference",
  "2247": "sun-belt-conference",
  "225": "ivy-league",
  "2250": "west-coast-conference",
  "2253": "mountain-west-conference",
  "2261": "coastal-athletic-association",
  "227": "atlantic-10-conference",
  "2272": "big-south-conference",
  "2275": "coastal-athletic-association",
  "2277": "southland-conference",
  "228": "atlantic-coast-conference",
  "2287": "missouri-valley-conference",
  "2294": "big-ten-conference",
  "2296": "southwestern-athletic-conference",
  "23": "mountain-west-conference",
  "2305": "big-12-conference",
  "2306": "big-12-conference",
  "2309": "mid-american-conference",
  "231": "southern-conference",
  "232": "coastal-athletic-association",
  "2320": "southland-conference",
  "2325": "atlantic-10-conference",
  "2329": "patriot-league",
  "233": "summit-league",
  "2330": "northeast-conference",
  "2335": "conference-usa",
  "2344": "big-south-conference",
  "2348": "conference-usa",
  "2349": "america-east-conference",
  "235": "american-conference",
  "2350": "atlantic-10-conference",
  "2351": "west-coast-conference",
  "2352": "patriot-league",
  "236": "southern-conference",
  "2363": "metro-conference",
  "2368": "metro-conference",
  "2377": "southland-conference",
  "2378": "america-east-conference",
  "2379": "mid-eastern-athletic-conference",
  "238": "southeastern-conference",
  "2382": "southern-conference",
  "2385": "northeast-conference",
  "239": "big-12-conference",
  "2390": "atlantic-coast-conference",
  "2393": "conference-usa",
  "24": "atlantic-coast-conference",
  "2400": "southwestern-athletic-conference",
  "2405": "coastal-athletic-association",
  "2413": "ohio-valley-conference",
  "2415": "mid-eastern-athletic-conference",
  "242": "american-conference",
  "2426": "patriot-league",
  "2427": "big-south-conference",
  "2428": "mid-eastern-athletic-conference",
  "2429": "american-conference",
  "2430": "southern-conference",
  "2433": "sun-belt-conference",
  "2437": "summit-league",
  "2439": "mountain-west-conference",
  "2440": "mountain-west-conference",
  "2441": "northeast-conference",
  "2443": "southland-conference",
  "2447": "southland-conference",
  "2448": "coastal-athletic-association",
  "2449": "summit-league",
  "245": "southeastern-conference",
  "2450": "mid-eastern-athletic-conference",
  "2453": "atlantic-sun-conference",
  "2454": "atlantic-sun-conference",
  "2458": "big-sky-conference",
  "2459": "mid-american-conference",
  "2460": "missouri-valley-conference",
  "2463": "big-west-conference",
  "2464": "big-sky-conference",
  "2466": "southland-conference",
  "2473": "horizon-league",
  "248": "big-12-conference",
  "2483": "big-ten-conference",
  "249": "american-conference",
  "2492": "west-coast-conference",
  "25": "atlantic-coast-conference",
  "250": "united-athletic-conference",
  "2501": "west-coast-conference",
  "2502": "big-sky-conference",
  "2504": "southwestern-athletic-conference",
  "2506": "big-south-conference",
  "2507": "big-east-conference",
  "2509": "big-ten-conference",
  "251": "southeastern-conference",
  "2511": "atlantic-sun-conference",
  "2514": "metro-conference",
  "2515": "big-south-conference",
  "252": "big-12-conference",
  "2520": "metro-conference",
  "2523": "horizon-league",
  "2529": "metro-conference",
  "253": "united-athletic-conference",
  "2534": "conference-usa",
  "2535": "southern-conference",
  "2539": "west-coast-conference",
  "254": "big-12-conference",
  "2540": "big-west-conference",
  "2541": "west-coast-conference",
  "2545": "southland-conference",
  "2546": "ohio-valley-conference",
  "2547": "west-coast-conference",
  "2550": "big-east-conference",
  "256": "sun-belt-conference",
  "2561": "metro-conference",
  "2565": "ohio-valley-conference",
  "2567": "atlantic-coast-conference",
  "2569": "mid-eastern-athletic-conference",
  "257": "atlantic-10-conference",
  "2571": "summit-league",
  "2572": "sun-belt-conference",
  "2579": "southeastern-conference",
  "258": "atlantic-coast-conference",
  "2582": "southwestern-athletic-conference",
  "259": "atlantic-coast-conference",
  "2598": "northeast-conference",
  "2599": "big-east-conference",
  "26": "big-ten-conference",
  "2603": "atlantic-10-conference",
  "2608": "west-coast-conference",
  "261": "america-east-conference",
  "2612": "metro-conference",
  "2617": "southland-conference",
  "2619": "coastal-athletic-association",
  "2623": "conference-usa",
  "2627": "united-athletic-conference",
  "2628": "big-12-conference",
  "2630": "ohio-valley-conference",
  "2633": "southeastern-conference",
  "2634": "ohio-valley-conference",
  "2635": "ohio-valley-conference",
  "2636": "american-conference",
  "2638": "conference-usa",
  "264": "big-ten-conference",
  "2640": "southwestern-athletic-conference",
  "2641": "big-12-conference",
  "2649": "mid-american-conference",
  "265": "west-coast-conference",
  "2653": "sun-belt-conference",
  "2655": "american-conference",
  "2670": "atlantic-10-conference",
  "2674": "missouri-valley-conference",
  "2681": "northeast-conference",
  "269": "big-east-conference",
  "2692": "big-sky-conference",
  "2698": "atlantic-sun-conference",
  "27": "big-west-conference",
  "270": "horizon-league",
  "2710": "ohio-valley-conference",
  "2711": "mid-american-conference",
  "2717": "southern-conference",
  "2724": "american-conference",
  "2729": "coastal-athletic-association",
  "2737": "big-south-conference",
  "2739": "horizon-league",
  "2747": "southern-conference",
  "275": "big-ten-conference",
  "2750": "horizon-league",
  "2751": "mountain-west-conference",
  "2752": "big-east-conference",
  "2754": "horizon-league",
  "2755": "southwestern-athletic-conference",
  "276": "sun-belt-conference",
  "277": "big-12-conference",
  "2771": "metro-conference",
  "278": "mountain-west-conference",
  "279": "west-coast-conference",
  "28": "big-west-conference",
  "2803": "america-east-conference",
  "2815": "ohio-valley-conference",
  "282": "missouri-valley-conference",
  "2837": "southland-conference",
  "284": "northeast-conference",
  "2856": "united-athletic-conference",
  "2870": "horizon-league",
  "288": "atlantic-sun-conference",
  "2885": "america-east-conference",
  "290": "sun-belt-conference",
  "2900": "summit-league",
  "2908": "big-south-conference",
  "2916": "southland-conference",
  "292": "southland-conference",
  "2934": "big-west-conference",
  "294": "atlantic-sun-conference",
  "295": "sun-belt-conference",
  "299": "big-west-conference",
  "30": "big-ten-conference",
  "300": "big-west-conference",
  "301": "west-coast-conference",
  "302": "big-west-conference",
  "304": "big-sky-conference",
  "305": "big-east-conference",
  "3084": "united-athletic-conference",
  "309": "sun-belt-conference",
  "3101": "united-athletic-conference",
  "311": "america-east-conference",
  "314": "metro-conference",
  "315": "metro-conference",
  "322": "patriot-league",
  "324": "sun-belt-conference",
  "325": "horizon-league",
  "326": "sun-belt-conference",
  "328": "mountain-west-conference",
  "331": "big-sky-conference",
  "333": "southeastern-conference",
  "338": "conference-usa",
  "339": "missouri-valley-conference",
  "344": "southeastern-conference",
  "349": "patriot-league",
  "350": "coastal-athletic-association",
  "356": "big-ten-conference",
  "357": "southland-conference",
  "36": "mountain-west-conference",
  "38": "big-12-conference",
  "399": "america-east-conference",
  "41": "big-east-conference",
  "43": "ivy-league",
  "44": "patriot-league",
  "45": "atlantic-10-conference",
  "46": "big-east-conference",
  "47": "mid-eastern-athletic-conference",
  "48": "conference-usa",
  "5": "american-conference",
  "50": "southwestern-athletic-conference",
  "52": "atlantic-coast-conference",
  "526": "atlantic-sun-conference",
  "55": "conference-usa",
  "56": "atlantic-sun-conference",
  "57": "southeastern-conference",
  "58": "american-conference",
  "59": "atlantic-coast-conference",
  "6": "sun-belt-conference",
  "61": "southeastern-conference",
  "62": "big-west-conference",
  "66": "big-12-conference",
  "68": "mountain-west-conference",
  "70": "big-sky-conference",
  "71": "missouri-valley-conference",
  "77": "big-ten-conference",
  "79": "missouri-valley-conference",
  "8": "southeastern-conference",
  "82": "missouri-valley-conference",
  "84": "big-ten-conference",
  "85": "horizon-league",
  "87": "atlantic-coast-conference",
  "88": "ohio-valley-conference",
  "9": "big-12-conference",
  "91": "atlantic-sun-conference",
  "93": "missouri-valley-conference",
  "94": "horizon-league",
  "96": "southeastern-conference",
  "97": "atlantic-coast-conference",
  "98": "conference-usa",
  "99": "southeastern-conference"
};

function nameToSlug(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[''.]/g, "")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function normalizeName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[''.]/g, "")
    .replace(/&/g, " and ")
    .replace(/\s+/g, " ");
}

function teamMatchesConference(
  team: { name: string; abbreviation: string; slug: string },
  conference: NcaaWConferenceMeta,
): boolean {
  const slug = team.slug.trim().toLowerCase();
  const nameSlug = nameToSlug(team.name);
  const normalizedTeamName = normalizeName(team.name);
  const abbrev = team.abbreviation.trim().toLowerCase();

  for (const conferenceSlug of conference.teamSlugs) {
    if (slug && slug === conferenceSlug) return true;
    if (nameSlug && nameSlug === conferenceSlug) return true;
  }

  for (const conferenceName of conference.teamNames) {
    const normalizedConferenceName = normalizeName(conferenceName);
    if (normalizedConferenceName === normalizedTeamName) return true;
    if (normalizedConferenceName.startsWith(`${normalizedTeamName} `)) return true;
    if (normalizedTeamName.startsWith(`${normalizedConferenceName} `)) return true;
  }

  for (const conferenceAbbrev of conference.teamAbbrevs) {
    if (abbrev && abbrev === conferenceAbbrev.trim().toLowerCase()) return true;
  }

  return false;
}

function conferenceForNcaaWTeam(team: { name: string; abbreviation: string; slug: string }): string {
  for (const conference of CONFERENCES) {
    if (teamMatchesConference(team, conference)) return conference.slug;
  }
  return OTHER_NCAA_W_CONFERENCE_SLUG;
}

export const NCAA_W_CONFERENCES = CONFERENCES;
export const OTHER_NCAA_W_CONFERENCE_SLUG = "other";

export function getNcaaWConference(slug: string): NcaaWConferenceMeta | undefined {
  return CONFERENCES.find((conference) => conference.slug === slug);
}

export function groupNcaaWTeamsByConference<T extends { name: string; abbreviation: string; slug: string }>(
  teams: T[],
): NcaaWConferenceGroup<T>[] {
  const buckets = new Map<string, T[]>();
  for (const team of teams) {
    const slug = conferenceForNcaaWTeam(team);
    const list = buckets.get(slug) ?? [];
    list.push(team);
    buckets.set(slug, list);
  }

  const groups: NcaaWConferenceGroup<T>[] = CONFERENCES.map((conference) => ({
    conference,
    teams: (buckets.get(conference.slug) ?? []).sort((a, b) => a.name.localeCompare(b.name)),
  })).filter((group) => group.teams.length > 0);

  const otherTeams = buckets.get(OTHER_NCAA_W_CONFERENCE_SLUG) ?? [];
  if (otherTeams.length > 0) {
    groups.push({
      conference: { slug: OTHER_NCAA_W_CONFERENCE_SLUG, name: "Other" },
      teams: otherTeams.sort((a, b) => a.name.localeCompare(b.name)),
    });
  }

  return groups;
}
