// Auto-generated for u-sports conference grouping.
// Source: u-sports-current-teams.json
// Regenerate: python3 scripts/generate-college-conferences.py --league u-sports
// Generated: 2026-08-12

import {
  createCollegeConferenceGrouper,
  type CollegeConferenceGroup,
  type CollegeConferenceMeta,
} from "./college-conference-core";

export type USportsConferenceMeta = CollegeConferenceMeta;
export type USportsConferenceGroup<T> = CollegeConferenceGroup<T>;

const CONFERENCES: readonly CollegeConferenceMeta[] = [
  {
    slug: "atlantic-university-sport",
    name: "Atlantic University Sport",
    teamSlugs: [
    "Acadia",
    "Cape Breton",
    "Dalhousie",
    "Memorial",
    "Saint Mary's",
    "StFX",
    "UNB",
    "UPEI",
    "acadia",
    "acadia university",
    "acadia-university",
    "cape breton h.",
    "cape breton highlanders",
    "cape breton university",
    "cape-breton",
    "cape-breton-h",
    "cape-breton-highlanders",
    "cape-breton-university",
    "cbh",
    "cbu",
    "dalhousie",
    "dalhousie university",
    "dalhousie-university",
    "du",
    "memori",
    "memorial",
    "memorial university",
    "memorial university of new foundland",
    "memorial university of newfoundland",
    "memorial-university",
    "memorial-university-of-new-foundland",
    "memorial-university-of-newfoundland",
    "mu",
    "muon",
    "muonf",
    "saint mary's university",
    "saint-mary-s-university",
    "saint-marys",
    "saint-marys-university",
    "smu",
    "st-francis-x",
    "st.francis x.",
    "stfrancis-x",
    "stfx",
    "sx",
    "unb",
    "unb saint john",
    "unb-saint-john",
    "upei",
    "usj",
  ],
    teamNames: [
    "Acadia",
    "Cape Breton",
    "Dalhousie",
    "Memorial",
    "Saint Mary's",
    "StFX",
    "UNB",
    "UPEI",
    "acadia",
    "acadia university",
    "acadia-university",
    "cape breton h.",
    "cape breton highlanders",
    "cape breton university",
    "cape-breton",
    "cape-breton-h",
    "cape-breton-highlanders",
    "cape-breton-university",
    "cbh",
    "cbu",
    "dalhousie",
    "dalhousie university",
    "dalhousie-university",
    "du",
    "memori",
    "memorial",
    "memorial university",
    "memorial university of new foundland",
    "memorial university of newfoundland",
    "memorial-university",
    "memorial-university-of-new-foundland",
    "memorial-university-of-newfoundland",
    "mu",
    "muon",
    "muonf",
    "saint mary's university",
    "saint-mary-s-university",
    "saint-marys",
    "saint-marys-university",
    "smu",
    "st-francis-x",
    "st.francis x.",
    "stfrancis-x",
    "stfx",
    "sx",
    "unb",
    "unb saint john",
    "unb-saint-john",
    "upei",
    "usj",
  ],
    canonicalSchools: [
    "Acadia",
    "Cape Breton",
    "Dalhousie",
    "Memorial",
    "Saint Mary's",
    "StFX",
    "UNB",
    "UPEI",
  ],
  },  {
    slug: "canada-west",
    name: "Canada West",
    teamSlugs: [
    "Alberta",
    "Brandon",
    "Calgary",
    "Lethbridge",
    "MacEwan",
    "Manitoba",
    "Mount Royal",
    "Regina",
    "Saskatchewan",
    "Thompson Rivers",
    "Trinity Western",
    "UBC",
    "UBC Okanagan",
    "UFV",
    "UNBC",
    "Victoria",
    "Winnipeg",
    "alberta",
    "brandon",
    "brandon university",
    "brandon-university",
    "calgary",
    "lethbr",
    "lethbridge",
    "macewan",
    "macewan university",
    "macewan-university",
    "manitoba",
    "manitoba univ.",
    "manitoba university",
    "manitoba-univ",
    "manitoba-university",
    "mount royal cougars",
    "mount royal university",
    "mount-royal",
    "mount-royal-cougars",
    "mount-royal-university",
    "mrc",
    "mru",
    "regina",
    "saskatchewan",
    "thompson rivers university",
    "thompson-rivers",
    "thompson-rivers-university",
    "trinity western university",
    "trinity-western",
    "trinity-western-university",
    "tru",
    "twu",
    "ubc",
    "ubc okanagan",
    "ubc-okanagan",
    "ufv",
    "unbc",
    "uo",
    "victoria",
    "victoria univ.",
    "victoria-univ",
    "vu",
    "winnipeg",
  ],
    teamNames: [
    "Alberta",
    "Brandon",
    "Calgary",
    "Lethbridge",
    "MacEwan",
    "Manitoba",
    "Mount Royal",
    "Regina",
    "Saskatchewan",
    "Thompson Rivers",
    "Trinity Western",
    "UBC",
    "UBC Okanagan",
    "UFV",
    "UNBC",
    "Victoria",
    "Winnipeg",
    "alberta",
    "brandon",
    "brandon university",
    "brandon-university",
    "calgary",
    "lethbr",
    "lethbridge",
    "macewan",
    "macewan university",
    "macewan-university",
    "manitoba",
    "manitoba univ.",
    "manitoba university",
    "manitoba-univ",
    "manitoba-university",
    "mount royal cougars",
    "mount royal university",
    "mount-royal",
    "mount-royal-cougars",
    "mount-royal-university",
    "mrc",
    "mru",
    "regina",
    "saskatchewan",
    "thompson rivers university",
    "thompson-rivers",
    "thompson-rivers-university",
    "trinity western university",
    "trinity-western",
    "trinity-western-university",
    "tru",
    "twu",
    "ubc",
    "ubc okanagan",
    "ubc-okanagan",
    "ufv",
    "unbc",
    "uo",
    "victoria",
    "victoria univ.",
    "victoria-univ",
    "vu",
    "winnipeg",
  ],
    canonicalSchools: [
    "Alberta",
    "Brandon",
    "Calgary",
    "Lethbridge",
    "MacEwan",
    "Manitoba",
    "Mount Royal",
    "Regina",
    "Saskatchewan",
    "Thompson Rivers",
    "Trinity Western",
    "UBC",
    "UBC Okanagan",
    "UFV",
    "UNBC",
    "Victoria",
    "Winnipeg",
  ],
  },  {
    slug: "ontario-university-athletics",
    name: "Ontario University Athletics",
    teamSlugs: [
    "Algoma",
    "Brock",
    "Carleton",
    "Guelph",
    "Lakehead",
    "Laurentian",
    "Laurier",
    "McMaster",
    "Nipissing",
    "Ontario Tech",
    "Ottawa",
    "Queen's",
    "Toronto",
    "Toronto Metropolitan",
    "Waterloo",
    "Western",
    "Windsor",
    "York",
    "algoma",
    "algoma university",
    "algoma-university",
    "au",
    "brock",
    "brock university",
    "brock-university",
    "bu",
    "carleton",
    "carleton university",
    "carleton-university",
    "cu",
    "guelph",
    "lakehead",
    "lakehead university",
    "lakehead-university",
    "laurentian",
    "laurentian university",
    "laurentian-university",
    "laurier",
    "laurier university",
    "laurier-university",
    "lu",
    "mcmaster",
    "mcmaster university",
    "mcmaster-university",
    "nipissing",
    "nipissing university",
    "nipissing-university",
    "nu",
    "ontario tech university",
    "ontario-tech",
    "ontario-tech-university",
    "os",
    "ottawa",
    "ottawa s.",
    "ottawa-s",
    "otu",
    "qc",
    "qu",
    "queen",
    "queen'",
    "queen's",
    "queen's college",
    "queen's university",
    "queen-s",
    "queen-s-college",
    "queen-s-university",
    "queens",
    "queens-college",
    "queens-university",
    "tmu",
    "toronto",
    "toronto metropolitan university",
    "toronto univ.",
    "toronto-metropolitan",
    "toronto-metropolitan-university",
    "toronto-univ",
    "tu",
    "waterloo",
    "waterloo university",
    "waterloo-university",
    "we",
    "western",
    "western ontario",
    "western university canada",
    "western-ontario",
    "western-university-canada",
    "windsor",
    "windsor exp.",
    "windsor-exp",
    "wo",
    "wu",
    "wuc",
    "york",
    "york university",
    "york-university",
    "yu",
  ],
    teamNames: [
    "Algoma",
    "Brock",
    "Carleton",
    "Guelph",
    "Lakehead",
    "Laurentian",
    "Laurier",
    "McMaster",
    "Nipissing",
    "Ontario Tech",
    "Ottawa",
    "Queen's",
    "Toronto",
    "Toronto Metropolitan",
    "Waterloo",
    "Western",
    "Windsor",
    "York",
    "algoma",
    "algoma university",
    "algoma-university",
    "au",
    "brock",
    "brock university",
    "brock-university",
    "bu",
    "carleton",
    "carleton university",
    "carleton-university",
    "cu",
    "guelph",
    "lakehead",
    "lakehead university",
    "lakehead-university",
    "laurentian",
    "laurentian university",
    "laurentian-university",
    "laurier",
    "laurier university",
    "laurier-university",
    "lu",
    "mcmaster",
    "mcmaster university",
    "mcmaster-university",
    "nipissing",
    "nipissing university",
    "nipissing-university",
    "nu",
    "ontario tech university",
    "ontario-tech",
    "ontario-tech-university",
    "os",
    "ottawa",
    "ottawa s.",
    "ottawa-s",
    "otu",
    "qc",
    "qu",
    "queen",
    "queen'",
    "queen's",
    "queen's college",
    "queen's university",
    "queen-s",
    "queen-s-college",
    "queen-s-university",
    "queens",
    "queens-college",
    "queens-university",
    "tmu",
    "toronto",
    "toronto metropolitan university",
    "toronto univ.",
    "toronto-metropolitan",
    "toronto-metropolitan-university",
    "toronto-univ",
    "tu",
    "waterloo",
    "waterloo university",
    "waterloo-university",
    "we",
    "western",
    "western ontario",
    "western university canada",
    "western-ontario",
    "western-university-canada",
    "windsor",
    "windsor exp.",
    "windsor-exp",
    "wo",
    "wu",
    "wuc",
    "york",
    "york university",
    "york-university",
    "yu",
  ],
    canonicalSchools: [
    "Algoma",
    "Brock",
    "Carleton",
    "Guelph",
    "Lakehead",
    "Laurentian",
    "Laurier",
    "McMaster",
    "Nipissing",
    "Ontario Tech",
    "Ottawa",
    "Queen's",
    "Toronto",
    "Toronto Metropolitan",
    "Waterloo",
    "Western",
    "Windsor",
    "York",
  ],
  },  {
    slug: "rseq",
    name: "RSEQ",
    teamSlugs: [
    "Bishop's",
    "Concordia",
    "Laval",
    "McGill",
    "UQAM",
    "bishop's university",
    "bishop-s-university",
    "bishops",
    "bishops-university",
    "concor",
    "concordia",
    "laval",
    "mcgill",
    "mcgill university",
    "mcgill-university",
    "uqam",
  ],
    teamNames: [
    "Bishop's",
    "Concordia",
    "Laval",
    "McGill",
    "UQAM",
    "bishop's university",
    "bishop-s-university",
    "bishops",
    "bishops-university",
    "concor",
    "concordia",
    "laval",
    "mcgill",
    "mcgill university",
    "mcgill-university",
    "uqam",
  ],
    canonicalSchools: [
    "Bishop's",
    "Concordia",
    "Laval",
    "McGill",
    "UQAM",
  ],
  },
] as const;

const CANONICAL_SCHOOL_TO_CONFERENCE: Record<string, string> = {
  "acadia": "atlantic-university-sport",
  "alberta": "canada-west",
  "algoma": "ontario-university-athletics",
  "bishops": "rseq",
  "brandon": "canada-west",
  "brock": "ontario-university-athletics",
  "calgary": "canada-west",
  "cape-breton": "atlantic-university-sport",
  "carleton": "ontario-university-athletics",
  "concordia": "rseq",
  "dalhousie": "atlantic-university-sport",
  "guelph": "ontario-university-athletics",
  "lakehead": "ontario-university-athletics",
  "laurentian": "ontario-university-athletics",
  "laurier": "ontario-university-athletics",
  "laval": "rseq",
  "lethbridge": "canada-west",
  "macewan": "canada-west",
  "manitoba": "canada-west",
  "mcgill": "rseq",
  "mcmaster": "ontario-university-athletics",
  "memorial": "atlantic-university-sport",
  "mount-royal": "canada-west",
  "nipissing": "ontario-university-athletics",
  "ontario-tech": "ontario-university-athletics",
  "ottawa": "ontario-university-athletics",
  "queens": "ontario-university-athletics",
  "regina": "canada-west",
  "saint-marys": "atlantic-university-sport",
  "saskatchewan": "canada-west",
  "stfx": "atlantic-university-sport",
  "thompson-rivers": "canada-west",
  "toronto": "ontario-university-athletics",
  "toronto-metropolitan": "ontario-university-athletics",
  "trinity-western": "canada-west",
  "ubc": "canada-west",
  "ubc-okanagan": "canada-west",
  "ufv": "canada-west",
  "unb": "atlantic-university-sport",
  "unbc": "canada-west",
  "upei": "atlantic-university-sport",
  "uqam": "rseq",
  "victoria": "canada-west",
  "waterloo": "ontario-university-athletics",
  "western": "ontario-university-athletics",
  "windsor": "ontario-university-athletics",
  "winnipeg": "canada-west",
  "york": "ontario-university-athletics"
};

const DB_ALIAS_TO_CANONICAL_SCHOOL: Record<string, string> = {
  "acadia university": "acadia",
  "acadia-university": "acadia",
  "algoma university": "algoma",
  "algoma-university": "algoma",
  "au": "algoma",
  "bishop's university": "bishops",
  "bishop-s-university": "bishops",
  "bishops-university": "bishops",
  "brandon university": "brandon",
  "brandon-university": "brandon",
  "brock university": "brock",
  "brock-university": "brock",
  "bu": "brock",
  "cape breton h.": "cape-breton",
  "cape breton highlanders": "cape-breton",
  "cape breton university": "cape-breton",
  "cape-breton-h": "cape-breton",
  "cape-breton-highlanders": "cape-breton",
  "cape-breton-university": "cape-breton",
  "carleton university": "carleton",
  "carleton-university": "carleton",
  "cbh": "cape-breton",
  "cbu": "cape-breton",
  "concor": "concordia",
  "concordia": "concordia",
  "cu": "carleton",
  "dalhousie university": "dalhousie",
  "dalhousie-university": "dalhousie",
  "du": "dalhousie",
  "lakehead university": "lakehead",
  "lakehead-university": "lakehead",
  "laurentian university": "laurentian",
  "laurentian-university": "laurentian",
  "laurier university": "laurier",
  "laurier-university": "laurier",
  "lethbr": "lethbridge",
  "lethbridge": "lethbridge",
  "lu": "laurier",
  "macewan university": "macewan",
  "macewan-university": "macewan",
  "manitoba univ.": "manitoba",
  "manitoba university": "manitoba",
  "manitoba-univ": "manitoba",
  "manitoba-university": "manitoba",
  "mcgill university": "mcgill",
  "mcgill-university": "mcgill",
  "mcmaster university": "mcmaster",
  "mcmaster-university": "mcmaster",
  "memori": "memorial",
  "memorial": "memorial",
  "memorial university": "memorial",
  "memorial university of new foundland": "memorial",
  "memorial university of newfoundland": "memorial",
  "memorial-university": "memorial",
  "memorial-university-of-new-foundland": "memorial",
  "memorial-university-of-newfoundland": "memorial",
  "mount royal cougars": "mount-royal",
  "mount royal university": "mount-royal",
  "mount-royal-cougars": "mount-royal",
  "mount-royal-university": "mount-royal",
  "mrc": "mount-royal",
  "mru": "mount-royal",
  "mu": "memorial",
  "muon": "memorial",
  "muonf": "memorial",
  "nipissing university": "nipissing",
  "nipissing-university": "nipissing",
  "nu": "nipissing",
  "ontario tech university": "ontario-tech",
  "ontario-tech-university": "ontario-tech",
  "os": "ottawa",
  "ottawa s.": "ottawa",
  "ottawa-s": "ottawa",
  "otu": "ontario-tech",
  "qc": "queens",
  "qu": "queens",
  "queen'": "queens",
  "queen's": "queens",
  "queen's college": "queens",
  "queen's university": "queens",
  "queen-s": "queens",
  "queen-s-college": "queens",
  "queen-s-university": "queens",
  "queens": "queens",
  "queens-college": "queens",
  "queens-university": "queens",
  "saint mary's university": "saint-marys",
  "saint-mary-s-university": "saint-marys",
  "saint-marys-university": "saint-marys",
  "smu": "saint-marys",
  "st-francis-x": "stfx",
  "st.francis x.": "stfx",
  "stfrancis-x": "stfx",
  "sx": "stfx",
  "thompson rivers university": "thompson-rivers",
  "thompson-rivers-university": "thompson-rivers",
  "tmu": "toronto",
  "toronto metropolitan university": "toronto",
  "toronto univ.": "toronto",
  "toronto-metropolitan-university": "toronto",
  "toronto-univ": "toronto",
  "trinity western university": "trinity-western",
  "trinity-western-university": "trinity-western",
  "tru": "thompson-rivers",
  "tu": "toronto",
  "twu": "trinity-western",
  "ubc": "ubc",
  "ubc okanagan": "ubc-okanagan",
  "ubc-okanagan": "ubc-okanagan",
  "ufv": "ufv",
  "unb": "unb",
  "unb saint john": "unb",
  "unb-saint-john": "unb",
  "unbc": "unbc",
  "uo": "ubc-okanagan",
  "upei": "upei",
  "uqam": "uqam",
  "usj": "unb",
  "victoria univ.": "victoria",
  "victoria-univ": "victoria",
  "vu": "victoria",
  "waterloo university": "waterloo",
  "waterloo-university": "waterloo",
  "we": "windsor",
  "western ontario": "western",
  "western university canada": "western",
  "western-ontario": "western",
  "western-university-canada": "western",
  "windsor exp.": "windsor",
  "windsor-exp": "windsor",
  "wo": "western",
  "wu": "waterloo",
  "wuc": "western",
  "york university": "york",
  "york-university": "york",
  "yu": "york"
};

const CURRENT_TEAM_SLUGS = new Set<string>([
  "acadia-university",
  "algoma-university",
  "bishop-s-university",
  "brandon-university",
  "brock-university",
  "cape-breton-university",
  "carleton-university",
  "concordia",
  "lakehead-university",
  "laurentian-university",
  "laurier-university",
  "lethbridge",
  "mcgill-university",
  "mcmaster-university",
  "memorial",
  "memorial-university",
  "mount-royal-university",
  "nipissing-university",
  "ontario-tech-university",
  "queen-s",
  "queen-s-university",
  "saint-mary-s-university",
  "st-francis-x",
  "thompson-rivers-university",
  "tmu",
  "toronto-metropolitan-university",
  "trinity-western-university",
  "tru",
  "twu",
  "ubc",
  "ubc-okanagan",
  "ufv",
  "unb",
  "unbc",
  "upei",
  "uqam",
  "waterloo-university",
  "western-university-canada",
  "york-university"
]);

const grouper = createCollegeConferenceGrouper({
  conferences: CONFERENCES,
  canonicalSchoolToConference: CANONICAL_SCHOOL_TO_CONFERENCE,
  dbAliasToCanonicalSchool: DB_ALIAS_TO_CANONICAL_SCHOOL,
  currentTeamSlugs: CURRENT_TEAM_SLUGS,
  requireCurrentTeam: true,
});

export const USPORTS_CONFERENCES = CONFERENCES;
export const OTHER_USPORTS_CONFERENCE_SLUG = grouper.OTHER_SLUG;
export const conferenceForUSportsTeam = grouper.conferenceForTeam;
export const getUSportsConference = grouper.getConference;
export const groupUSportsTeamsByConference = grouper.groupTeamsByConference;
